### ISSUE TITLE
Feature: allow a user to select what branch to use

### ISSUE THREAD

**Issue by jplattel** [denolehov/obsidian-git#1]
Hi! Thanks for this wonderful plugin! I have a feature request, which would be the following:

- [ ] Allow a user to input the branch name in the settings
- [x] Use the specified branch (or default to master) to sync.

I'm using the `main` branch instead of `master`.  So that's the reasoning behind it.

Thanks!

**Comment by denolehov** [comment]
Hey, thank you for your feedback! This is actually next feature to implement on my list! :smile: 

I plan to work on this later today :)

**Comment by jplattel** [comment]
Awesome, thanks! 👍

**Comment by denolehov** [comment]
hey @jplattel! just released a version that autodetects current working branch, you can also choose between local, existing branches in the settings.

I have been thinking about actually creating and managing _new_ branches from within Obsidian, but at the moment I don't think that there is a strong need for that. Power users are going to manage their git repositories from command line anyways, and not-so-technical users don't use branches that much anyways (for vault backup purposes). 

I am not removing this from my radar, and this is something I consider adding in the future, once I collect enough feedback on the matter.

:heart:
