### ISSUE TITLE
Push to multiple remotes

### ISSUE THREAD

**Issue by snird** [denolehov/obsidian-git#101]
I know the use-case is over paranoidic, yet it's worth bringing up:

Can we have a configuration to push to multiple remotes?
Such that I won't have to rely on github alone for example, but I can add gitlab too - lowering the risk that any one of the centralized git repos will be out in the future.

**Comment by Vinzent03** [comment]
I think it is pretty unlikely that you lose your local copy and GitHub is down, but before I have to change something, does this guide work? https://leighmcculloch.com/posts/git-push-to-multiple-remotes-at-once/

**Comment by snird** [comment]
The guide looks like a valid solution, thank you!
I'll try it and report back. I haven't thought about resolving this from the git side.

**Comment by snird** [comment]
I can confirm this approach works. Thank you.
