### ISSUE TITLE
How to work with ssh login?

### ISSUE THREAD

**Issue by hsayed21** [denolehov/obsidian-git#102]
I want to add ssh login to automatically push to the repo.
If there are configuration  should apply

**Comment by Vinzent03** [comment]
The plugin just runs `git push`. The remote url needs to be properly set, because it is different from the https url. Please take a look at https://github.com/denolehov/obsidian-git/wiki#ssh-authentication and explain further what exactly doesn't work.

**Comment by Vinzent03** [comment]
Closing because of the thumps up from the author.
