### ISSUE TITLE
[Bug]: Recurrent error "git obsidian error: Not all of the required configs are set. See README"

### ISSUE THREAD

**Issue by pcuellar** [denolehov/obsidian-git#103]
### Describe the bug

I'm on v1.10.0. 
I am repeatedly getting an error "git obsidian error: Not all of the required configs are set. See README"
<img width="531" alt="Screen Shot 2021-08-14 at 3 56 23 PM" src="https://user-images.githubusercontent.com/20482146/129458760-1d0361d2-3b38-4e55-bb13-b3b784f8db66.png">
The plugin though seems to be working fine (see screenshot) and my configuration hasn't changed.
<img width="768" alt="Screen Shot 2021-08-14 at 3 57 03 PM" src="https://user-images.githubusercontent.com/20482146/129458767-dabd3933-1661-4585-bf74-cda3a4e0538b.png">

### Steps to reproduce

Updated to v1.10.0 and started seeing this issue.

### Addition context

More worryingly, I noticed that after this error began to show, performance in Obsidian slows when the plugin is activated, with the settings page taking a few seconds to appear and scroll on setting pages lagging. If I disable the plugin and reload Obsidian, things go back to normal.

**Comment by Vinzent03** [comment]
I am sorry to hear that. Can you confirm that in `git/config` `user.name` `user.email` and `remote.origin.url` are set. This requires the remote to be named `origin`. If it is not called like that, please try to rename it.
Regarding your performance, I don't really know what is causing the issue.

**Comment by pcuellar** [comment]
Thanks for the fast reply. Indeed setting `user.name` and user.email` made the error go away. Performance, however, is still affected. Any local test I can run to verify the source of this?

**Comment by Vinzent03** [comment]
It's strange that the `user` properties are missing. Without them, you shouldn't be able to commit before too.

Can you downgrade to `1.9.3` and confirm that the performance is better?

**Comment by pcuellar** [comment]
Email was missing after I changed authentication to token, but I supposed pwd properties were still there? 

I installed `1.9.3`, restarted and performance is back to normal. Tomorrow when I am back at my computer I can upgrade again and see how that works. Let me know if you need me to do anything before I switch back to `1.10.0`

**Comment by firinael** [comment]
> I am sorry to hear that. Can you confirm that in `.git/config` `user.name` `user.email` and `remote.origin.url` are set. This requires the remote to be named `origin`. If it is not called like that, please try to rename it.
> Regarding your performance, I don't really know what is causing the issue.

Just added the `user.name` and `user.email` lines and values and now the notification doesn't show up anymore, but these weren't even there before, not even empty.

Perhaps something to do with updating the plugin, as I had it working perfectly before, too, without setting any of that. Also, the README (here in GitHub) does not say what you're supposed to do so that error message should either be changed or the README should be updated.

**Comment by Vinzent03** [comment]
@firinael Oh you are right. The README has changed, so it is not there anymore. Will remove the check, because it causes just problems. The source of the check is the mobile pr. A check was needed there.

**Comment by Vinzent03** [comment]
Fixed in new [release](https://github.com/denolehov/obsidian-git/releases/tag/1.10.1)
