### ISSUE TITLE
[Bug]: Uncaught (in promise) TypeError

### ISSUE THREAD

**Issue by firinael** [denolehov/obsidian-git#107]
### Describe the bug

This error shows up:

![image](https://user-images.githubusercontent.com/67032657/131060162-a97921ed-dfc4-4836-a7c5-ab66133d2a9f.png)

I'm no dev. so I've no idea what that means, but it might be an issue?

### Steps to reproduce

Just open the app with the plugin on.

**Comment by Vinzent03** [comment]
Honestly, I have no clue what could cause this error. I can't reproduce, so it's hard to fix. Does the plugin work, though?

**Comment by firinael** [comment]
oh wow what the fuck, it doesn't.

it hasn't worked for 2 months now, it seems.

**Comment by firinael** [comment]
`fatal: bad config line 17 in file .git/config
fatal: bad config line 17 in file .git/config
    while executing
"close $fd"
    (procedure "git" line 5)
    invoked from within
"git config --global --add gui.recentrepo $path"
    (procedure "_append_recentrepos" line 14)
    invoked from within
"_append_recentrepos [pwd]"
    (procedure "choose_repository::_do_open2" line 12)
    invoked from within
"choose_repository::_do_open2 ::choose_repository::__o1::__d"
    invoked from within
".buttons.next invoke "
    invoked from within
".buttons.next instate !disabled { .buttons.next invoke } "
    invoked from within
".buttons.next instate pressed { .buttons.next state !pressed; .buttons.next instate !disabled { .buttons.next invoke } } "
    (command bound to event)`

might have something to do with this? popped up when I tried opening my vault with the Git GUI

**Comment by Vinzent03** [comment]
I am doing this in my free time, so please be a bit more polite. Thanks.
Well, that could cause the issue. Could you send me your config? It's in `.git/config`.

**Comment by firinael** [comment]
I'm sorry! Didn't mean to be rude, the "what the fuck" was at myself for not having noticed that there were no pushes happening! I've attached a screenshot showing what the config looks like.

**Comment by Vinzent03** [comment]
Okay, sorry. I misunderstood your message. Sorry to hear that your vault was not synced for two months. In line 16 is a `[user]` missing. I hope it works now.

**Comment by firinael** [comment]
No problem! I'm too used to swearing for no reason, lol.

Changing line 16 onwards to this:

![image](https://user-images.githubusercontent.com/67032657/131263964-c5a32508-2126-48d6-b182-115953253a2d.png)

Fixed it, working perfectly now!

**Comment by Vinzent03** [comment]
I don't think you need the "firinael" in `[user]`. Just `[user]` should be enough. You can delete the comment to protect the email if you want to. Happy that it works.
