### ISSUE TITLE
Allow specifying custom repository root

### ISSUE THREAD

**Issue by denolehov** [denolehov/obsidian-git#11]
Expose a setting for specifying a custom repository root in order to cover [use-case](https://github.com/denolehov/obsidian-git/issues/7#issuecomment-722032481) where git repo is not in the root of the vault, but in one of the subfolders that users wish to backup.

**Comment by dummifiedme** [comment]
Related to this

My use case is my github repo is say Folder A, and I want a subfolder B to be my Vault. Will it work if I work on folder B from Obsidian? or the I have to compulsarily make Folder A as my Vault.

**Comment by denolehov** [comment]
As of right now, you'd have to make Folder A as your vault. Plugin looks for git repo in the root of the vault.
