### ISSUE TITLE
[Bug]: Plugin doesn't work for rename folder.

### ISSUE THREAD

**Issue by keyskull** [denolehov/obsidian-git#111]
### Describe the bug

When I rename a folder, it will make a copy from the original folder and the original folder still exist on the branch.

### Steps to reproduce

Rename folder in Obsidian.
![screencast](https://user-images.githubusercontent.com/3397225/133341225-432262d9-cb6c-4eb1-9a3e-dbdc968ce14e.gif)

### Expected Behavior

Record rename action on one commit.

### Operating system

Windows 10

git version 2.32.0.windows.2

**Comment by Vinzent03** [comment]
What do you exactly mean with the original folder still exists? If you create a backup (commit) nothing should change in your working directory. The plugin doesn't do anything until you call a command.

**Comment by keyskull** [comment]
So, do the rename process for a folder. For example, the `article` folder rename to the `publish` folder. the new commit will become have both of the folders and having the same duplicated files in those folders.

**Comment by Vinzent03** [comment]
Sorry I don't know what's wrong with your setup, but I cannot reproduce. Please disable all other plugins, restart and try again. Maybe even in another vault. Maybe it's some other sync service.

**Comment by denolehov** [comment]
@keyskull how did you rename a folder? from within Obsidian? I tried it as well and couldn't reproduce the issue.

**Comment by keyskull** [comment]
[](url)
![screencast](https://user-images.githubusercontent.com/3397225/133341225-432262d9-cb6c-4eb1-9a3e-dbdc968ce14e.gif)
