### ISSUE TITLE
Set custom OS git binary path OR Support custom git SSH keys

### ISSUE THREAD

**Issue by maximberezin97** [denolehov/obsidian-git#113]
I am trying to set up an Obsidian vault by cloning a Git repository with SSH on Windows. I manage my locally cloned git repos within the WSL filesystem particularly because Git on Windows is not convenient out of the box. Git for Windows depends on MinGW (which is relatively inconvenient) and SSH key and startup agent configuration is not as simple as it should be. Interacting with Git through Windows CMD or PowerShell has not been straightforward in my experience either.

Windows Subsystem for Linux, however, makes it as simple as running a Linux VM and bridging the host/guest filesystems. I can also explore it using Windows File Explorer by mounting the virtual disk image as a network drive, such as `\\wsl$\Ubuntu\ = L:\` However, this is not a complete solution either. I cannot use this git plugin to automatically push/pull commits because Obsidian running on the Windows host is not aware of the git in the WSL VM.

My JavaScript is mediocre and I haven't read into the code to see how git is implemented here. If it so happens that it depends on the OS git installation, perhaps there could be a way to point Obsidian to a different git path, like with an environment variable.

Or perhaps this could be fixed by having the option to add custom SSH keys. I see previous discussion on this on https://github.com/denolehov/obsidian-git/issues/32. If this is more relevant could someone please help me apply that to this case?

**Comment by Vinzent03** [comment]
Available in new [release](https://github.com/denolehov/obsidian-git/releases/tag/1.12.0). I hope it works for you.

**Comment by maximberezin97** [comment]
Thank you for the quick release, it's exactly what I asked for.

Unfortunately it did not fix my original problem. I tried setting the custom git binary path to `wsl git`, `'wsl git'`, setting a local-user-specific environment variable (the same non-admin user is running Obsidian) `WSLGIT='wsl git'` and setting the binary path to `WSLGIT`, and `%WSLGIT%`, all of which result in the following error:

![wsl_git](https://user-images.githubusercontent.com/12620705/134428409-837604c8-db94-4281-895a-42e8b432410e.png)

It appears Obsidian or the git library cannot find the `wsl` command. This is more likely an issue with my setup than this plugin, so I'll leave this issue closed and attempt to solve it myself.

Thanks again for your help.

**Comment by Vinzent03** [comment]
Sorry to hear that. I've never used wsl, so I don't know what's the issue is, too. Maybe try with file path to either wsl or git or even both instead of just the binary file name.
