### ISSUE TITLE
I get a "# Conflict files" every single time opening the same vault in another computer

### ISSUE THREAD

**Issue by rzfzr** [denolehov/obsidian-git#114]
It's always the same file
```
# Conflict files
Please resolve them and commit per command (This file will be deleted before the commit).
- Not a file: .obsidian/workspace
```

**Comment by Vinzent03** [comment]
First, there is a bug report template, so please use it. I strongly suggest you to add this file to `.gitignore`. See https://github.com/denolehov/obsidian-git/wiki/Tips-and-Tricks#gitignore. So add the file to `.gitignore` and run `git rm --cached .obsidian/workspace`. Finally, commit everything.
By the way. What exactly do you mean with it opens every single time. Do you have auto backup/pull turned on?

**Comment by rzfzr** [comment]
Hi, sorry for not using the template, I suspected it might not been a bug.
I do have the auto pull and commit set to 5/2 minutes respectively.
I mean every time in the sense that I'm working on pc A, make some changes and save with "Create backup" command, I open pc B witches autopulls when opening Obsidian, I get this conflict.
The few times that worked seamlessly bringing back even the open note was very nice, but I'll add the files to .gitignore as recommended, thanks

**Comment by Vinzent03** [comment]
I see your point. Yeah, saving the workspace file can be convenient, but creates merge conflicts too often.

**Comment by HuangZhuo** [comment]
sometimes it's useful to sync the workspace file, my way to solve this is run a simple sync.sh file to revert the workspace file before pull from the repo.
```
# revert workspace file
git checkout .obsidian/workspace
git pull --rebase --autostash
```

**Comment by rzfzr** [comment]
I know this was closed, but I removed the files from my .gitignore and I think I discovered the root of the issue.
Whenever I open the repository on a git client, with obsidian closed, .obsidian/workspace always has unstaged changes, maybe the file is edited on the closing process, after the last push?
![image](https://user-images.githubusercontent.com/13456224/148705744-fc57461b-6cca-4303-8365-821ca58b9742.png)

**Comment by coolcodecding** [comment]
I'm having the same issue and can confirm @rzfzr observation. Is there a permanent fix?
From what I see the workspace.json is quite important so ignoring it doesn't seem to be a good idea.

**Comment by Vinzent03** [comment]
@coolcodecding It just stores the layout of Obsidian. Like which files are opened. This changes a lot and is different from each device. There are no issues with ignoring it despite your layout is not synced with other devices.

**Comment by coolcodecding** [comment]
@Vinzent03 Thanks for making this clear! I guess this will be a great relief!

**Comment by ghostkaa** [comment]
@Vinzent03 is it possible to create a command like “Reset all local changes”? Now I unable to pull any changes on my iPad getting merge conflict. Option reset local changes would be helpful, I guess in this case

**Comment by Vinzent03** [comment]
@ghostkaa There is a button in the source control View. Just press the arrow in the "Changes" row

**Comment by pierre-mike-pge** [comment]
I'm having the same issue, I may try to just add to the .gitignore, as this is just needed for each local app and do not have to be shared across device

**Comment by Sejmou** [comment]
might be a dumb question, but where is the source control view? I cannot find it on my iPad

**Comment by rzfzr** [comment]
> note: if you cannot find the 'Source Control View' (like me - was looking for it for a while 😅), it's also in the command palette ('Open source control view').

I just took a screenshot to show you this haha, bit late
![image](https://github.com/denolehov/obsidian-git/assets/13456224/43e1cc27-f75f-4daa-9cfe-62a5aa27a9ff)

**Comment by xero** [comment]
for future googlers:

the wiki page linked above doesn't exist. but i was able to solve this problem with a `.gitignore` with the following values:

```
.obsidian/workspace-mobile.json
.obsidian/workspace.json
.obsidian/workspace
.obsidian/plugins/home-tab/data.json
```

i have a few other plugins `data.json` files ignored w/o issue as well
