### ISSUE TITLE
[Bug]: Can't open file with whitespace in path

### ISSUE THREAD

**Issue by NomarCub** [denolehov/obsidian-git#119]
### Describe the bug

When I open the changelist and choose a file with whitespace in its path (its name or some of its parent folders) it doesn't open and results in an error.

![image](https://user-images.githubusercontent.com/5298006/135420383-e084af37-87cb-4d37-bb95-318ce30f7336.png)

![image](https://user-images.githubusercontent.com/5298006/135421220-5c6c8fe5-7ade-41c3-984e-061d94c18043.png)

### Steps to reproduce

Have a file with changes that has whitespace in its path.
Execute the `Obsidian Git: List changed files` command.
Select the aforementioned file.

### Operating system

Windows

**Comment by Vinzent03** [comment]
Oh you are right. It's caused by the underlying git library. They add some `"`.  Should be fixed now
