### ISSUE TITLE
Prerequisite Software?

### ISSUE THREAD

**Issue by mrkhdly** [denolehov/obsidian-git#12]
Is anything else need to be installed or do you just need Obsidian installed & this plugin?

**Comment by denolehov** [comment]
Hey, you need to have `git` installed, as well as repository initialized both locally and on github/gitlab/etc. In other words, you should be able to push/pull changes from remote repo from command line manually.

**Comment by mrkhdly** [comment]
Okay thanks for confirming. Appreciate the quick response.
