### ISSUE TITLE
Can't Push.  Upstream branch of your current branch does not match the name of current branch

### ISSUE THREAD

**Issue by josh-spatial** [denolehov/obsidian-git#120]
### Describe the bug

Commits work fine.  Pulling is fine.  Get's stuck pushing with this error.  I'm not sure if this is an ssh issue or what.  GitHub Desktop pushes the commit fine.  I'm using SSH without a passphrase.

![Screen Shot 2021-09-30 at 6 29 33 AM](https://user-images.githubusercontent.com/72358384/135440015-52b748e2-37e2-4eec-814f-a98f179defbb.png)

### Steps to reproduce

Set up automatic pushes.

### Operating system

macOS

**Comment by Vinzent03** [comment]
Did you rename your local branch? I don't think git likes an upstream branch called differently from a local branch.

**Comment by josh-spatial** [comment]
I don't think I renamed it?  How do I check this?  Both should be "main" correct?

**Comment by Vinzent03** [comment]
correct

**Comment by josh-spatial** [comment]
Do you know how I would check the branch names?

**Comment by Vinzent03** [comment]
Just go to your remote repo on GitHub. The branch name is shown above the file list.

**Comment by josh-spatial** [comment]
There is only one branch: main.

**Comment by josh-spatial** [comment]
Maybe it is because my current branch in Obsidian Git Plugin options is "Master" not "main"?  I can't change it?

**Comment by Vinzent03** [comment]
Could you run `git branch` in the terminal and share the output? I want to see which local branches you have.

**Comment by josh-spatial** [comment]
So I actually deleted everything.  Uninstalled the plugin, and then I recloned my repo and then reinstalled the plugin.  Now the branch matches in the plugin `main`.   Which is the only branch that I have.  It must've been a setting I had in git for `push HEAD:master` or something from previous tinkering


But now it won't pull, says that I need to set my username.  I am using Github Desktop.

**Comment by robinwassen** [comment]
I just wanted to say that I ended up with the same issue when setting up a git repository using the command palette "Git: Initialize new repo", the first push worked and after that I got the error.

Fired up git in a terminal, removed the remotes and re-added them to solve the issue.
