### ISSUE TITLE
[Bug]: File paths are not properly utf-8 encoded

### ISSUE THREAD

**Issue by NomarCub** [denolehov/obsidian-git#121]
### Describe the bug

When I open the changelist and choose a file with emojis or special characters in its path it doesn't open and results in an error.

My example: `file with 🔥 or ǀ`

(Note that `ǀ` is not the pipe character (`|`) which is forbidden in Windows paths).

![image](https://user-images.githubusercontent.com/5298006/135508956-d93d57a8-94f3-46aa-8ceb-690eee61e073.png)

![image](https://user-images.githubusercontent.com/5298006/135509068-917870de-6a9b-4adf-816c-66d5a385207c.png)

### Steps to reproduce

Have a file with changes that has emojis or special characters in its path.
Execute the `Obsidian Git: List changed files` command.
Select the aforementioned file.

### Operating system

Windows

**Comment by Vinzent03** [comment]
Looks like the path is not properly encoded. This is technically the issue of git itself. If you run `git status` in the terminal, you should the same file path. A fix is running `git config core.quotepath off` in the terminal. Will have to think about a fix from the plugins site.

**Comment by jsmm** [comment]
Thanks for pointing out this thread about Non-ASCII filenames. The behaviour is not happening with Sublime Merge on the same Obsidian vault, so I still wonder if it is a real issue with this plugin.

**Comment by Vinzent03** [comment]
I am now using that setting for every git request, so you don't need to take that setting manually. I hope it has no side effects.
