### ISSUE TITLE
[Bug]: Obisidan becomes very slow when commiting / pushing

### ISSUE THREAD

**Issue by raphaelhuleux** [denolehov/obsidian-git#123]
### Describe the bug

Hey, when I push my vault to Git, Obisidian becomes very slow. Any idea why?

### Steps to reproduce

Push and commit.

### Operating system

macOS

**Comment by miluoshi** [comment]
Did you search other issues? 

It is a known issue of `simple-git` library on MacOS Big Sur. It was discussed here already: https://github.com/denolehov/obsidian-git/issues/69
