### ISSUE TITLE
[Bug]: File log in commit message misformatted

### ISSUE THREAD

**Issue by nivedano** [denolehov/obsidian-git#124]
### Describe the bug

When directory or file names in the repo contain cyrillic symbols, they got inserted as two-bytes unicode escapes. 
E.g. `\320\223\320\276\321\200\320\276\320\264/` instead of `Город`

### Steps to reproduce

1. Create a file with cyrillic name? e.g. `Правильный файл.txt`
2. Allow file log in commit message
3. Push to a repo
4. See unicode escapes in the log

### Expected Behavior

Expected UTF-8 encoding for the God's sake.

### Operating system

Windows

**Comment by Vinzent03** [comment]
Closing in favor of #121
