### ISSUE TITLE
Syncing between Windows and Mac leads to git conflict issues

### ISSUE THREAD

**Issue by kanlanc** [denolehov/obsidian-git#129]
### Describe the bug

The plugin works great on Windows alone and pushing to github, but chaos ensues if I clone the same repo into my MacOS.

Git conflicts come up and solving them in Mac leads to errors in the windows one.

Not sure if this was solved earlier but any help would be really appreciated. Thanks!

### Steps to reproduce

Use in windows and then clone into mac

### Operating system

Windows

**Comment by Vinzent03** [comment]
I guess you have trouble with the `.workspace` file in `.obsidian`. If so, see #114 for more details

**Comment by Vinzent03** [comment]
Closing because of no response. Just comment if you have still problems, and I'm open to reopen the issue.
