### ISSUE TITLE
Question: How do I change branches? The drop down menu doesn't include newly created ones?

### ISSUE THREAD

**Issue by ReaderGuy42** [denolehov/obsidian-git#130]
I created a new branch on github for my repo, but even when I restart Obsidian it doesn't show up in the drop down menu. Am I missing a step? 

I finally got the push & pull to work smoothly, but I'm really not very knowledgeable on git at all, so I apologize if it's obvious.

Thanks :)

**Comment by Vinzent03** [comment]
The branch is only on GitHub and not on your local system. How and why did you create it on GitHub?

**Comment by ReaderGuy42** [comment]
In the repo I click on the main button to the top left of the files. Then it asks if I want to create a new branch.
I thought this would be a good idea to have multiple versions in case something goes wrong. Or does github do that automatically?
Thanks :)

**Comment by Vinzent03** [comment]
Since GitHub is a hub for git, it's all based on commits, so you don't have to create a new branch, since you can just revert a bad commit.

**Comment by ReaderGuy42** [comment]
I have somewhat succesfully set up the plugin, and just now [followed this tutorial](https://renerocks.ai/blog/obsidian-encrypted-github-android/#why-i-prefer-git-and-github) to encrypt my repo-vault.

But no I don't really know much beyond the tutorials, not even sure what a commit is haha

**Comment by Vinzent03** [comment]
I suggest you to learn a bit more about git. But a commit is basically a snapshot of all your files. Every time you want to push your current files to GitHub, you create a new commit, which is based on the previous commit. If something goes wrong, you can reset/revert that commit. You don't need an extra branch.

**Comment by ReaderGuy42** [comment]
Ok, thanks, that's a good idea. Are there any plans of making git-crypt available for the plugin?

**Comment by argenos** [comment]
@Vinzent03 I do have a use case for branches based on the hub. Contributors (those added to the organisation with write access to the hub) can push to different branches for different changes we are working on. Having a drop down menu to switch branches would be great.

**Comment by denolehov** [comment]
@argenos there is already a setting that allows you to switch branches. It's in Settings > Obsidian Git > Current branch.
