### ISSUE TITLE
feat: create and delete branches

### ISSUE THREAD

**Issue by argenos** [denolehov/obsidian-git#132]
In the hub, we have two types of contributors: 
- Those with write access that can use the hub remote
- Those without it that must work in their forks

Eventually, people in the latter group will join the first. Sometimes branches on the hub (see my comment in #130) need to be pulled from upstream as well, for people on the 2nd group too. An easy way to configure additional remotes would be really helpful to hub contributors with little git experience.

**Comment by Vinzent03** [comment]
There is already a command to add new remotes and change the url of existing ones. You can't change the remote of a branch with an existing upstream branch, but if you checkout a new branch, a modal should open to select a remote and branch as upstream branch. I think that's what you need. So I think you are more looking for adding new branches?
