### ISSUE TITLE
[FR] Display Folders In Source Control View

### ISSUE THREAD

**Issue by SlRvb** [denolehov/obsidian-git#134]
Source control view is pretty amazing ❤️‍🔥 The only thing is that it's hard to mass commit files from only a specific folder, I usually stage the folder with a message and then commit it which saves the headache of clicking on 30 files in individually.

As an example, it's especially difficult to tell plugin data stuff apart as I can't see what folder they belong to: 
![Obsidian_X403bWL7zu](https://user-images.githubusercontent.com/54087190/141365501-31d4d6b1-daf4-458a-9e0a-3389c9440a9b.png)

---

It would be incredibly helpful to see the folders, something like how VS Code does it: 
![7mXSfrHO7e](https://user-images.githubusercontent.com/54087190/141365640-cbb1652a-ebf8-4edd-ae90-412bc11e5d64.png)

**Comment by Vinzent03** [comment]
I knew that this request would come xD. Will see when I get the time. VSCode does the git sidebar perfectly.

**Comment by Vinzent03** [comment]
I knew that this request would come xD. Will see when I get the time. VSCode does the git sidebar perfectly.

**Comment by phibr0** [comment]
![image](https://user-images.githubusercontent.com/59741989/147828769-478276ce-64f2-475f-a58c-73a98d38276e.png)
 Done! :partying_face:

Vinzent will review my PR in a few days.
