### ISSUE TITLE
Feature Request: Prompt for Commit Message on Timed Backup

### ISSUE THREAD

**Issue by dylan-k** [denolehov/obsidian-git#135]
There's already the option to have commit and push every X minutes. It's very helpful. But when it does those, there's only a default commit message. Could there be the option for a prompt like "what are you working on right now?" or something, so that the commit includes a note about what's going on? 

I think of [a similar configuration](https://github.com/cmdln/flashbake), although much more detailed, called [flashbake](https://boingboing.net/2009/02/13/flashbake-free-versi.html). That's probably overkill, but it would be nice to have more meaningful messages, optionally. I think a prompt like this should be optional, since it could be distracting in some contexts.

**Comment by Vinzent03** [comment]
Available in new [release](https://github.com/denolehov/obsidian-git/releases/tag/1.15.0). I would say that was fast xD. Just before going to sleep. I hope everything works.

**Comment by dylan-k** [comment]
Thanks for this by the way. I use it a lot and it works well.
