### ISSUE TITLE
Having trouble after reinstall of OS (Linux Mint)

### ISSUE THREAD

**Issue by ReaderGuy42** [denolehov/obsidian-git#137]
I just did a fresh reinstall of Linux Mint 20.2. Before, I'd gotten Obsidian Git to work perfectly. Now I restored all my files and programs and the .ssh file is still where it's supposed to be, but the project is no longer being pushed.
Obsidian Git just keeps telling me everything is up to date, but in my repo I can see that it hasn't updated in several days.
I did "git init" and the thing with remote origin but it just told me that the origin was already there.

Any ideas?
Thanks :)

**Comment by Vinzent03** [comment]
What happens if you run `git pull` in the terminal? Is it the same output?

**Comment by ReaderGuy42** [comment]
It says "Already up to date". 
I should add that since writing this issue I switched my HDD to a SSD but I cloned the disk. Everything works aside from Obsidian Git.
In the console it says 
`Uncaught (in promise) Error: 
*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got '[my-username]@[myusername]-Linux.(none)')

    at Object.action (eval at <anonymous> (app.js:1), <anonymous>:2120:29)
    at PluginStore.exec (eval at <anonymous> (app.js:1), <anonymous>:2155:29)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:2594:43)
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (eval at <anonymous> (app.js:1), <anonymous>:2592:16)
    at GitExecutorChain.eval (eval at <anonymous> (app.js:1), <anonymous>:2576:44)
    at Generator.next (<anonymous>)
    at fulfilled (eval at <anonymous> (app.js:1), <anonymous>:2496:28)```
    
    I did git config for user.email and user.name and then I did another push. It says git Obsidian committed x-number files.  I had refreshed my repo already, but I refreshed it again, and now it says stuff is updated. So I guess I was missing "git config". 

Unless something breaks again, I'll close this. Thanks :smile:
