### ISSUE TITLE
Obsidian option to maximize the screen

### ISSUE THREAD

**Issue by akitxu** [denolehov/obsidian-git#139]
Dear all

We have an option to minimize the screen (top right of the screen). I miss the option to maximize the screen. Kind regards

**Comment by Vinzent03** [comment]
I think you are talking about Obsidian itself and not this plugin.
This is the repo of the Obsidian-Git plugin, not for Obsidian.
Nevertheless, there is a button for maximing if Obsidian is not in full screen. 
![grafik](https://user-images.githubusercontent.com/63981639/142453945-78dc4821-a0fd-4de1-858d-cd564413d893.png)
