### ISSUE TITLE
[Feature request] Commit n minutes after a change

### ISSUE THREAD

**Issue by Sanqui** [denolehov/obsidian-git#140]
Rather than commit in a fixed interval like every 60 minutes, I would like to make a commit when a certain amount of time has elapsed after the last change to a note (such as 10 minutes).  I see a benefit in cleaner file history, because currently it can happen that an automatic commit would happen in the middle of me writing something.  Would this be possible to implement?

**Comment by joelmeyerhamme** [comment]
Seconded, it happens way too often that changes are committed right after I start writing something, leading to lag.

**Comment by Vinzent03** [comment]
I think this is doable. To be honest, git is not made for automatic/timed commits. You commit when you are finished with a certain topic. But you are right, this issue could partly solve that issue.

**Comment by Vinzent03** [comment]
Available in new [release](https://github.com/denolehov/obsidian-git/releases/tag/1.16.0). Let me know if everything works as expected.

**Comment by Sanqui** [comment]
Awesome, I'll give it a spin.  It's small but I'm sure it's a great improvement.  Thanks for implementing it quickly!

**Comment by joelmeyerhamme** [comment]
It's been working very well for me
