### ISSUE TITLE
How do I make git ignore the [.obsidian] folder?

### ISSUE THREAD

**Issue by driftywinds** [denolehov/obsidian-git#144]
Hello I am new to git and my commits keep including the .obsidian folder and pushing that to the repo. I would like for git to ignore that folder, is there a way?
I tried googling but the method of making a [.gitignore] file did not work for me so I thought I'd ask here.

**Comment by Vinzent03** [comment]
You are right. The way to ignore files with git is the `.gitinore` file. You have to place it in the same directory as your `.git` folder. I assume that's your vault. Please try the content for the file as shown [here](https://github.com/denolehov/obsidian-git/wiki/Tips-and-Tricks#gitignore)

**Comment by driftywinds** [comment]
Thanks for the help @Vinzent03 , just to clarify, will this delete the folder from the repo too, or will it just stop pushing the changes in the folder to the repo?

**Comment by Vinzent03** [comment]
If the files are already committed. Please run `git rm --cached .obsidian/` in the terminal and commit afterwards. Now new changes to `.obsidian` shouldn't be recognized anymore.

**Comment by driftywinds** [comment]
Thank you! This worked perfectly.
