### ISSUE TITLE
1.16.0 broke auto-backup, 1.16.2 didn't fix it

### ISSUE THREAD

**Issue by davidculley** [denolehov/obsidian-git#145]
Please make it clearer (during the plugin update process, in the plugin description, etc.) that

1. there is a new toggle in the settings.
2. users need to go to their settings and deactivate that new toggle to restore the previous behavior.

Although you already reverted the value of `autoBackupAfterFileChange` to `false` in `constants.ts`, this does not change the `data.json` file containing the user's preferences.

In the case I updated to plugin version `1.16.0` or `1.16.1`, I'd have the value of `autoBackupAfterFileChange` in `data.json` set to `true`. If I'd then update to version `1.16.2`, the value in `data.json` would still be set to `true` because you only changed it in `constants.ts`. This was the cause of a lot of confusion on my part in the last few days because auto-update was no longer working and I didn't immediately realize why.

Your current solution only works for users who updated from version `1.15.1` or older directly to `1.16.2`. But everyone who had `1.16.0` or `1.16.1` installed in the meantime is, as I suspect, currently wondering why auto-backup is no longer working. At least I was.

https://github.com/denolehov/obsidian-git/blob/d5f148078ee36c98366d91573e4393d6a6ffb250/src/constants.ts#L17

**Comment by Vinzent03** [comment]
Sorry for the inconvenience. I only realized that I made a breaking change the next morning. That's why I reverted that. And warning the user now is too late, because I don't know whether the setting got enabled by the user or by the default config. Will add a notification the next time I add a breaking change.
