### ISSUE TITLE
FR: Status Bar Icon instead of message

### ISSUE THREAD

**Issue by chrisgrieser** [denolehov/obsidian-git#147]
Would it be possible to use some icons to indicate git status instead of the long message? e.g. a checkmark for "everything up to date" arrows up/down for push/pull, etc.

Alternatively, applying css classes for the different states could also be enough, then theme designers like me could simply apply icons per state (right now, it's always the same CSS class, independent of the state).

**Comment by Vinzent03** [comment]
I like the idea, but I don't know if there is a good icon for commits :thinking:

**Comment by chrisgrieser** [comment]
Well, a lack of git icons shouldn't be the problem 🙂 

https://thenounproject.com/search/icons/?iconspage=1&q=git
https://icon-sets.iconify.design/?query=git
https://www.iconfinder.com/search?q=git

Also, if you don't know with one(s) to choose, you can just pick a simple one and assign css classes to the different states – theme designers like me will sort out the rest 🙂
