### ISSUE TITLE
[FR] Longer message timeouts

### ISSUE THREAD

**Issue by mracette** [denolehov/obsidian-git#148]
I am having a hard time reading the popup messages before they disappear. I would love to see the timeout increased significantly (or better yet, have it be a customizable value).

In the long run, I'd love to see an actual persistent log rather than just an ephemeral notification containing the last message, but that's a much bigger scope so perhaps it can be considered a separate request? 

Happy to help with either if you'd like.

**Comment by Vinzent03** [comment]
That's a good idea. You can always see the logs for all plugins by opening the console `CTRL + SHIFT + I`
