### ISSUE TITLE
Feature Request: Command to open File in GitHub Repo

### ISSUE THREAD

**Issue by chrisgrieser** [denolehov/obsidian-git#149]
There is a fantastic plugin for Sublime that, when you trigger it, opens the current line in the remote repository:
https://packagecontrol.io/packages/GitHubinator

Something like this could be useful for the git plugin as well, since it basically provides you convenient access to the history of that particular file.

**Comment by Vinzent03** [comment]
I see you requested a similar feature from koala on discord. But that shows the history and this should link to the direct line, right?

**Comment by chrisgrieser** [comment]
oh right, I forgot that I requested a similar thing in this repo, too. 

Yeah, the Githubinator plugin goes to the direct line. But at least for my use case, the issue is solved by what koala did, so you could also close the issue, your call.

**Comment by Vinzent03** [comment]
@phibr0 already added this in his pr. I have to review it after my holiday.

**Comment by chrisgrieser** [comment]
oh boy, I hope I haven't caused unnecessary duplicate work 🙈 
That wasn't my intention, sorry!
