### ISSUE TITLE
Nested repository backups 

### ISSUE THREAD

**Issue by JoshKing56** [denolehov/obsidian-git#15]
I use nested git repositories to backup parts of my vault in different repositories. This allows me to be able to write notes/documentation that I can share with others in a public github repo, while the rest of my vault remains in a private repo.

Is there a way for this extension to sync _all_ git repos inside of the vault? It doesn't seem to happen by default.

**Comment by denolehov** [comment]
Unfortunately, not at the moment. Plugin looks for one git repo to back up in the root of the vault directory.

**Comment by JoshKing56** [comment]
Ok. Is this a feature that'll be available in the future?

**Comment by denolehov** [comment]
At the moment, I don't plan to implement multi-repo support. Maybe in the future though.

**Comment by Vinzent03** [comment]
Why do you close this? It's still not added. Or because we can't implement this?

**Comment by denolehov** [comment]
It's an old question that has been answered. Me closing this issue doesn't mean we won't do it :) just cleaning up a bit.
