### ISSUE TITLE
[Bug]: css-class "center" messes with slides plugin

### ISSUE THREAD

**Issue by flo-ui** [denolehov/obsidian-git#150]
### Describe the bug

Hi, this is my first bug report, so please give feedback on how i can improve my issuing-skills :)
I noticed the following bug:

The Slides core plugin looks like this when obsidian-git (I am currently using version 1.17.0) is enabled:
![image](https://user-images.githubusercontent.com/63207417/145477525-19867f66-1246-4027-a3e1-09746f0c7d83.png)

- I created a testing vault to verify that this error only occurs with this plugin enabled 
- After that I compared the latest version to an older one (1.15.0) and noticed, that `styles.css` was added recently. 
- After sequentially deleting and restoring parts of that file locally, i came to the conclusion, that the `center` class seems to be the problem.
- My guess is that this class conflicts with the one from obsidian core
- Renaming that class to something else should probably do the trick

Sadly, I don't understand what that class is used for in obsidian-git. 
Creating a pull request by myself would probably break more than fix.

P.S.: I really like this plugin and appreciate your efforts bringing it to mobile :)

### Steps to reproduce

- Create new Vault
- Install obsidian-git
- Enable slides plugin
- Start Presentation

### Expected Behavior

- Full-Screen Slide
![image](https://user-images.githubusercontent.com/63207417/145478820-165da835-1364-4fb8-b9a0-8f82b449713f.png)

### Addition context

https://github.com/denolehov/obsidian-git/commit/5f294a466d62571887fbe4a6c55478990bc9c26c#diff-380b7b38760dd442e897eb0164c58f6a17da966ccaca6318017a468c163979b1

⬆️ that's the commit that introduced the `center` class

### Operating system

Windows

**Comment by Vinzent03** [comment]
Thanks for raising the issue. Should be fixed now.
