### ISSUE TITLE
suggestion: cleaner status bar

### ISSUE THREAD

**Issue by Meikul** [denolehov/obsidian-git#152]
Really like the plugin. I just wish the message in the status bar didn't take up so much space.
`git: last update X minutes ago` is a little wordy.

I think it would look a lot nicer if, instead, it looked something like `<github icon> X min` or at least `git: X min`.
I know that status bar message is also used to show when commits and pushes are made. I think it would be fine to keep those messages pretty much unchanged since they only appear for a few seconds. It's the "last update" message that's visible the vast majority of the time.

btw sorry if an issue isn't the best way to make a suggestion.

**Comment by Vinzent03** [comment]
Are you on the latest version? I just released a new version addressing this issue. See #147 and [1.18.0](https://github.com/denolehov/obsidian-git/releases/tag/1.18.0l)

**Comment by Meikul** [comment]
GAH I promise I looked for existing issues! Updated now. Thanks
