### ISSUE TITLE
Backup only on saving note rather than auto-save?

### ISSUE THREAD

**Issue by ashutoshsaboo** [denolehov/obsidian-git#154]
Thanks @Vinzent03 for all your efforts with this plugin! Currently, i've configured obsidian-git to pull/push if there are any changes every 1 minute (so as to not miss any update). However it seems to consume compute and slightly lags obsidian when i'm still in the middle of editing notes (and the auto backup gets triggered) - it lags on while creating commit/auto-pull/auto-push operations i think. Would be a better option IMO, if there could be a setting added to backup only when a note is saved? GitJournal - https://github.com/GitJournal/GitJournal/ - uses the same strategy and has a very good experience while using it! Can we please add this setting to this plugin too similarly @Vinzent03 ?

**Comment by Vinzent03** [comment]
You mean the autobackup should only get triggered, when you manually save the file? The problem is that Obsidian auto saves your file ca. every 2 seconds.

**Comment by ashutoshsaboo** [comment]
Yes when I manually save it. Or alternatively if in case obsidian vends out relevant functionalities in interface, can be combination of - when a note is switched in editor after some edits and obsidian is quit. Not entirely sure, but from what I've experienced as a user I think GitJournal does the latter so it's pretty seamless even on mobile. (I know there's a long standing issue for this plugin's support for mobile but this would be largely orthogonal and if done correctly would help experience in both desktop + mobile in future as complementary) 

Even if there are not these specifics in the plugin interface (that i mentioned above), just thinking out loud - maybe you could rely on the same obsidian save trigger (even if it's every 2 sec) but with some delay which can be same as the already configured auto-save delay (i.e, trigger git sync only on saves of various files, but apart atleast the set auto-save delay, this ways the background syncing stops atleast). 

Would be really great to have this sort of a sync triggered!

**Comment by Vinzent03** [comment]
Did you see the "new" feature to change to the interval to a time after the last change. So that the auto backup is only fired X minutes after the last change. Maybe that helps you too. In general, why do you want to commit so often? In Obsidian, you switch panes very often, and I don't know why you would want to commit every minute or so.
