### ISSUE TITLE
diff View

### ISSUE THREAD

**Issue by BaumiCoder** [denolehov/obsidian-git#158]
## Use-Case
When I see a changed file in the Source Control, I want to check what have changed there. Maybe there are changes in it, which shouldn't be commited to the repository. This can be an undesigned change in a file for example.
## Specifications for feature
A possibility for viewing the diff of a file could be look like this:

1. A option in the settings for choosing the diff viewer application.
2. calling the function
2.1. Source Control: Double click on a file OR a another Icon on each file
2.2. Obsidian Command: A command to get the diff of the currently open (and active) file in obsidian

**Comment by BaumiCoder** [comment]
Thank you for the fast implementation!

It works fine for markup files, but with files of other kinds it seems to be broken. Another filetype for example is the workspace file of obsidian. A double click on it in the Source Control shows me this message in the Diff View ".obsidian/workspace was deleted".

**Comment by dailyherold** [comment]
Noticed something interesting with my `v0.13.19` appimage build:
- Double click on a modified markdown file to view diff
- The diff pane opens but I get the `path/to/file was deleted` error
- Close Obsidian without changing workspace
- Reopen and I see the proper diff rendered in pane that previously showed the error.

The file I'm using in the example is a normal markdown in a non-hidden directory, part of my main vault. Happy to provide more details if needed. Thanks for the work on this plugin, it's fantastic!

**Comment by Vinzent03** [comment]
@dailyherold sorry, but I can't reproduce. The `xx was deleted` is shown when the file doesn't exist in the Obsidian vault. How is your path exactly formatted and what OS are you using?

**Comment by dailyherold** [comment]
>How is your path exactly formatted
Are you referring to a particular setting? Or just my vault location itself? Vault is nested in my git repo's root, but `.obsidian` in the top/root of my vault path, same level as some organizational directories I use (fleeting/literature/permanent/templates). What's weird is all other functionality seems to work, haven't hit another git operation from quick command or UI button that goes unexpectedly. Just diffing.

OS is PopOS/Ubuntu 20.04.

**Comment by generic-user** [comment]
I seem to have the same problem, could it be the `.` in the foldername?
![image](https://user-images.githubusercontent.com/1516035/153177109-d1799475-8a9d-4a06-bd58-d21fb961b563.png)

**Comment by Vinzent03** [comment]
@generic-user @dailyherold Does the issue still persist. I releases a new version with a different diff view system. It may fixed this issue too.

**Comment by generic-user** [comment]
> @generic-user @dailyherold Does the issue still persist. I released a new version with a different diff view system. It may have fixed this issue too.

Just tested it, and at first glance this the issue is fixed for me, thanks @Vinzent03. 🎉

**Comment by dailyherold** [comment]
Never circled back, but problem resolved for me, thanks!
