### ISSUE TITLE
Keeps showing "git:checking repo status"

### ISSUE THREAD

**Issue by dummifiedme** [denolehov/obsidian-git#16]
How does it work?

I have github client installed, I have a working repo of my vault. I thought this plugin will automatically trigger pushes? But it seems like it's stuck somewhere. Can someone please explain what I need to do to get it up and running?

**Comment by denolehov** [comment]
Please check what errors you see in the console (`ctrl + shift + I`). If you're on windows, please make sure that [official git executable](https://git-scm.com/download/win) is installed.

**Comment by dummifiedme** [comment]
I am on windows, I had GitHub desktop client installed. Shouldn't it work?

**Comment by denolehov** [comment]
From what I remember, GitHub desktop doesn't provide `git` binary that this plugin relies on.

**Comment by dummifiedme** [comment]
Yes, thanks. I got it to work.
Now the only issue is to store credentials in cache

**Comment by denolehov** [comment]
I am glad you've got it working. Regarding credentials cache:
```bash
git config --global credential.helper store
```
I will update readme to clarify this.

**Comment by dummifiedme** [comment]
I didn't have to do anything. For the first 3-4 times it asked me to login,
but after that it began pushing files without any interruption, Even when I
changed the Vaults.
