### ISSUE TITLE
[Bug]: Unable to successfully connect to GIT

### ISSUE THREAD

**Issue by friendlemon** [denolehov/obsidian-git#161]
### Describe the bug

I was able to use the plug-in when I first started it, but it didn't work the next day. When you open the settings, you see that the branch is empty, no longer showing the master branch, Source Control has been refreshing, clicking on pull will prompt'Cannot run git command', but I can pull and submit with commands  through the MAC terminal.
<img width="1399" alt="WX20211228-145440@2x" src="https://user-images.githubusercontent.com/23216128/147538200-81547b8c-6012-413c-b0c1-30e97d2e0309.png">
 

### Steps to reproduce

Open the software

### Operating system

macOS

**Comment by Vinzent03** [comment]
How did you install Obsidian on your machine?

**Comment by friendlemon** [comment]
> 
I downloaded and installed Obsidian on the official website. Git was installed a long time ago. I forgot how it was installed at that time, but I'm sure Git is installed in the `/usr / local / git`  directory and there is a link in the path `/ usr / local / bin`.
<img width="1068" alt="WX20211230-095118@2x" src="https://user-images.githubusercontent.com/23216128/147715497-c3828044-21d3-4f6e-b620-80a02c356b41.png">

**Comment by friendlemon** [comment]
> How did you install Obsidian and git on your machine?

I downloaded and installed Obsidian on the official website. Git was installed a long time ago. I forgot how it was installed at that time, but I'm sure Git is installed in the `/usr / local / git` directory and there is a link in the path `/usr/local/bin`.

The following is the value of the environment variable path in my computer
<img width="1069" alt="WX20211230-095831@2x" src="https://user-images.githubusercontent.com/23216128/147715645-967a7784-80a0-40a7-b87b-2f5649f7f2ce.png">

**Comment by Vinzent03** [comment]
Hmm Idk what's the problem. Can you try setting the git binary path manual in the settings?

**Comment by friendlemon** [comment]
> Hmm Idk what's the problem. Can you try setting the git binary path manual in the settings?

At the beginning, I also thought about whether it was because I used gitee, so I later built a new repository in GitHub and used the path of GitHub, but it still didn't work. (because the Internet speed of GitHub in China will fluctuate, I use gitee)

**Comment by Vinzent03** [comment]
So you entered the gitee/GitHub url as git binary path at the bottom of the settings? That's wrong. It's about **git**, not **github**. Please clear the field and call the edit remotes command to set the GitHub/gitee link as remote url.

**Comment by friendlemon** [comment]
> So you entered the gitee/GitHub url as git binary path at the bottom of the settings? That's wrong. It's about **git**, not **github**. Please clear the field and call the edit remotes command to set the GitHub/gitee link as remote url.

I  clear the field in the way you said, and it works normally.

God, I actually made such a stupid mistake, so that setting is to help those who do not install git according to the default path to set the GIT directory?  Sorry, I completely understand wrong. I wonder if I should delete this stupid question.

**Comment by Vinzent03** [comment]
No problem. You don't have to delete this issue, so I can always refer to this issue if someone else has the same problem.
