### ISSUE TITLE
[Feature Request] Option to specify which folders / files to backup 

### ISSUE THREAD

**Issue by rvlewerissa** [denolehov/obsidian-git#162]
👋 Hi,

Thanks for the plugin!

It would be great if there would be an option to specify which folders / files to backup (and push). 

Personally, I have some folders / files which I do not want to include push to Git.

Thank you.

**Comment by Vinzent03** [comment]
You can't push individual files. You have to select which files to commit. There is already a native way in git: The `.gitignore` file. You can list files and directories to ignore. See an example [here](https://github.com/denolehov/obsidian-git/wiki/Tips-and-Tricks#gitignore) and another related issue [here](https://github.com/denolehov/obsidian-git/issues/144)

**Comment by rvlewerissa** [comment]
@Vinzent03 Ah ur right! 😅

Why didn't I think of that...
