### ISSUE TITLE
Stuck at "git: checking repo status", missing styles.css?

### ISSUE THREAD

**Issue by minhduccao** [denolehov/obsidian-git#17]
Just installed the plugin today and ran `git init` in my Obsidian vault folder and was able to push files to my repo without any issues using command line. However, I noticed that the plugin seems to be stuck on "git: checking repo status..". I do not have a .gitignore file in my repo and running Windows 10.

Here's the developer console output:
![image](https://user-images.githubusercontent.com/37083760/99732284-16ade480-2a74-11eb-9ae3-74cbf976bfa7.png)

**Comment by denolehov** [comment]
Hmm, `styles.css` isn't an issue. Provided that there are no other errors in the console, could you try pushing/pulling changes from within Obsidian manually? `ctrl + p` -> type "push" (or "pull") and execute a command and see if it helps? I suspect it's a visual glitch.

**Comment by minhduccao** [comment]
After doing the manual push in Obsidian, the plugin seems to be working properly now and is pushing my changes automatically. Thanks for the follow-up!
