### ISSUE TITLE
[Bug]: Cant push

### ISSUE THREAD

**Issue by dejwi** [denolehov/obsidian-git#171]
### Describe the bug

when i try to push changes i get this error in console | auto push doesnt work too
![image](https://user-images.githubusercontent.com/80927085/151228790-ea76687f-d749-4d9c-8645-0fd5e591354c.png)

commits and everything else works

Error: fatal: ambiguous
argument 'main': both revision and
filename
### Steps to reproduce

manual push

### Operating system

Linux

**Comment by gassparr** [comment]
yep, me too i get this 
![image](https://user-images.githubusercontent.com/92806151/151583552-52474c7a-224b-4292-94a5-90a1d27beed9.png)

**Comment by dejwi** [comment]
Issue: folder was named 'main', fixed with rename

**Comment by illarionov** [comment]
Also stumbled upon this bug.
I think it would be nice to fix it in the repository so that you don't have to use any workarounds.

Error message:
```
Uncaught (in promise) Error: fatal: ambiguous argument 'main': both revision and filename
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

    at Object.action (plugin:obsidian-git:23833:25)
    at PluginStore.exec (plugin:obsidian-git:23858:25)
    at eval (plugin:obsidian-git:21445:43)
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (plugin:obsidian-git:21443:16)
    at GitExecutorChain.eval (plugin:obsidian-git:21427:44)
    at Generator.next (<anonymous>)
    at fulfilled (plugin:obsidian-git:20276:24)
```
Root of the repository with Obsidian vaults:
```shell
$ git branch -a
* main
  remotes/origin/main

$ tree -aL 1
.
├── .git
├── main
└── README.md
```

**Comment by Vinzent03** [comment]
@illarionov Should be fixed now!

**Comment by illarionov** [comment]
It works, thank you!
