### ISSUE TITLE
[User error]: Plugin installed and working but panel not visible

### ISSUE THREAD

**Issue by JohnPaton** [denolehov/obsidian-git#174]
### Describe the bug

Hello! I have the plugin successfully installed, and the commands work via the command palette (git is also working via the command line). However, the panel is not showing in the sidebar, so I can't use the point-and-click controls or see an overview of the changes without switching to the command line.

I've tried uninstalling and reinstalling, but to no avail. There are no errors in the console. I'm afraid it's a config issue and I'm just an idiot, but I haven't been able to find anything.

![image](https://user-images.githubusercontent.com/18459252/151658792-223ebb1e-f747-4a2d-9cc1-cfac3cf75927.png)

### Steps to reproduce

1. Install obsidian-git on macOS
2. Enable the plugin
3. Restart Obsidian

### Expected Behavior

I expected the panel to be visible

### Operating system

macOS

**Comment by Vinzent03** [comment]
No problem. Did you follow the README? 
> It can be opened by the Open Source Control View command.

There's a command in the command palette to open it.

**Comment by JohnPaton** [comment]
Oof, I knew this was me being stupid haha. Thanks so much for the tip 🙈
