### ISSUE TITLE
Suggestion: Add macOS instructions for viewing the Obsidian console

### ISSUE THREAD

**Issue by JohnPaton** [denolehov/obsidian-git#175]
The settings page suggests to use `CTRL + SHIFT + I` [here](https://github.com/denolehov/obsidian-git/blob/dcc2c5021457c3c564748a8280c6a16b0fc6102a/src/settings.ts#L277) to open the Obsidian console. On macOS this key combination is actually `CMD (⌘) + OPTION (⌥) + I`.

**Comment by Vinzent03** [comment]
Should be fixed now. If not, let me know.

**Comment by JohnPaton** [comment]
Amazing, thanks!
