### ISSUE TITLE
Could not read Username / Device not configured

### ISSUE THREAD

**Issue by NAL100** [denolehov/obsidian-git#179]
### Describe the bug

I'm getting the error "fatal: Could not read Username for 'https://www.github.com': Device Not Configured"   - This is when I try to do a Push.  

I'm running on OS X Monterey 12.1 / Apple Silicon. I'm not sure if it's trying to authenticate through https or SSH - SSH is set up and I tested that it is working in the terminal. Ideas?

### Steps to reproduce

Command-P to bring up the menu -->  Obsidian Git: Push

### Operating system

macOS

**Comment by mutachre** [comment]
I have the same problem, you figured out how to solve?
