### ISSUE TITLE
[Bug]: Document defaults 

### ISSUE THREAD

**Issue by HaleTom** [denolehov/obsidian-git#181]
### Describe the bug

The Settings UI says:

> To disable automatic backup, specify negative value or zero (default)

What is the default?

### Steps to reproduce

Open Settings

### Expected Behavior

UI says something like (default == 5 mins)

### Operating system

Linux

**Comment by Vinzent03** [comment]
To be honest, I don't understand your problem. It says you have to specify a negative or zero value, which is the default, to disable automatic backup. I see no difference in meaning whether you refer the `default` to "negative value", "zero" or "disabled automatic backup". So the default is a disabled automatic backup.

**Comment by Vinzent03** [comment]
I thought about it again, and I think changing it to `Commit and push changes every X minutes. Set to 0 (default) to disable. (See below setting for further configuration!)` is better, right?

**Comment by HaleTom** [comment]
Ah, that's what it means!  Yup, if 0 is indeed the default, your proposed wording is excellent!  Thanks!

**Comment by Vinzent03** [comment]
Will be available in the next release. Don't know yet when that is.
