### ISSUE TITLE
[Bug]: {{hostname}} turns into gibberish

### ISSUE THREAD

**Issue by HaleTom** [denolehov/obsidian-git#182]
### Describe the bug

I have the following set:

Commit message: `Vault backup: x{{hostname}}x {{date}}`
Date: `{{hostname}} YYYY-MM-DD HH:mm:ss`

My commit message turns out to be:

```
Vault backup: xx {{1o15tnpm512}} 2022-02-08 13:51:15
```

### Relevant errors (if available)

```shell
There should be a hostname in between `xx`

{{hostname}} in date turns into `{{` bracketed gibberish.
```

### Steps to reproduce

Setup as above, click `Preview`

### Expected Behavior

```
Vault backup: xHOSTx HOST 2022-02-08 13:51:15
```

Where `HOST` is my hostname, as retrieved by `hostname` on Linux.

### Operating system

Linux

**Comment by HaleTom** [comment]
Related: #146

**Comment by Vinzent03** [comment]
Why do you use the `{{hostname}}` field in the {{data}} placeholder format field. Don't put `{{hostname}}` into that field. Only in "Commit message". This is a valid config: 

 
![grafik](https://user-images.githubusercontent.com/63981639/153029016-3155bc35-086e-4f84-a047-db934e6060e3.png)

**Comment by HaleTom** [comment]
Because the hostname between the two letter 'x' is blank as shown.

**Comment by HaleTom** [comment]
Ah, sorry... I just saw the 3rd field where you have DESKTOP.

Given this is a git plugin, it would be great to be able to share the 
configuration across hosts using git. Having the hostname derived by 
default from the machine's hostname would allow that to occur.
