### ISSUE TITLE
Suggestion: Git hook error handling

### ISSUE THREAD

**Issue by rlaker** [denolehov/obsidian-git#183]
I have a git pre-commit hook that checks for large files. The failure shows up as an uncaught error, so I have to open the inspect window to see the error. It would be nice if this plugin had a pop-up telling me if there was an exit code.

I don't know anything about Obsidian Plugins or Typescript, so don't worry if this is not possible.

**Comment by Vinzent03** [comment]
>  The failure shows up as an uncaught error,
What exactly do you mean? Is there a notification in the top right corner? If so, can you share a screenshot?

**Comment by rlaker** [comment]
I would like an error to appear in the top right, but it does not happen. Currently, the refresh wheel just keeps spinning, and when I open the console I see this:
![image](https://user-images.githubusercontent.com/20686171/153053454-beaadb91-5523-4112-9dba-6ce842d6980f.png)

**Comment by Vinzent03** [comment]
Does the new update fix the issue?

**Comment by rlaker** [comment]
It did show the right error once, which appears like this

![image](https://user-images.githubusercontent.com/20686171/156623486-b24f2f27-43ca-406c-b312-09e5657de936.png)

But then I ran another test and it just did the same as my previous comment.

**Comment by Vinzent03** [comment]
What command did you use and which version are you on? I added another missed error catch in v1.21.2

**Comment by rlaker** [comment]
I updated to v1.22.0 and it does work now. I see this message appear in a pop up.

![image](https://user-images.githubusercontent.com/20686171/156742680-0d7415f7-3dc2-468f-af49-f8f2a75c68d7.png)

Thanks so much. The only thing now is that there is still an uncaught error in the console, which means that the refresh button does not stop spinning. But I am happy that it shows me the error.

Thank you
