### ISSUE TITLE
Issues detecting and pushing changes

### ISSUE THREAD

**Issue by lillianhorin** [denolehov/obsidian-git#19]
Hello,

I'm writing because this plugin has been phenomenal but I recently discovered that about ~6 days ago my changes stopped being pushed. Which was strange, because the status bar had said it had been pushing the changes throughout these six days. I tried to manually push any changes, but it said that no changes were detected. To check if this was the case, I edited some pages and moved some and the plugin still was not able to detect changes.

Thanks for your help!

**Specs**
OS: Windows 10
Obsidian v0.9.16
Obsidian Git v1.4.0

**Screenshots**
Turning plugin off and on 
![image](https://user-images.githubusercontent.com/24489520/99883572-63212d80-2bf6-11eb-86f9-e5e286e1c265.png)
After changing files 
![image](https://user-images.githubusercontent.com/24489520/99883602-8b109100-2bf6-11eb-9eb7-1df24b525240.png)
Repo not updated in 6 days:
![image](https://user-images.githubusercontent.com/24489520/99883552-3705ac80-2bf6-11eb-998a-d95dfa2a6b34.png)

**Comment by lillianhorin** [comment]
Just an update: checked the developer console and it looks like there is no error with actually finding the `.git` file. Wanted to share in case it would be useful.

![image](https://user-images.githubusercontent.com/24489520/99911534-266f3800-2cc3-11eb-82ca-925c27600915.png)

**Comment by denolehov** [comment]
Very interesting. The plugin _does_ commit changes, but does not push them, correct? 

If you're comfortable with the terminal, could you please provide the output of `git status` command? As well as `git log`.
Could you also check if there are errors in the console when plugin _automatically_ tries to push changes?

**Comment by denolehov** [comment]
The error on screenshot does not seem to be related to the git plugin, but I'll dig and see if I am able to reproduce the issue.

**Comment by lillianhorin** [comment]
@denolehov Thanks for your quick help on this! I'm not even 100% sure it is committing the changes, just that it is _saying_ it is if that makes sense. As far as I'm aware the plugin isn't automatically trying to push the changes at all, since I haven't gotten any error messages. 

I'm not a super pro so I'm not sure if I'm doing it correct, but when I navigated to the repo, initialized git, and typed in `git status` and `git log`, this is what I am seeing.

![image](https://user-images.githubusercontent.com/24489520/99921377-ff7f2900-2cf7-11eb-9e71-8ed3f2276f3a.png)

**Comment by denolehov** [comment]
@lillianhorin it seems like your repository is empty (no commits, as if it is freshly created), are you sure you didn't remove the repository itself? Did you see your commits on github before plugin stopped pushing changes to remote?

**Comment by lillianhorin** [comment]
@denolehov Hmm that is so strange. Yes GitHub is actually where I noticed the commits stopped going through, because it is full of files and just says it last updated 8 days ago. And there are definitely files in the repository. Maybe I should go ahead and create a new repository and move the files there? I'll try that later tonight and see if it helps.

**Comment by denolehov** [comment]
I am sure there is a way to fix existing repo. But given that I've no idea what happened to the previous one, it makes more sense to just setup a new one from scratch. :)

**Comment by lillianhorin** [comment]
Happy report that everything is working now! Thank you so much for your advice in solving this issue, and again for the amazing plugin. :)
