### ISSUE TITLE
[Fea]: Widening the selectable area of the file in the Source Control view

### ISSUE THREAD

**Issue by jorgb** [denolehov/obsidian-git#190]
Hi,

This is a small quality of life request.

I love the Git Diff view you added. However, the steps I take are:

1. Click file
2. See the diff
3. Click plus (to stage)

However the clickable file is on the left and ends where the file ends, the plus icon is on the right, like;

![image](https://user-images.githubusercontent.com/3519707/155518936-b4890a47-bcda-4e66-af65-742ee3e7c571.png)

I have to first click the file 2022-02-24 on the left side, then travel all the way to the plus sign with the mouse, and repeat this process  for every change of file I want to review in the diff. If the area on the left is completely clickable for the file (up until the icons), the travel time to the plus icon is minimal.

Thanks!

**Comment by Vinzent03** [comment]
@phibr0 Sorry, but as always html related issues go to you :joy:
