### ISSUE TITLE
[Bug]: 0 minutes doesn't disable autobackup if "...X minutes after last change..." is enabled

### ISSUE THREAD

**Issue by 229c9cf0** [denolehov/obsidian-git#193]
### Describe the bug

Instead of disabling auto-backup like it does with the regular fixed-interval behavior, when the "...X minutes after last change.." option is enabled, vault backups are triggered immediately on any change (apparently rate-limited to 30s, but still bad).

### Steps to reproduce

1. Enable "If turned on, do auto backup every X minutes after last change. Prevents auto backup while editing a file. If turned off, do auto backup every X minutes. It's independent from last change."
2. Set "Vault backup interval (minutes)" to 0. Observe the "Automatic backup disabled!" popup.
3. Start typing in any file, then observe the flurry of auto-commit notification popups and/or inspect the `git log`.

### Expected Behavior

Setting the vault backup interval to zero should always disable auto-backups, independent of other options.

### Addition context

While you're in that area, "If turned on, do auto backup every X minutes after last change. Prevents auto backup while editing a file. If turned off, do auto backup every X minutes. It's independent from last change." should probably be renamed. 

Suggestion: You could call it "Interval is idle timer" and move the long text into the description unchanged.

### Operating system

Windows

**Comment by Vinzent03** [comment]
Sorry, but I'm unable to reproduce your issue. Working fine for me. Are you on the latest version?
