### ISSUE TITLE
Automatically refresh the Source Control view

### ISSUE THREAD

**Issue by NomarCub** [denolehov/obsidian-git#199]
This could definitely be done when the plugin's own related commands are executed.
There are also hooks in Obsidian, that could refresh the Source Control view, if it is open - like moving, renaming, opening, closing files and folders (even hooks for editing them, but I'm not sure). These specific ones wouldn't even necessitate looking for changes in the whole vault, just the affected files.
Another solution is handling it like DataView (also VSCode and others), and refreshing periodically, with the user potentially being able to adjust the refresh interval.

**Comment by Vinzent03** [comment]
It already watches for metadata changes. So it refreshes on file delete, edits, etc. But if debounces them for 5 minutes. So it refreshes after 5 minutes. That's definitely too high. Will add a setting to disable it, because of some Mac OS issues. #69

**Comment by NomarCub** [comment]
Changes can take over 8 seconds to show up. Could the timer be made configurable? How resource intensive is it with the Mac issue solved?

**Comment by Vinzent03** [comment]
It's currently debounced to 7 seconds. So you have to stop editing for 7 seconds. iirc somebody reported lags while typing. Will add a setting...

**Comment by Vinzent03** [comment]
It's now configurable in the latest release.
