### ISSUE TITLE
Failed to load resource - blocks plugin at 'git: checking repo status...'

### ISSUE THREAD

**Issue by jamestillercode** [denolehov/obsidian-git#20]
![image](https://user-images.githubusercontent.com/2343130/99892806-e9fdf680-2c46-11eb-8404-4f26990ea720.png)
![image](https://user-images.githubusercontent.com/2343130/99892822-0dc13c80-2c47-11eb-8434-b2861f7b276f.png)

Hi, I've wanted to use this for version control of my vault, just in case I need to roll back changes. I'm using git via command line at the moment, but I'd really love to automate it using this plugin. Unfortunately, it appears this css resource is not included in the .obsidian/plugins folder, and the link appears to be dead. 

This is a request to add that css file to the repo so that we can link it locally.

**Comment by denolehov** [comment]
Hey, this error does not impact the usability of the plugin. There are no `styles.css` to load, as there is nothing to style.

Is there any other errors that you see in the console? It might be a visual glitch, try manually pushing/pulling the changes from within obsidian itself (`ctrl + p` -> "push"/"pull") and see if it resolves the issue.

**Comment by Vinzent03** [comment]
@jamestillercode As @denolehov said. A style.css is not especially needed. Does the plugin work now? Or were there any other problems at all?

**Comment by Vinzent03** [comment]
Closing because of no response.
