### ISSUE TITLE
feature: show quick diff on hover

### ISSUE THREAD

**Issue by taro-ball** [denolehov/obsidian-git#200]
Is it possible to show a diff when hovering/clicking on a changed file in the side panel?
Doesn't have to be comprehensive though (especially for big changes) - first 10-15 lines is enough. May also add arrow buttons to go to previous/next change.  Can be useful to have some idea of what's changed when you've made changes to many files over a long period.
![image](https://user-images.githubusercontent.com/22948157/156961386-c5276cf2-11ca-4360-bd87-efd52ea71789.png)

**Comment by Vinzent03** [comment]
There's already a hover effect, when holding CTRL key, but it shows the file content and not the diff. I use Obsidian's internal features to show a preview of files, but I'm unsure how to implement that for my custom view. So I think it will stay with previewing the file content and not diff.

**Comment by Vinzent03** [comment]
I currently don't plan on implementing this, because I think it's enough to just click on the different files and see the diff in the diff view.
