### ISSUE TITLE
[Bug]: Obsidian only works with git from terminal

### ISSUE THREAD

**Issue by Geldra** [denolehov/obsidian-git#201]
### Describe the bug

Manjaro
Package installed via "yay"
Plugin functions fine if I start the application with
`$ obsidian`
from terminal.
However, opening the app via icons or start menu results in:
![image](https://user-images.githubusercontent.com/10325953/157393281-3fd3b782-74eb-4933-91ee-9f39bc1c11c2.png)

Did yay sneak the snap version of this package on me? (I ran yay -Q on the package, results below in error box). This is probably more of an Obsidian installation issue, but it only affects obsidian git.

### Relevant errors (if available)

```shell
yay -Q --info obsidian
Name            : obsidian-appimage
Version         : 0.13.23-1
Description     : Obsidian is a powerful knowledge base that works on top of a local folder of plain text Markdown files
Architecture    : x86_64
URL             : https://obsidian.md/
Licenses        : custom:Commercial
Groups          : None
Provides        : obsidian
Depends On      : zlib  hicolor-icon-theme  fuse
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : obsidian  obsidian  obsidian-insider
Replaces        : None
Installed Size  : 86.63 MiB
Packager        : Unknown Packager
Build Date      : Tue Feb 22 11:49:57 2022
Install Date    : Tue Feb 22 11:49:59 2022
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None
```

### Steps to reproduce

Using Manjaro KDE Plasma:
Install using `yay -S obsidian`
Set up github credentials and ssh key
Boot normally via icon / start menu

### Expected Behavior

Obsidian git should be able to talk to git and my permissions correctly and push

### Operating system

Linux

### Plugin version

1.21.0

**Comment by Vinzent03** [comment]
I think the environment variables are different when started from terminal. Does your ssh key have a passphrase and do you have to enter it when pushing in Obsidian started from the terminal?

**Comment by byq77** [comment]
I had a similar problem, but the error message was about an incorrect access rights of the `config` file inside the `.ssh` directory. Indeed, it was incorrect (620 instead of 600). After the change, the extension started to work as intended. Check this response: https://superuser.com/questions/215504/permissions-on-private-key-in-ssh-folder#answer-1559867.
