### ISSUE TITLE
Feature Request: Push only from specified machine(s)

### ISSUE THREAD

**Issue by finn-matti** [denolehov/obsidian-git#207]
It would be nice if Obsidian Git could be used as a automated back up solution. For this to work it would make sense to have the option to disable (automated) pushing to origin on a machine by machine basis. I think this could be done using the hostname variable. Using a simple table:

|Machine|Push?|
| --- | --- |
|primary|yes|
|secondary|no|

The user would be able to first activate customized pushing options and then second activate or deactivate the machines that ought to be pushing.

Thanks for your considderation!

**Comment by Vinzent03** [comment]
I don't plan on implementing this, but you can achieve it by using two different config folders. This separates mostly all Obsidian config, but this allows you to use different configs for the plugin on different devices.
