### ISSUE TITLE
automatic gpg signing doesn't seem to work

### ISSUE THREAD

**Issue by Sigafoos** [denolehov/obsidian-git#21]
I automatically sign all of my commits: my `~/.gitconfig` includes

```
[commit]
	gpgsign = true
```

When the plugin attempted to commit some changes, I got this error in the console:

```js
git-error.js:32 Uncaught (in promise) Error: error: cannot run gpg: No such file or directory
error: gpg failed to sign the data
fatal: failed to write commit object

    at GitExecutorChain.onFatalException (eval at <anonymous> (app.js:1), <anonymous>:2536:85)
    at GitExecutorChain.eval (eval at <anonymous> (app.js:1), <anonymous>:2527:28)
    at Generator.throw (<anonymous>)
    at rejected (eval at <anonymous> (app.js:1), <anonymous>:2482:65)
```

**Comment by denolehov** [comment]
hey @Sigafoos, are you on Linux? If so, could you try launching Obsidian from a command line using their AppImage and see if the problem persists?

Or if you're using flatpak:
```bash
/home/$USER/.local/share/flatpak/app/md.obsidian.Obsidian/current/active/files/obsidian
```

**Comment by Sigafoos** [comment]
Unfortunately I'm on a Mac (and Windows, though I haven't tried it there yet)

**Comment by danmichaelo** [comment]
GUI apps on Mac don't read your shell initialization files (.profile, .bashrc etc.), so they generally have a different PATH from what you get in your terminal.

So one solution would be to [modify the system-wide PATH variable](https://stackoverflow.com/a/26586170/489916), but I guess the reason Homebrew or other package managers don't recommend doing this by default, is the risk of conflicts. 

My preferred solution is therefore instead to tell `git` where it can find `gpg`. First, find out where `gpg` is located:

```
$ type gpg
gpg is /usr/local/bin/gpg
```

Then configure git to use that full path:

```
$ git config --global gpg.program /usr/local/bin/gpg
```

**Comment by Sigafoos** [comment]
This worked! Thank you so much.

**Comment by agucova** [comment]
I'm on Linux using the Flatpak version, with `gpgsign = true` and `gpg.program` set to `/usr/bin/gpg` (where it is on my case), and I can only get it to work while manually running the flatpak binary. If launched through the desktop shortcut, I get the following error (slightly different):
```javascript
git-error.js:31 Uncaught (in promise) Error: error: gpg failed to sign the data
fatal: failed to write commit object

    at GitExecutorChain.onFatalException (eval at evalFunc (app.js:1), <anonymous>:2302:85)
    at GitExecutorChain.eval (eval at evalFunc (app.js:1), <anonymous>:2293:28)
    at Generator.throw (<anonymous>)
    at rejected (eval at evalFunc (app.js:1), <anonymous>:2247:65)
```

**Comment by jonatan-ivanov** [comment]
Fyi, there is another workaround: if you start Obsidian from the terminal where the environment is initialized (`PATH`), the Obsidian process will see the environment variables, finds `gpg` and commit works: `open /Applications/Obsidian.app`.

**Comment by j-dogcoder** [comment]
> GUI apps on Mac don't read your shell initialization files (.profile, .bashrc etc.), so they generally have a different PATH from what you get in your terminal.
> 
> So one solution would be to [modify the system-wide PATH variable](https://stackoverflow.com/a/26586170/489916), but I guess the reason Homebrew or other package managers don't recommend doing this by default, is the risk of conflicts.
> 
> My preferred solution is therefore instead to tell `git` where it can find `gpg`. First, find out where `gpg` is located:
> 
> ```
> $ type gpg
> gpg is /usr/local/bin/gpg
> ```
> 
> Then configure git to use that full path:
> 
> ```
> $ git config --global gpg.program /usr/local/bin/gpg
> ```

This is working for me. Thank you!

**Comment by jasonm23** [comment]
Hi @dmthepm hopefully you figured this out.  Explaining how to install/set it up and integrate with Git, and obsidian seems to be well outside the scope of this issue.

The solution to this issue, is simply about how PATH environment var is (or isn't) passed to GUI apps like Obsidian, so we can configure git to know where to find the `gpg` executable.

for example:

```
git config --global gpg.program /usr/local/bin/gpg
```

If you don't have gpg installed, the process is involved and not trivial for non-dev/ops/programmer people, as you'll need to install it and setup your cryptographic keys etc.

For example on mac you could look at this guide.

https://gist.github.com/troyfontaine/18c9146295168ee9ca2b30c00bd1b41e

Google will help you for other platforms/os  "how do I setup GPG on X"
