### ISSUE TITLE
configuration {{hostname}} doesn't work

### ISSUE THREAD

**Issue by LiMuhua** [denolehov/obsidian-git#210]
configuration {{hostname}} doesn't work, it always be an empty character
![hostname doesn't work](https://user-images.githubusercontent.com/97930508/159876566-2f26e4ac-5976-4483-9d52-92c677e89776.png)
.

**Comment by LiMuhua** [comment]
No, I didn't, my them are so dark that I didn't notice the input box.
But if I don't set it, won't there be a default value?

**Comment by LiMuhua** [comment]
> It's working on my side. Did you specify the replacement of `{{hostname}}` in the setting below?

No, I didn't, my them are so dark that I didn't notice the input box.
But if I don't set it, won't there be a default value?

**Comment by Vinzent03** [comment]
No there isn't any default. See [here](https://github.com/denolehov/obsidian-git/issues/182#issuecomment-1032854477) for an explanation.

**Comment by LiMuhua** [comment]
> No there isn't any default. See [here](https://github.com/denolehov/obsidian-git/issues/182#issuecomment-1032854477) for an explanation.

I got it, thanks.
