### ISSUE TITLE
[Bug]: Occasional Error Messages even though new stuff gets pushed to the repo

### ISSUE THREAD

**Issue by ReaderGuy42** [denolehov/obsidian-git#212]
### Describe the bug

Every now and then I'll get the error message
```
Error: ssh: Could not resolve hostname github.com: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
What's interesting is that when I then check my Github repo, everything there is up to date, so I don't know what the error is about.

### Relevant errors (if available)

```shell
Uncaught (in promise) Error: ssh: Could not resolve hostname github.com: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

    at Object.action (eval at <anonymous> (app.js:1), <anonymous>:10544:25)
    at PluginStore.exec (eval at <anonymous> (app.js:1), <anonymous>:10569:25)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:8382:43)
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (eval at <anonymous> (app.js:1), <anonymous>:8380:16)
    at GitExecutorChain.eval (eval at <anonymous> (app.js:1), <anonymous>:8364:44)
    at Generator.next (<anonymous>)
    at fulfilled (eval at <anonymous> (app.js:1), <anonymous>:7216:24)
```

### Steps to reproduce

![image](https://user-images.githubusercontent.com/71895400/160389991-0586d748-cded-4b49-b0f7-2d2aacc1c82b.png)

### Operating system

Linux

### Plugin version

1.24.1

**Comment by Vinzent03** [comment]
`Could not resolve hostname github.com` sounds like a network issue.

**Comment by ReaderGuy42** [comment]
OK, so something with the internet connection (sorry if that's dumb)? That might be possible, but whenever I get an error like that, I check the repo and it's up to date, that's why I'm confused.

**Comment by Vinzent03** [comment]
If everything is correct online, I guess the pull failed, but the following push succeeds. I don't know why, but I think it's an issue on your side. Very strange.

**Comment by ReaderGuy42** [comment]
Could well be on my end, my connection is wonky sometimes. Thanks anyways!!
