### ISSUE TITLE
[Bug]: Author Identity Unknown

### ISSUE THREAD

**Issue by spcbfr** [denolehov/obsidian-git#213]
### Describe the bug

whenever I try to push or commit changes from obsidian the following error shows up
![image](https://user-images.githubusercontent.com/77839865/160885110-17430208-634c-47dd-85ed-66e5c93a13ca.png)

Thought I can still commit and push from the terminal as usual, I have the `user.name` and `user.email` already assigned

### Steps to reproduce

Open Obsidian
Open Source control view 
Press the commit button

### Operating system

Linux

### Plugin version

1.24.1

**Comment by Vinzent03** [comment]
The error is `unable to auto-detect email adress (got 'bla.(none)')` I think your config is wrong. Can you control your config via `git config -e` / `git config -e --gobal`?

**Comment by spcbfr** [comment]
I just reinstalled arch (not because of this bug) and the issue is now gone!
