### ISSUE TITLE
[Bug]:  Unable to specify Github account for push

### ISSUE THREAD

**Issue by aknight2015** [denolehov/obsidian-git#214]
I'm using the Debian version of Obsidian. I installed the plugin from Obsidian's built in plugin manager. I can't specify anywhere which GitHub account I want to push to.

**Comment by Vinzent03** [comment]
To clear some vocabulary. You don't push to a GitHub account, but to a remote git repository, which can be on GitHub. One GitHub account can have many git repositories. 
There's an edit remotes command. In addition, it should ask you for a remote, when you try to pull/push.

**Comment by assopri** [comment]
I also didnt get where I can set git account settings (using Windows) in plugin or in my git 3rd party app?

**Comment by aknight2015** [comment]
If there's no way to configure your plugin then it's useless.

**Comment by Vinzent03** [comment]
@aknight2015 
Authentication is different from system to system, which I haven't understood completely, and I don't know how to handle securely. Git is not just a sync method, but designed to be used by, e.g. developers. I'm aware that configuring authentication is an issue currently. But saying this plugin is useless is simply wrong.

**Comment by billpetro** [comment]
I'm getting this error: Base path does not exist

In the plugin Options > Advanced > Custom base path (Git repository path) I have put the Git repository name:

billpetro/obsidian-backup

(The full path would be https://github.com/billpetro/obsidian-backup)

What have I missed?

**Comment by NomarCub** [comment]
There's a "Username on your git server" option on mobile now. Could that be brought over to desktop? Would that solve your problem?

**Comment by aknight2015** [comment]
It doesn't. It doesn't prompt me for anything.

**Comment by Vinzent03** [comment]
@aknight2015 On mobile or desktop? It should only on mobile.
