### ISSUE TITLE
Obsidian git does not recreate modified / created timestamps which throws of organizing plugins

### ISSUE THREAD

**Issue by vvambo** [denolehov/obsidian-git#215]
I've started to work with dataview / calendar / daily / tasks   plugins and inside those with queries that use the timestamps for created and modified.
Pulling from git is changing these timestamps to the time of the pull / clone  / git-action instead of the original time.

This is a "problem"  inherent to git, but I imagine this affects many obsidian users.
There's scripts to cover this like [metastore](https://github.com/przemoc/metastore), [git-meta](https://github.com/01VCS/git-meta) or [git-store-meta](https://github.com/danny0838/git-store-meta) and with some fiddling and research I could probably insert them with pre-hooks into my obsidian repositories.

But the 2nd to last one is just a single .sh script and the last one comes with an installer for hooks, which I can imagine could be very easily integrated into the obsidian-git wrapper for push / pull and delivered with the  obsidian-git plugin to enable this for everybody (or as an option).

**Comment by Vinzent03** [comment]
Thanks for offering multiple ways to solve this, but I don't plan to integrate that into the plugin.
