### ISSUE TITLE
[Bug]: fatal: unsafe repository

### ISSUE THREAD

**Issue by calicorabbit** [denolehov/obsidian-git#218]
### Describe the bug

When starting the plug-in it throws an error. Following the instructions provided in the error message does not fix the issue.

### Relevant errors (if available)

```shell
VM118:14347 Error: fatal: unsafe repository ('C:/Users/Nemo/Documents/Active Projects/Notebook' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory 'C:/Users/UserName/Documents/ProjectLocation'

    at Object.action (eval at <anonymous> (app.js:1), <anonymous>:10544:25)
    at PluginStore.exec (eval at <anonymous> (app.js:1), <anonymous>:10569:25)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:8382:43)
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (eval at <anonymous> (app.js:1), <anonymous>:8380:16)
    at GitExecutorChain.eval (eval at <anonymous> (app.js:1), <anonymous>:8364:44)
    at Generator.next (<anonymous>)
    at fulfilled (eval at <anonymous> (app.js:1), <anonymous>:7216:24)
```

### Steps to reproduce

Update git to version 2.35.2.windows.1
open obsidian settings and go to obsidian git settings page
error message will be displayed

### Operating system

Windows

### Plugin version

1.25.0

**Comment by Vinzent03** [comment]
I think it's related to [this security vulnerability](https://github.blog/2022-04-12-git-security-vulnerability-announced/). Do you have different users on your machine? Running this config command should work though. Have you restarted Obsidian after changing the config?

**Comment by calicorabbit** [comment]
Hey, sorry for the delayed response my notification settings seem to not be doing what I think they would do on github. Regardless,

I tried doing the commend as listed in your edit link.  `$ git config --global --add safe.directory 'C:\Users\UserName\Documents\obsidianVaultLocation'` It appears to run successfully, it doesn't print out any sort of error message but when I go back to obsidian, even after a reset, it doesn't seem to have fixed anything.

Technically yes I have multi-account windows machine though I am the only user. I just use the other account for testing. However I did wonder if maybe I could try re-installing git not for a specific user? So I went through and did a re-install of git from git-scm.com and there is no option for single vs multi-user install and the issue persists.

as an fyi since I updated git in this process the same behavior is also happening for `2.36.0.windows.1`

**Comment by Vinzent03** [comment]
@calicorabbit Did you run exact this command? `git config --global --add safe.directory 'C:\Users\UserName\Documents\obsidianVaultLocation'`, because you should replace the `'` with `"`. So it should be `git config --global --add safe.directory "C:\Users\UserName\Documents\obsidianVaultLocation"`.
Otherwise, I don't know how to help you. Sorry.

**Comment by calicorabbit** [comment]
yeah, I did. It didn't work. But then I tried it using a different CLI than powershell and it did work... Yeah I am not sure. I think that works but I did _something_ wrong the first time. Not sure what.
