### ISSUE TITLE
[Bug]: TypeError Cannot read properties of undefined (reading 'checkIsRepo')

### ISSUE THREAD

**Issue by vworp** [denolehov/obsidian-git#219]
### Describe the bug

Install the plugin, can commit test and pull. After restarting obsidian, all actions fail with:
TypeError Cannot read properties of undefined (reading 'checkIsRepo')

Have to uninstall and reinstall, but it still fails after every restart of obsidian

### Steps to reproduce

Restart Obsidian

### Operating system

Windows

### Plugin version

1.25.0

**Comment by Vinzent03** [comment]
Can you share the content of the console? (`CTRL + SHIFT + I`)

**Comment by vworp** [comment]
Hmm, I can't get it to repeat now. I went thru a few iterations if deleting and recloning the same repository, trying to get .gitignore to behave. I might have accidentally fixed it along the way.

**Comment by ooliver1** [comment]
i still get this issue

**Comment by ooliver1** [comment]
i had this too, deleting files then git resetting to origin and a reboot of obsidian worked
