### ISSUE TITLE
Pushing not working

### ISSUE THREAD

**Issue by NicholasMamo** [denolehov/obsidian-git#22]
I've installed this plugin, but I'm unable to push or pull commits. Whenever I push, the plugin creates a commit, but fails on pushing with this error (from the console). I have access rights to the repository, and I can push from the command line, so I'm not sure what the problem is. I'm on Ubuntu 20.04, and `ssh-askpass` is installed. I connect to my repository using SSH, not username/password.

The error and stack in question:

```
Uncaught (in promise) Error: Pushing to github.com:NicholasMamo/xyz.git
ssh_askpass: exec(/usr/libexec/ssh-askpass): No such file or directory
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

    at GitExecutorChain.onFatalException (eval at <anonymous> (app.js:1), <anonymous>:2536:85)
    at GitExecutorChain.eval (eval at <anonymous> (app.js:1), <anonymous>:2527:28)
    at Generator.throw (<anonymous>)
    at rejected (eval at <anonymous> (app.js:1), <anonymous>:2482:65)
```

**Comment by denolehov** [comment]
Hmm, could you try starting Obsidian from command line (using Obsidian AppImage) and see if the problem persists?
If you're using flatpak:
```bash
/home/$USER/.local/share/flatpak/app/md.obsidian.Obsidian/current/active/files/obsidian 
```

**Comment by NicholasMamo** [comment]
Thanks for the quick reply. It worked when launching the app from the command-line, but it doesn't work when I launch it from dash. Any idea why that is?

**Comment by denolehov** [comment]
I am not entirely sure, but most likely it is related to the fact that Obsidian instance that you're launching from dash is sandboxed, and it doesn't "see" your `$PATH`. I didn't pinpoint the issue yet, but it seems like an emerging pattern given other, similar issues some people have.

**Comment by NicholasMamo** [comment]
Got it. Let me know if I can help in any way! :)

**Comment by denolehov** [comment]
As a workaround, you could try adding AppImage to dash [manually](https://askubuntu.com/questions/90345/desktop-launcher-documentation).

**Comment by jalberto** [comment]
same issue uwing flatpack

**Comment by NicholasMamo** [comment]
An update from 2 days ago seems to have fixed this issue for me

**Comment by pew** [comment]
Automatic push doesn't seem to work for me either (I set it to 5 minutes intervals), I'm on macOS with Obsidian v0.10.1, any way I can debug this to fix it?

**Comment by Vinzent03** [comment]
@NicholasMamo Can I close this now?

**Comment by NicholasMamo** [comment]
> @NicholasMamo Can I close this now?

Not yet, I'm afraid. It hasn't worked for at least a month now. When I push, I get the error: "git: push failed to github.com:username/vault.git bad owner or permissions on vault.git".

**Comment by Vinzent03** [comment]
When you push changes from the command prompt. Do you have to type in some password or similar?

**Comment by NicholasMamo** [comment]
No, I use SSH to push changes. Pushing from the command prompt works flawlessly.

**Comment by ebouchut** [comment]
FYI, take a look at this.
https://github.com/denolehov/obsidian-git/issues/39#issuecomment-798955390

**Comment by JeremyKennedy** [comment]
This is what worked for me: https://github.com/denolehov/obsidian-git/issues/39#issuecomment-812216390

**Comment by Vinzent03** [comment]
I'm now trying to summarize auth methods [here](https://github.com/denolehov/obsidian-git/wiki/Authentication)
