### ISSUE TITLE
[Feature Request]: Add branch support

### ISSUE THREAD

**Issue by metruzanca** [denolehov/obsidian-git#220]
Really been enjoying this plugin recently. Its grown so much too from the auto-push/pull. Currently, this is a must have for myself and a few other friends of mine. Obsidian has become our wiki viewer and editor especially since azure wikis are a bit odd, especially with their folder note syntax (which is perfectly abstracted away with [alx-folder-note](https://github.com/aidenlx/alx-folder-note)).

However there's still one more use case in which I reach for a terminal and that is for dealing with branches.

Personally, all I think that's necessary is: 
- Status line with branch name akin to vscode
- List local branches, and (attempt) checkout on click
    - Maybe, load remote branches too but via some other button/menu item
- Create new branch

**Comment by Vinzent03** [comment]
There is no branch management currently, because that's a rare use case for personal knowledge management.

**Comment by leventov** [comment]
I second this feature request. I want to setup Obsidian as team's engineering/architecture knowledge base. I want to create a new "feature" branch and make some coherent changes in it and then push this branch as a merge request against a GitLab repository.

Maybe GitLab support is too far fetched at the moment, but it would be useful to create and checkout a new branch with a hotkey and also to push it upstream.

**Comment by NomarCub** [comment]
I found this request also related to branches, creating and deleting them: https://github.com/denolehov/obsidian-git/issues/132

**Comment by nprime496** [comment]
I'd like to have branches support just because I use obsidian on multiple devices and commit histories diverge very often. It would be easier for me to let each device push on its branch and merge it at the end of the week.

**Comment by Vinzent03** [comment]
There are some branch features. Please create a new issue with the exact features you are missing.
