### ISSUE TITLE
[wiki]: .obsidian/workspaces.json is now .obsidian/workspace

### ISSUE THREAD

**Issue by Amar-Gill** [denolehov/obsidian-git#222]
Want to share that the latest version of Obsidian `0.14.6` has changed the `.obsidian/workspaces.json` file to `.obsidian/workspace`.

The [tips and tricks](https://github.com/denolehov/obsidian-git/wiki/Tips-and-Tricks) page still references the old file name.

Logging this issue to request an update to the wiki.

Really enjoying the plugin so far, awesome work =]

**Comment by Vinzent03** [comment]
Thanks for the issue. I think this change is already half a year old or so.
