### ISSUE TITLE
[FR] support Android/chromeOS

### ISSUE THREAD

**Issue by leonhma** [denolehov/obsidian-git#225]
With the popularity of chromebooks nowadays, i think it would be really useful to have this working on chromeOS (basically Android). This would as far as i can see require a javascript-only implementation of git (git add/commit, push, pull and branch), which might be a bit tricky to implement.

**Comment by Vinzent03** [comment]
Which version of Obsidian do you install on chrome OS? The Android version?

**Comment by leonhma** [comment]
Yeah. I think android is more integrated with chrome os and sometimes I have the issue where frosting (the Linux environment) has its GUI entirely brick.
Do you think isomorphic got can be integrated with electron/capacitors or is that not feasible anyways?

**Comment by s-aluma-r** [comment]
you can install MGit from Fdroid (playstore version has problems getting the all file permission necessary) and use that on android

**Comment by NomarCub** [comment]
There's been an update that makes the plugin available for mobile, using isogit. Does that solve your problem?

**Comment by leonhma** [comment]
That's actually kind of the solution I was eying for! Solves my problem, although i have gone to Dropbox for syncing my notes in the meantime. I'll try it out soon.
