### ISSUE TITLE
[Bug]: The plugin stops working when the status of a staged file is "renamed"

### ISSUE THREAD

**Issue by Konfido** [denolehov/obsidian-git#226]
### Describe the bug

The plug works fine when the status of staged files are "U", "D", "M".
But once your rename a file and try to stage the two [D]eleted and [U]ntracked file, the plug just stops functioning and leaves the refresh icon spinning. It seem it is not responding to a status of [R]enamed.

### Steps to reproduce

Just rename a file, and stage the two deleted and untracked file.

I have reproduced this bug in the HELP vault, so it is most likely caused by the plug itself.

### Operating system

macOS

### Plugin version

v1.25.1

**Comment by Vinzent03** [comment]
Thanks for raising the issue. Should be fixed now.
