### ISSUE TITLE
[Bug]: Appearance issue

### ISSUE THREAD

**Issue by slabzzz** [denolehov/obsidian-git#229]
### Describe the bug

![image](https://user-images.githubusercontent.com/100169858/167274625-b02c5750-cffb-432f-8cd2-9e5b89d957a9.png)

### Steps to reproduce

Plugins: Automatic Dark mode, obsidian git, excalidraw

### Operating system

Windows

### Plugin version

1.25.1

**Comment by Vinzent03** [comment]
This is a standard Git issue. You have changes in `.obsidian/appearance.json` and are trying to pull. Because the changes are not committed, it can't try merging them. So you have to either discard the changes or commit them and pull afterwards.
