### ISSUE TITLE
[Bug]: origin/main errors on initial push

### ISSUE THREAD

**Issue by junefish** [denolehov/obsidian-git#233]
### Describe the bug

I configured the git repo following [these instructions](https://forum.obsidian.md/t/using-gitdesktop-github-obsidiangit-to-backup-vaults/14219).  When I tell Obsidian Git to "commit all changes" it succeeds, but when I tell it to "push" I get the following errors:

<pre>Uncaught (in promise) Error: origin/main
fatal: ambiguous argument 'origin/main': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

    at Object.action (eval at <anonymous> (app.js:1:1), <anonymous>:10620:25)
    at PluginStore.exec (eval at <anonymous> (app.js:1:1), <anonymous>:10645:25)
    at eval (eval at <anonymous> (app.js:1:1), <anonymous>:8440:43)
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (eval at <anonymous> (app.js:1:1), <anonymous>:8438:16)
    at GitExecutorChain.eval (eval at <anonymous> (app.js:1:1), <anonymous>:8422:44)
    at Generator.next (<anonymous>)
    at fulfilled (eval at <anonymous> (app.js:1:1), <anonymous>:7274:24)</pre>

### Steps to reproduce

- github.com/new
   - initialise repo with no README or templates
- open Github Desktop and clone repo
- open repo in File Explorer (e.g. ~/Github/obsidian)
- view hidden files and folders
- copy .git folder to folder of obsidian vault (e.g. ~/Documents/obsidian)
- in Obsidian:
   - ctrl-p > "commit all changes"
   - \> "push"

### Expected Behavior

Plugin pushes changes to Github and they become viewable on github.com/junefish/$repo.

### Operating system

Linux (Pop OS)

### Plugin version

1.25.2

**Comment by junefish** [comment]
I tried creating a .gitignore (adding an API token file from another plugin) in case origin/main wasn't "initialised" properly, and now I'm just getting the same error when I try to "pull" with Obsidian Git.

**Comment by Vinzent03** [comment]
Hmm it can't find your `origin/main` branch. Can you run `git branch -a` in the terminal in your git repository root and share the output?

**Comment by junefish** [comment]
I should have tried doing it in the terminal (as opposed to in Obsidian > looking at logs) first!  The error output was much more self-explanatory and I was able to fix it.
