### ISSUE TITLE
[Enhancement]: Add a way to auto-push / push on Obsidian close

### ISSUE THREAD

**Issue by hiAndrewQuinn** [denolehov/obsidian-git#240]
Hello! I have this plugin working now and the auto-commit is lovely. I'd like a way to automate actually pushing changes as well, since I'm using this by myself. Is this possible? I could write it myself if you have any tips to help me start.

**Comment by Vinzent03** [comment]
Do you have the setting `Disable push` enabled? The description may need some update, but by disabling the option (enabling push) it should push on auto backup.

**Comment by McNickSisto** [comment]
Hi @Vinzent03,

For some reason, the Auto Backup after File Change does not seem to work automatically. I have both options enabled (Push after backup + Auto backup after File Change), and whenever I make a change on one file, it does not commit + push automatically. I can't seem to figure this out. 

Thanks in advance.
Nicholas

**Comment by Vinzent03** [comment]
@McNickSisto this has nothing to do with this issue. After file change, it still uses the set time duration before committing. So check the value is low enough and you wait for it. Please open a new issue for further questions.

**Comment by McNickSisto** [comment]
@Vinzent03 Thanks ! Apologies for the confusion.
