### ISSUE TITLE
[Bug]: Resolve merge conflict within obsidian?

### ISSUE THREAD

**Issue by slabzzz** [denolehov/obsidian-git#246]
### Describe the bug

I need to use the github desktop plugin currently. But it would be nice to be able to resolve this automatically.
![image](https://user-images.githubusercontent.com/100169858/172944375-00e6dd60-8e86-476e-8691-99e545ead4ad.png)

### Steps to reproduce

Using multiple devices automatically gives this error if you change the size of text

### Operating system

Windows

### Plugin version

1.25.3

**Comment by Vinzent03** [comment]
Can you update to the latest version? I fixed some merge conflict scenarios.

**Comment by slabzzz** [comment]
Is this expected output?

<img width="317" alt="image" src="https://user-images.githubusercontent.com/100169858/173157925-ef54b6cc-32e6-42cf-aa43-b6d6d3b30877.png">

**Comment by Vinzent03** [comment]
Oh now that I read your error message more carefully, you don't have a merge conflict. You mist either discard your changes to the appearance file or commit the changes or ignore the file via .gitignore.

**Comment by slabzzz** [comment]
I think update fixed it; screenshot was after the update. I am able to successfully pull push and commit even when I get that message. There is no more of that longer message that comes directly after.
