### ISSUE TITLE
Two period suffix looks out of place

### ISSUE THREAD

**Issue by skalnik** [denolehov/obsidian-git#25]
This plugin is great! Thank you so much for the work on it. After I installed it, I thought the `..` suffix for most statuses was some bug with joining things into the status bar, but after looking at the source code, I see it is intentional: https://github.com/denolehov/obsidian-git/blob/master/main.ts#L477-L500

I was curious why you chose to add that. It felt a bit out of place on my status bar.

<img width="411" alt="Screen Shot 2020-12-09 at 10 38 04 🌃" src="https://user-images.githubusercontent.com/2546/101730739-6d08b480-3a6f-11eb-98de-bfb5a9c49122.png">

I figured I'd ask before sending you a PR 😀

**Comment by denolehov** [comment]
Hey @skalnik, it's just a personal preference :D

**Comment by skalnik** [comment]
Fair enough! Thanks for the info. I'll leave it as be since it's on purpose 😀
