### ISSUE TITLE
[Bug]: Plugin unable to find git-crypt on Apple Silicon

### ISSUE THREAD

**Issue by protoz** [denolehov/obsidian-git#250]
### Describe the bug

I recently started using an M1 Mac which has a different path for homebrew of `/opt/homebrew/bin` which is accessible in my terminal (Both bash and zsh).  I can, from terminal, interact with the encrypted vault repo without issue so I'm thinking there may be an issue at the Obsidian plugin level.

### Relevant errors (if available)

```shell
"git-crypt" clean: git-crypt: command not found
error: external filter "git-crypt" clean: failed 127
error: external filter "git-crypt" clean: failed
fatal: .obsidian/community-plugins.json: clean filter 'git-crypt' failed
```

### Steps to reproduce

Create vault
Encrypt with git-crypt following this guide : [https://renerocks.ai/blog/obsidian-encrypted-github-android/](https://renerocks.ai/blog/obsidian-encrypted-github-android/)

Install obsidian git plugin
When pulling/pushing the error appears and the plugin isn't detecting the current branch.

### Expected Behavior

Like on Windows and Intel Mac, it just works as intended in the tutorial.

### Addition context

This failed on 1.25.6 as well so it may just be something unreported yet.

### Operating system

macOS

### Plugin version

1.26.1

**Comment by protoz** [comment]
This behavior matches `https://github.com/denolehov/obsidian-git/issues/201`  opening Obsidian in a terminal window works just fine.

**Comment by rxng** [comment]
@protoz I am having the same issue, can you say what you changed it to? 

I have the following in .git/config , but changing git-crypt to /usr/bin/git-crypt did not help:
```
[filter "git-crypt"]
        smudge = \"git-crypt\" smudge
        clean = \"git-crypt\" clean
        required = true
[diff "git-crypt"]
        textconv = \"git-crypt\" diff
```

**Comment by zufanka** [comment]
+1

```
git obsidian error: "/usr/bin/git-crypt" clean: line 1: /usr/bin/git-crypt: No such file or directory
error: external filter '"/usr/bin/git-crypt" clean' failed 127
error: external filter '"/usr/bin/git-crypt" clean' failed
fatal: FTM/lobbyregister to argo.md: clean filter 'git-crypt' failed
```

**Comment by protoz** [comment]
I installed git-crypt using homebrew so mine looks like:

```
[filter "git-crypt"]
	smudge = /opt/homebrew/bin/git-crypt smudge
	clean = /opt/homebrew/bin/git-crypt clean
	required = true
[diff "git-crypt"]
	textconv = /opt/homebrew/bin/git-crypt diff
```
