### ISSUE TITLE
[Bug]: Source control view icon is overridden when pinned

### ISSUE THREAD

**Issue by NomarCub** [denolehov/obsidian-git#252]
### Describe the bug

With the new [insider release](https://forum.obsidian.md/t/obsidian-release-v0-15-3-insider-build/39566), the panes made by the plugin have their icon overridden when pinned. Also, If I have the source control view in the sidebar and don't pin it, I get stuck in the diff view if I click on a file change, so pinning becomes necessary.

### Steps to reproduce

Open source control view, pin the pane in the sidebar.

### Operating system

Windows

### Plugin version

1.26.1

**Comment by peterkaminski** [comment]
I'm running Obsidian v0.15.6 and Obsidian Git v1.26.1 on MacOS, and I couldn't figure out how to get out of diff view.

Pinning the pane forces diff view to open in another pane, while the Source Control View stays open, and then it's easy to close the diff pane when I'm done with it. So pinning is necessary to be able to get back to Source Control View.

And as OP notes, the Source Control View icon at the top is overridden by the pin icon.

**Comment by Vinzent03** [comment]
I think overriding the icon is an Obsidian issue, because the same happens to Obsidian's own sidebar panes like "Backlinks".

You are correct that since Obsidian v0.15 the diff view gets opened in the sidebar. Will fix this.
