### ISSUE TITLE
[Bug]: `Create backup` command says `No changes to commit` when all changes are staged

### ISSUE THREAD

**Issue by NomarCub** [denolehov/obsidian-git#253]
### Describe the bug

Title says it all. If there are any non-staged changes, then all changes are backed up normally.

### Steps to reproduce

- init a repo
- make changes and stage them all
- execute the `Create backup` command

### Expected Behavior

A backup is made when there are any changes, even if all are staged.

### Operating system

Windows

### Plugin version

1.26.1

**Comment by NomarCub** [comment]
The fix didn't work. The fix commit looks wrong too, but easy to fix https://github.com/denolehov/obsidian-git/commit/f71fdf58271c1490887f057c6ecc5e6d3689dbd4

**Comment by Vinzent03** [comment]
Oh what a stupid mistake, haha. Should be really fixed now.
