### ISSUE TITLE
Enhancement request: Icon order in source control view

### ISSUE THREAD

**Issue by peterkaminski** [denolehov/obsidian-git#259]
The source control view is **awesome**, thank you.

I have a UI/UX suggestion, feel free to ignore if you don't think it's a good idea.

I suggest that the order of the icons at the top be roughly in workflow order (in other words, in the order you'd typically do them as you work with Git):

![reordered-icons-20220710-pk](https://user-images.githubusercontent.com/169442/178162500-95e18db9-85af-4808-a19d-a7304a7b2cef.png)

Pull - Stage all - Unstage all - Commit - Push - Change Layout

(Change Layout at the end because it's not part of your Git workflow.  It could perhaps be moved to the right a little, and/or separated from the others by a small vertical bar.)

Background: I have found in teaching people how to use Git with [Atom](https://atom.io)'s sidebar, their top-to-bottom ordering of workflow helps people remember the order of Git operations more easily than if they were ordered another way.

Edit: see comment thread about workflow order vs. functional grouping, and a suggestion about potentially making icon order configurable.

**Comment by Zachatoo** [comment]
My 2¢, I prefer having push/pull next to each other, signifying the similarities of the actions (pushing and pulling from an origin). Same with stage/unstage.

I do see the benefit of new users to git not having to remember the order, which many users of this plugin will be unfamiliar.

**Comment by Vinzent03** [comment]
For reference, I asked on the Discord for some more opinions.
I agree with @Zachatoo that I like the grouping of similar actions more than the order of execution.
I will leave this issue open though.

**Comment by peterkaminski** [comment]
@Vinzent03 @Zachatoo, thanks for your comments.

I still prefer workflow order, but I also see the benefit of functional grouping.  I'm fine with either choice. Thanks for leaving the issue open, Vinzent.

A way to have both would be to make the order configurable.  This would increase documentation and setup complexity somewhat, with a potential benefit of somewhat increased usability and trainability for some people.  I'm not sure if it's a good idea or not, but _I'd_ find it useful. :-)

**Comment by Vinzent03** [comment]
I decided to close this issue now, as I plan to continue with the current button order and adding an extra button is not worth it.
