### ISSUE TITLE
Feature: Add specified message

### ISSUE THREAD

**Issue by jorgb** [denolehov/obsidian-git#26]
I like the shortcut to commit my current state in one go to GIT. However, I would like to specify a short message when I invoke the command myself. Workflow for me is;

Hotkey -> Commit prompt (may be pre-filled with default message) -> Commit & Push all

Ideally I see the files and check / uncheck the ones excluded, but I understand the philosophy of the backup plugin, and I can use a separate source control tool e.g. Sourcetree to do a fine grained commit. But in small bursts (e.g. an adjustment to one jounal entry) I would like to specify a more fine grained message.

Thank you for this plugin!

**Comment by psyguy** [comment]
I'd like to +1 this, especially if invoked by a hotkey.

Currently, I rely on another Git client (GitKraken or Git bash) to manually set commit message.

**Comment by Vinzent03** [comment]
Is now available in the new [release](https://github.com/denolehov/obsidian-git/releases/tag/1.6.0)
