### ISSUE TITLE
Enhancement request: Source Control View lists recently pulled files

### ISSUE THREAD

**Issue by peterkaminski** [denolehov/obsidian-git#260]
## Current Behavior

After doing a pull, Obsidian Git currently displays a pop-up message like this:

> Pulled new changes. 10 files updated

It would be nice to know _which_ files were updated.

## Idea: pulled files listed in Source Control View

Idea: Use the bottom half of the Source Control View pane to display the names of the files that were updated in the most recent pull.

Mockup:

![Source Control View lists recently pulled files mockup 2022-07-12](https://user-images.githubusercontent.com/169442/178581714-ff4b757f-2353-4eb5-8f3b-f60e23013ed5.jpg)

## Technical considerations: `git pull`

Part of the `git pull` output looks like this, and may be able to be parsed to get needed information:

```
Obsidian Tips and                                          | 165 +++++++++++++++++--------------------------
Decentralizing, Centralizing, and Decentralizing Again     |  46 ------------
Office Hours                                               | 198 ----------------------------------------------------
Connections (British Documentary)                          |  17 +++++
 ```
 
 Internally, `git pull` is a fetch and merge, offhand I don't know which one would generate the information above, or if there is a porcelain version of it.

**Comment by Vinzent03** [comment]
I definitely like the idea, but I don't when I get the time for it.
