### ISSUE TITLE
[Bug]: False handling of Custom base path

### ISSUE THREAD

**Issue by cjunekim** [denolehov/obsidian-git#263]
### Describe the bug

Please have a look at https://github.com/kometenstaub/obsidian-version-history-diff/issues/9#issuecomment-1169454462

Using substring len+1, it omits the first character of the path.

> I think it's all coming from using a simple and cheap trick of substring +1 instead of proper path handling. Even something like split by the delimiter(slash or backslash) would've been better.

### Steps to reproduce

Use custom base path or not, you can see

>fatal: ambiguous argument 'xxxxxx': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:

Be careful to see that the file name xxxxx's first character is omitted.

### Operating system

Windows

### Plugin version

1.26.3

**Comment by Vinzent03** [comment]
Should be fixed now.
