### ISSUE TITLE
[Bug]: could not read Username for 'https://github.com': No such device or address

### ISSUE THREAD

**Issue by Elkellympia** [denolehov/obsidian-git#267]
### Describe the bug

The error just occurs when obsidian tries to read from github, the commits are fine from what i know

### Relevant errors (if available)

```shell
plugin:obsidian-git:10760 Uncaught (in promise) Error: fatal: could not read Username for 'https://github.com': No such device or address

    at Object.action (plugin:obsidian-git:10760:25)
    at PluginStore.exec (plugin:obsidian-git:10785:25)
    at eval (plugin:obsidian-git:8505:43)
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (plugin:obsidian-git:8503:16)
    at GitExecutorChain.eval (plugin:obsidian-git:8487:44)
    at Generator.next (<anonymous>)
    at fulfilled (plugin:obsidian-git:7339:24)
action @ plugin:obsidian-git:10760
exec @ plugin:obsidian-git:10785
eval @ plugin:obsidian-git:8505
handleTaskData @ plugin:obsidian-git:8503
eval @ plugin:obsidian-git:8487
fulfilled @ plugin:obsidian-git:7339
plugin:obsidian-git:15062 git obsidian message: Committed 0 file
```

### Steps to reproduce

install obsidian via .deb
clone the repository
open the folder on obsidian
enable the plugin and set up active sync
1 and 2 minutes respectively
watch the error as you cry of frustation

### Expected Behavior

An error on the top left corner saying "could not read Username for 'https://github.com': No such device or address"

### Addition context

I have seen that the deb inst commonly used, but its an official version as shown in this screenshot 
![image](https://user-images.githubusercontent.com/87786716/180885019-3e35261c-ffd7-42c4-8efb-bf86f672ddca.png)
So that could be strangely it

### Operating system

Linux

### Plugin version

1.28.0

**Comment by Elkellympia** [comment]
Also, can this extension work with shared repositories like with other accounts instead of only 1? or it could broke that way

**Comment by Vinzent03** [comment]
Authentication is kind of a problem, especially on Linux, because git doesn't have credential caching by default.

When pushing via terminal you have to enter your credentials, which is not possible in Obsidian, so it fails.

An alternative is to use `ssh`. You either use an ssh key with passphrase and add it to the ssh-agent or use a ssh key without passphrase.

What exactly do you mean with multiple accounts? Using multiple accounts on the same machine or your friend who is using the same repo? Both cases shouldn't be a problem.

**Comment by Elkellympia** [comment]
Alright, i will change to ssh, yeah, i was using a Personal access tokens because on top of linux dont having credential caching, for some reason i couldnt use the password, it tells me that for security reasons now i cant use passwords.
brb

**Comment by Elkellympia** [comment]
It worked! thank you!
I have seen that there are many common/easily fixable problems that aren't on the wiki and i would like to help adding them to it so there's less "filling" on the issues section and everything is streamlined
