### ISSUE TITLE
Plugin initialization procedure

### ISSUE THREAD

**Issue by lishid** [denolehov/obsidian-git#27]
Inside the `onload` function, I recommend doing all the synchronous actions first, such as registering your command and setting page. This way, a user who enables your plugin sees the setting tab right away, and also any errors during initialization won't prevent the setting page from showing up.

https://github.com/denolehov/obsidian-git/blob/745fc53a9fe6925bd2d5f8153dcd385839f078f0/main.ts#L52
I would highly recommend avoid doing intensive/long running work in the `onload` function, but rather, defer this to later.
This is because if your await takes a long time, it will prevent the app from loading. The user will spend a significant amount of time seeing the loading bar, until your plugin finishes the loading process.
Start a new `async` function, but don't `await` on it (so it can run independently of your onload).

https://github.com/denolehov/obsidian-git/blob/745fc53a9fe6925bd2d5f8153dcd385839f078f0/main.ts#L49
Don't use a class for your setting. `loadData` will return a generic object, so you should use an interface instead.

**Comment by orchifai** [comment]
Thank you for providing such a good idea.
May I know what if I want to use your version, how am I suppose to do?
I tried copying your ts file and edit the existing manifest.json from "js:main.js" to "js:main.ts", but it fails to initialize.

**Comment by lishid** [comment]
You'll want to build the .ts file to a .js version using the build pipeline - just run `npm install` to install dependencies then `npm run build` to actually build the final file.

**Comment by denolehov** [comment]
thank you for the suggestions!

**Comment by Vinzent03** [comment]
@lishid You are right, that some users complain about missing settings page or commands, but why should the commands be registered, when the plugin fails in initialization? Other tasks though should of course be moved to other functions.

**Comment by lishid** [comment]
The command could gracefully fail with a message, keeping the plugin experience consistent. Right now the biggest friction is that if something goes wrong, the user has no idea what's going on, or how to solve it, without joining the discord and ask for tips.

**Comment by Vinzent03** [comment]
Okay, I will add that.

**Comment by lishid** [comment]
I'd suggest some way to re-run the initialization process should it fail - then everything else that depends on internal state of the initialization could re-run the initialization step when it's triggered (like showing the settings pane, triggering a command). That way, the user doesn't have to reload the app (or disable/enable the plugin) once they fix the issue.

**Comment by Vinzent03** [comment]
Yes I thought about something similar.
