### ISSUE TITLE
[Bug]: No changes to push

### ISSUE THREAD

**Issue by curi0usJack** [denolehov/obsidian-git#279]
### Describe the bug

When I make a change to a note and attempt to push, I get "No changes to push". 

- I've verified Obsidian-git is configured to the correct branch
- I can _pull_ changes without issue
- I see the change in the local repo using git status
- I can push changes manually using git so it's not a repo priv issue
- I get no error in the developer console
- OS is Arch Linux with Obsidian installed from the AUR (v0.15.9)

### Relevant errors (if available)

```shell
None
```

### Steps to reproduce

- Change a file
- Attempt to push with hotkey

### Expected Behavior

I expect to get a notification that a commit/push was made

### Addition context

This has been going on for several upgrades. 

### Operating system

Linux

### Plugin version

1.28.0

**Comment by Vinzent03** [comment]
Are you just pushing after file change? You need to commit them before push.

**Comment by curi0usJack** [comment]
Thanks for responding. That was it. I was only pushing via my hotkey. 

I could have sworn that Commit + Push was just a single hotkey before. Is that true or have I lost my mind?

**Comment by Vinzent03** [comment]
You can use the create backup command.

**Comment by curi0usJack** [comment]
That must have been it. Thank you again for responding.
