### ISSUE TITLE
Commands of plugin 'Obsidian Git' doesn't display in commands menu in Obsidian 0.9.22 which installed from snap

### ISSUE THREAD

**Issue by GreenRobot777** [denolehov/obsidian-git#28]
Commands of plugin 'Obsidian Git' doesn't display in commands menu (`Ctrl + P`) in Obsidian `0.9.22` [installed from snap](https://github.com/obsidianmd/obsidian-releases/releases/download/v0.9.22/obsidian_0.9.22_amd64.snap)

But this plugin work at the same version Obsidian `0.9.22` [from AppImage package](https://github.com/obsidianmd/obsidian-releases/releases/download/v0.9.22/Obsidian-0.9.22.AppImage)

All packages links i get from https://obsidian.md/

May be root problem from Obsidian core, not in a plugin.

Screenshoot Obsidian `0.9.22` [installed from snap](https://github.com/obsidianmd/obsidian-releases/releases/download/v0.9.22/obsidian_0.9.22_amd64.snap):
![image](https://user-images.githubusercontent.com/14993551/102781173-c5be4280-43c9-11eb-90da-9edd7feb2913.png)

**Comment by BillKracke** [comment]
I had a similar issue and it was an issue with GIT, not obsidian. In my case, I had to accept some new TOS in Xcode (Mac). In any case, viewing the developer tools gave me a clear error code to explore. Once I resolved my GIT issue, plugin worked as expected.

**Comment by mkusz** [comment]
It's a problem with snap release not a plugin itself. Yesterday I have tested it on my Ubuntu machine and I can confirm that this plugin is not working on snap version. Problem is not in plugin, but in snap packages and their sandbox approach to file access, etc. This plugin works utilizing system 'git' command and if it's not accessible, plugin is not loading.

**Comment by Vinzent03** [comment]
If you are on Linux I can recommend the [flatpak](https://flathub.org/apps/details/md.obsidian.Obsidian) version.(Or of course AppImage)
You should have an error in your console (`Ctrl + Shift +i`). Snap apps are in a sandbox, why Obsidian doesn't have access to git.
