### ISSUE TITLE
[Bug]: unable to push new changes

### ISSUE THREAD

**Issue by youbicode** [denolehov/obsidian-git#281]
### Describe the bug

Unable to perform a `git push` from the command palette
![CleanShot 2022-08-20 at 00 21 22](https://user-images.githubusercontent.com/2829896/185714535-221dc606-bcb4-410f-9270-f25edda5bb8e.png)
![CleanShot 2022-08-20 at 00 24 37](https://user-images.githubusercontent.com/2829896/185714793-d8108e62-2cce-4ac7-9d74-9baeee0b58d6.png)

### Steps to reproduce

this was working fine, I updated the plugin and something broke 
unfortunately I can't provide exact steps to reproduce it, just the error message

### Operating system

macOS

### Plugin variant

Obsidian Git

### Plugin version

1.29.0

**Comment by Vinzent03** [comment]
Should be fixed now in new release.
