### ISSUE TITLE
[Bug]: mobile plugin mangles file name 

### ISSUE THREAD

**Issue by bartoszcisek** [denolehov/obsidian-git#282]
### Describe the bug

Running command "stage current file" result in 
> NotFoundError: Could not find ernote migration.md. 

Correct file name is "Evernote migration.md"

### Relevant errors (if available)

```shell
NotFoundError: Could not find ernote migration.md
```
```


### Steps to reproduce

1. Empty vault with installed git plugin
2. Clone remote repo into `.` directory.
3. Change any file content
4. Run command "stage current file" 

### Expected Behavior

File added to stage

### Addition context

![AFB5B7CC-F5D8-4B68-8579-BFF2B3FF4DA3_1_102_o](https://user-images.githubusercontent.com/1272652/185800554-bd46b2ff-214f-495a-b7b7-a2768bc9253d.jpeg)


### Operating system

macOS

### Plugin variant

Obsidian Git Isomorphic

### Plugin version

1.1.7

**Comment by Vinzent03** [comment]
I found the issue and will release a new version today. For now, can you tell me what's in the settings field `Custom base path` and clear it afterwards. It should work then.

**Comment by bartoszcisek** [comment]
Thanks for lightning fast response :) 

I left custom base path empty but it was filled with dot `.` (aka current dir)

**Comment by bartoszcisek** [comment]
I removed dot from `Custom base path` and staging worked.

**Comment by Vinzent03** [comment]
What did you enter as directory when cloning?

**Comment by bartoszcisek** [comment]
This time I left it blank. Previously I entered dot `.` as it was not clear to me what should be there. On a phone tooltip is not shown entirely.

**Comment by Vinzent03** [comment]
Yeah, I need to improve that. Thanks for your feedback.
