### ISSUE TITLE
Don't save custom git binary path in repo

### ISSUE THREAD

**Issue by DJSchaffner** [denolehov/obsidian-git#283]
Hello,

while using Github for synching I just had a situation where I would have found it useful to not save the git binary path in the repository. The reason behind this is that on the computers I use, the git exe file is in different locations and I do not have the necessary rights to change the PATH variable in every of those systems. Every other option would be nice to keep.

While adding this, keeping all the custom paths out of sync would probably be desirable although it's not relevant for me right now.

Maybe as a simple suggestion on on how this could be achieved: Store this path in a seperate file from the other settings so I can add it to the .gitignore file (this way you wouldn't have to change anything about the commit and push process itself)

But feel free to add this in any way you like (If you wish to add this) :)

Until then, I will just have to add the full data.json file to my .gitignore file.

Cheers

**Comment by Vinzent03** [comment]
Oh good point. Will store it in `localstorage`(if you know that). So you don't even have to ignore a special file.

**Comment by DJSchaffner** [comment]
Sounds like a good plan. Looking forward to it :)
