### ISSUE TITLE
[Bug]: Getting Status is always displayed during COMMIT

### ISSUE THREAD

**Issue by a812305914** [denolehov/obsidian-git#286]
### Describe the bug

When I try to commit a local file, I fail, and Getting Status keeps showing. Is it related to the fact that my file contains Chinese?

The plug-in is obsidian-git-mobile

### Steps to reproduce

Open the command panel and enter the Obsidian Git Mobile commit all changes command

### Operating system

Windows

### Plugin variant

Obsidian Git Isomorphic

### Plugin version

1.1.11

**Comment by Vinzent03** [comment]
Does the `Getting status` notice keep forever and no notice about `Committed X files` or does it commit and the notice is still there?

**Comment by a812305914** [comment]
`Getting status` notice keep forever and no notice about `Committed X files`

**Comment by Vinzent03** [comment]
How big is your vault? It may be too many files and it takes just long.

**Comment by a812305914** [comment]
just 26MB，but there are a lot of documents，maybe thousands of files

**Comment by Vinzent03** [comment]
Then the count of files is the issue. See [performance](https://github.com/Vinzent03/obsidian-git-mobile#performance) in the README.

**Comment by a812305914** [comment]
I got it. Thank you
