### ISSUE TITLE
Plugin installed but config tab isn't shown in under  plugin options

### ISSUE THREAD

**Issue by adam-b-peterson** [denolehov/obsidian-git#29]
Tried to reinstall both obsidian & obsidian-git.
It used to be working with auto updates but since then it does not auto push and pull with commits.
May you advise what I can do to fix this?

![Screenshot 2020-12-24 at 5 15 50 PM](https://user-images.githubusercontent.com/41034824/103077899-aca4d400-460b-11eb-927f-80091b365d49.png)

**Comment by dimateos** [comment]
After first installation I had to restart obsidian. Maybe you reinstalled both but didnt try a restart afterwards?

**Comment by sylumer** [comment]
Looks like this is probably the same as the details covered by this issue whereby the plugin is not getting initialised correctly - https://github.com/denolehov/obsidian-git/issues/27

**Comment by stefanoginella** [comment]
I have the same issue.

I just installed Obsidian 0.10.6 on Windows 10 (with Git 2.30.0 installed).
I enable Obsidian Git 1.5.0 but the option tab is not showing up (currently it's the only plugin installed).
The repository is already initialized and I manually did a first commit to GitHub.
On the bottom-right corner of Obsidian I can see the `git:ready` status, but it doesn't seem to commit/push new changed. I tried creating a new test file, but it just doesn't get committed even after more than 30 mins.

**Comment by stefanoginella** [comment]
Nevermind, I had just installed Git on Windows (I normally use Git inside WSL so I didn't have it installed on Windows).
With a logout/login it all got solved, now the option tab is visible! :)

**Comment by adam-b-peterson** [comment]
wow thank you @stefanoginella for your comment.
I've already installed git on my macOS, but I tried to update to the latest version after seeing your comment.
Magically, I don't know why it helps.
For some unknown reasons, git 2.28.0 don't work well with obsidian git on Mac OS.
Upgrading to git 2.30.0 solved the problem.
Thank you for your feedback @stefanoginella !
