### ISSUE TITLE
[bug] `DisableNotification` setting does not work on obsidian git mobile (iOS).

### ISSUE THREAD

**Issue by andylizf** [denolehov/obsidian-git#292]
Maybe because there is no check for the `DisableNotification` setting before raise a `Notice` in file [isomorphicGit.ts](https://github.com/denolehov/obsidian-git/blob/master/src/isomorphicGit.ts)

**Comment by Vinzent03** [comment]
Some commands can take a while. So I want the user
always to know that the command is still running. I may delay the notice so that they come only up if the task takes like > 5 seconds. Which notices are disturbing you in particular?

**Comment by mwxgaf** [comment]
It shows **all** notifications even if you disable notifications (In Android too)

**Comment by Vinzent03** [comment]
@mwxgaf Notifications like
- Everything is up to date

**Comment by mwxgaf** [comment]
yes yes
this is right
I had not paid attention
this is not about all notifications

> You should see notifications like Getting Status or progress notifications

do you have any plan to fix this?

**Comment by green-codes** [comment]
The spec is that only *errors* are shown, *all* other notifications should be silenced. 

I depend on Obsidian Git for syncing all my vaults and have all auto backup options on, and it’s quite annoying to be bombarded by status updates every time I startup the iOS app. Hope this is fixed soon.

**Comment by mwxgaf** [comment]
For a temp solution I commented all `Notice` lines in the JS file

**Comment by Vinzent03** [comment]
Should be fixed now. If the status command takes longer than 20s I'm still showing a notification to let the user know a task is running long.

**Comment by bd-g** [comment]
I am getting an error with the new pull request

```
TypeError: undefined is not an object (evaluating progressNotice.noticeEl')
```

**Comment by bd-g** [comment]
@Vinzent03 just implementation details - for example, in file `obsidian-git/src/isomorphicGit.ts`, a sample change is below

```
// This used to ALWAYS be a Notice object - now it can be undefined
const progressNotice = this.showNotice("Initializing pull");
...
...
// progressNotice is used here, but if it is undefined it will fail
(progressNotice as any).noticeEl.innerText = this.getProgressText("Checkout", progress);
```

I will see if there is a fix in the next day or two. If not, I may try to find time to make a PR with my own fix.

**Comment by echo-saurav** [comment]
Am i suppose to see "finish pull" every time?? . i get this notification on ios

**Comment by Vinzent03** [comment]
@echo-saurav Should be fixed now!
