### ISSUE TITLE
Error: fatal: not a git repository (or any parent up to mount point /Volumes)

### ISSUE THREAD

**Issue by dsebastien** [denolehov/obsidian-git#294]
I've distributed a pre-made Obsidian vault that includes the Obsidian Git plugin.
Locally I have no issue because git is installed, but some of the persons I've share the vault with get the following error upon startup when the Obsidian Git plugin is installed and enabled:

```
Error: fatal: not a git repository (or any parent up to mount point /Volumes)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

I suppose it makes sense since the vault does not include a git repository and some of those persons don't even have Git installed.

Is it to be expected that the plugin generates/shows those errors when there is no Git repository and/or when git is not installed?

**Comment by Vinzent03** [comment]
This is by design so. The plugin expects a Git to be installed and the repository to exist. I suggest them to just disable the plugin.

**Comment by dsebastien** [comment]
I supposed so. It somewhat makes sense, but I wonder if you would reconsider given the impact on user experience?

For non-technical users, it makes the whole process more complicated than it needs to be, and gives them the impression that they've broken their installation.

Ideally, there should be a notification upon startup if the plugin is enabled and one of those critical conditions are met, warning the user that the plugin will not be active until they install/configure git and a repository properly. What do you think?

**Comment by Vinzent03** [comment]
> Ideally, there should be a notification upon startup if the plugin is enabled and one of those critical conditions are met, warning the user that the plugin will not be active until they install/configure git and a repository properly.

I'm unsure I understood you correctly. Isn't the error already on startup? Or do you just want to rephrase the error? Or explaining more in the notice?

**Comment by dsebastien** [comment]
I think that rephrasing the notice would help the message to be less scary for less technical users :p
Also, I don't know if it's the case now, but it should only appear once, not upon each and every startup of Obsidian

**Comment by 2colours** [comment]
I'm getting this error with git installed and even the repository set up inside the folder I actually want to share (although I think the latter could be handled by the plugin).
