### ISSUE TITLE
[Bug]: `HttpError: HTTP Error: 401 401` on push on mobile repo

### ISSUE THREAD

**Issue by NomarCub** [denolehov/obsidian-git#296]
### Describe the bug

I have a repo on mobile that I accessed through MGit and Termux up until now. I installed the plugin, tried to push and I got this error message and no push. The host is on GitLab. The plugin definitely recognises the repo, an automatic commit was made and I can see the author name and email in settings.

![image](https://user-images.githubusercontent.com/5298006/188742314-d66f9d75-f77e-43b0-ba6b-67b85541cbbd.png)

### Steps to reproduce

Have an existing repo and open it in the app and try to push. It also happens with automatic push,

### Operating system

Android

### Plugin version

2.0.3

**Comment by Vinzent03** [comment]
Did you specify the password and username in the settings?

**Comment by NomarCub** [comment]
No, and that solved it, thanks!
The plugin should warn me about this instead of or after the HTTP error message, if that's possible.
