### ISSUE TITLE
[Bug]: Mobile doesn't use .gitignore

### ISSUE THREAD

**Issue by NomarCub** [denolehov/obsidian-git#297]
### Describe the bug

Here are my rules to ignore Obsidian plugins:

```gitignore
.obsidian/plugins/**/**js
.obsidian/plugins/**/manifest.json
.obsidian/plugins/**/styles.css
```

They work on Windows but not on android, the files are listed in changes.

The `Checkout progress: Analyzing workdir:` message also counts up above 1000 even though I have like half that many files tops, which is suspicious and looks related.

![image](https://user-images.githubusercontent.com/5298006/188754232-dac78b0b-1666-4235-9271-81a774522057.png)

### Steps to reproduce

Make a gitignore mentioned above in root.

### Operating system

Android

### Plugin version

2.0.3

**Comment by Vinzent03** [comment]
Gitignore should works, but maybe your syntax is not supported by the underlying lib?

**Comment by NomarCub** [comment]
Could you help me test the underlying lib? I looked around and didn't find docs on isogit's gitignore and I get errors running isogit cli on desktop.

**Comment by Vinzent03** [comment]
I think your syntax is wrong. `**.js` is wrong.`**` Should only be used for directories. Please try `*` instead. See the [documentation](https://git-scm.com/docs/gitignore#_pattern_format)

**Comment by NomarCub** [comment]
Thanks, your suggestion worked!

My syntax could be better, but it's not wrong for matching these files. It works on Windows, Linux WSL, Termux and MGit on Android. In the doc you linked it says that any non-leading, non-trailing or not `/`-enclosed `**` gets treated as normal asterisks, which match anything. I'll file an issue upstream.
