### ISSUE TITLE
[Bug]: Source control view is broken on mobile

### ISSUE THREAD

**Issue by NomarCub** [denolehov/obsidian-git#298]
### Describe the bug

When I open up changes sometimes all, sometimes half the buttons are covered. The thing next to the refresh button looks and behaves weirdly (I have commit message set to `{{date}}`, that shows up there in desktop.)
![image](https://user-images.githubusercontent.com/5298006/188755564-66329be3-2c2c-4041-b316-168507765e35.png)

### Steps to reproduce

Have varying amount of changes, open source control view, fold folders.

### Operating system

Android

### Plugin version

2.0.3

**Comment by Vinzent03** [comment]
The view design should be improved on desktop as well and will fix issues on mobile too then.

**Comment by NomarCub** [comment]
Is there a general source view ticket?

I'd also note that the add `+` buttons on files are really small on Android.
And it'd be nice to have a stage and unstage button for folders too.

**Comment by Vinzent03** [comment]
I've done all these features now locally. I've aligned it to the file view in Obsidian and used their css classes etc. But it's looks weird on < v0.16 of Obsidian. And I don't want to make all future releases 0.16 only, so I'll wait until Obsidian 0.16 is public.

**Comment by NomarCub** [comment]
Thanks!
My existing CSS customizations work right out of the box 😁
![image](https://user-images.githubusercontent.com/5298006/195645420-b466ace2-d00a-4a05-962f-0c96d82118f8.png)

I found some hitches however.

- The corner of the commit message input box thing looks weird on mobile. It has a scrollbar when there's only one line. And there's that thing in the corner. I have no idea what it does and it looks uglier than on PC.
![image](https://user-images.githubusercontent.com/5298006/195646053-182902a3-9885-4050-858c-6972036e2c7c.png)

- There's this jittering when refreshing on mobile.

https://user-images.githubusercontent.com/5298006/195646178-2e8f2741-1483-40f1-9556-958bfe30c15b.mp4

- "nesting" folders misbehaves, doesn't go as deep as it could
![image](https://user-images.githubusercontent.com/5298006/195647760-1be041b6-8ffa-4b44-bc3f-caea8a16ef3e.png)
![image](https://user-images.githubusercontent.com/5298006/195647801-270d208d-4bb2-41d6-9b95-236fdd44301c.png)

- and with the plus buttons on folders, it would make sense to have an add all, discard all button for the root on the fold of "changes" and "staged changes", like there is in VSCode
![image](https://user-images.githubusercontent.com/5298006/195648689-4ece11bb-5037-4e7e-acad-59acaf2c6354.png)

**Comment by Vinzent03** [comment]
I've changed the height of the textarea to behave like in vscode. So you can't resize it manually anymore, just by adding/removing a line.
Looks like I only tested 2 depth folders.
Both not released yet.

I thought about adding the stage/unstage button to the category as well, but I thought it would make the ui cleaner not adding another button there, but keeping it at the top. What do you think?

**Comment by NomarCub** [comment]
If files and folders have the button, I think the root (changes, staged changed) should have it too. There's nothing else where it would go anyway, I don't think it would be cluttered. But don't base this just on me.

**Comment by NomarCub** [comment]
Also, I just noticed, there's no discard button on folders under changes, which would also be handy.

**Comment by Vinzent03** [comment]
Oh true. Will add that as well.
