### ISSUE TITLE
[Bug]: Cloning on mobile fails, and plugin deletes itself

### ISSUE THREAD

**Issue by chrisgrieser** [denolehov/obsidian-git#299]
### Describe the bug

So I tried to set up Obsidian git on mobile (iOS). My remote is a private git repo.

1. Create new Personal Access Token on GitHub
2. On Obsidian Mobile, create a new vault.
3. Install Obsidian Git in that vault.
4. Enter GitHub username & PAT in the Obsidian git settings
5. Run Command to clone a remote repo
6. enter HTTPS remote address (`https://github.com/chrisgrieser/{{foobar}}.git`).
7. Select: Vault Root → YES (has .obsidian folder) → DELETE...

Now I get the notification "Initializing clone". Nothing further happens. After a while, Obsidian crashes, and when I restart, the plugin seems to have deleted itself? (it's literally gone from the installed plugins) 

Since I assumed it was an issue with the plugin overriding `.obsidian` while downloading `.obsidian`, I tried 7) with "Vault Root → NO". The result is the same, only after Obsidian crashing it, the Obsidian git plugin has not deleted itself. 🥴 

The phone does get slightly warm during that time, so I assume it does try to do something?

### Additional Context
My vault contains images and is therefore fairly big, if that's an issue? (Vault size: 300 Mb, .git size: 700 Mb, so a total of 1Gb to clone?)

I have previously been using working copy, and it did not have an issue with the repo though.

### Operating system

iOS

### Plugin version

2.0.3

**Comment by Vinzent03** [comment]
Yeah your repo is too big. It's crashing, because of out of memory. I don't know what I can do about that. Must be an issue with isomorphic-git.

**Comment by chrisgrieser** [comment]
hmmm, well, back to working copy then 🙁

**Comment by Vinzent03** [comment]
I'm really sorry, and it hurts still having such issues. 🙁

**Comment by chrisgrieser** [comment]
Probably you already explored this, but just out of curiosity: what form of git is working copy using, and why isn't that an option?

**Comment by Vinzent03** [comment]
It's a native iOS app, so I guess it can use some native c implementation. Obsidian uses Capacitor, which allows running a javascript app on mobile. I can't access any native APIs so I have to use a reimplementation of Git in JS. Another approach was a web assembly Git version, but haven't tries it yet.
