### ISSUE TITLE
Mobile setting for git config user.email

### ISSUE THREAD

**Issue by MarcoDiFrancesco** [denolehov/obsidian-git#300]
Hello, when committing on mobile it's not possible to set `git config user.email` in the plugin config, so I cannot commit changes. Could you please add this option?

![Screenshot_2022-09-07-09-00-50-63_51606159b24eff83e24a54116878fe3e](https://user-images.githubusercontent.com/7454137/188800590-d3de33e3-2de2-41a0-b1d8-246e5ae57c2c.jpg)

**Comment by Vinzent03** [comment]
When you initialized a repo you should find it in the settings under advanced at the bottom.

**Comment by MarcoDiFrancesco** [comment]
Found it. Thanks!
