### ISSUE TITLE
[Bug]: Diff view is broken on mobile

### ISSUE THREAD

**Issue by NomarCub** [denolehov/obsidian-git#302]
### Describe the bug

The diff view comes up empty, and when you open a file from file navigation or quick switcher it opens besides the diff view, not instead/on top of it as I'd expect for a view on mobile.

![Screenshot_2022-09-07-17-08-09-89_51606159b24eff83e24a54116878fe3e](https://user-images.githubusercontent.com/5298006/188913977-9a51ac12-f77f-485a-b314-84805908ff42.jpg)

### Steps to reproduce

Open a changed file in diff view. Opan a file from quick switcher.

### Operating system

Android

### Plugin version

2.0.3

**Comment by NomarCub** [comment]
In 2.1.1 the split is fixed, but the diff view is still empty.

**Comment by Vinzent03** [comment]
The underlying lib doesn't provide a diff method so I have to get the diff with a different lib and format it like the git output.

**Comment by NomarCub** [comment]
I'm fine with whatever solution.
It should be mentioned here at least: https://github.com/denolehov/obsidian-git#restrictions-of-the-mobile-version
And the command should be disabled if it's not done.

**Comment by Vinzent03** [comment]
You are right, but I already started working on this and will hopefully be finished soon.
