### ISSUE TITLE
[Bug]: Diff view to new pane breaks tabs

### ISSUE THREAD

**Issue by NomarCub** [denolehov/obsidian-git#306]
### Describe the bug

![image](https://user-images.githubusercontent.com/5298006/189177133-4b52c8ea-aae5-4049-8ea8-458fc131b002.png)

### Steps to reproduce

Open a note. Ctrl + click on a change in source control view. I am using the 0.16.2 insider Obsidian version that has tabs.

### Operating system

Windows

### Plugin version

2.1.0

**Comment by NomarCub** [comment]
To make it more up to par and consistent with the new Obsidian version, Ctrl + Alt + click should open a new pane and Ctrl + Click should open a new tab.
Now with diffs Ctrl + Alt + click opens tabs instead of panes, and with files Ctrl + click opens panes instead of tabs.

**Comment by Vinzent03** [comment]
Didn't know there hotkeys. Will add them as well.

**Comment by NomarCub** [comment]
Thanks!
Here are the hotkeys in the official release notes: https://forum.obsidian.md/t/obsidian-release-v0-16-0-insider-build/42536#improved-2

**Comment by NomarCub** [comment]
The open diff hotkeys are good now, but the open file hotkeys are still the same and always open a new pane.
