### ISSUE TITLE
Git is not ready!

### ISSUE THREAD

**Issue by JacksonNiu616** [denolehov/obsidian-git#314]
![image](https://user-images.githubusercontent.com/104992911/190866517-9c71526b-a2e5-4675-8a2d-5a4dc81138bd.png)
my git can work in other app,  How can i get it ready for obsidian?
thanks!

**Comment by Vinzent03** [comment]
There should be a notification when starting Obsidian, which gives you more details why it's not ready.

**Comment by driftywinds** [comment]
I am having the same issue, even though the vault opened is cloned from my repo. This is what it shows me when I start Obsidian - 
![Screenshot_2022_09_21_17_49_16_08_51606159b24eff83e24a54116878fe3e](https://user-images.githubusercontent.com/63164617/191502132-415a3438-5a9f-4b8c-91b7-3359df8c46dd.jpg)

**Comment by Vinzent03** [comment]
@driftywinds Can you verify in you file viewer or terminal that a .git directory exists at the root of you obsidian vault? And try clearing the base path setting.

**Comment by driftywinds** [comment]
> @driftywinds Can you verify in you file viewer or terminal that a .git directory exists at the root of you obsidian vault? And try clearing the base path setting.

yes there is a .git directory at the root of my vault and the bas path setting is cleared. It still gives me the same error

**Comment by adams141** [comment]
what is "the existing command"? or how do I clone an existing repo on mobile?

**Comment by mathewlowry** [comment]
Same problem. There was no notification when starting Obsidian. There is a .git directory. 
What does "clearing the base path setting" refer to?

**Comment by Vinzent03** [comment]
@mathewlowry There is a `base path` setting, which may cause this issue. Is there any error in the console? (`CTRL + SHIFT + I`)

**Comment by AlainRo** [comment]
+1 working well on a machine but "git is not ready" on another one with the same remote repo. No visible error in the console.

**Comment by mathewlowry** [comment]
Hi, The instructions I was following were to install GitHub Desktop, but that turned out to be a mistake. I installed Git, messed about for a while with the guys behind massive.wiki, and got it working. Not exactly a simple install process, tho - will document it at some point, but for now hope this helps.

**Comment by AlainRo** [comment]
I found an error message :
<img width="437" alt="Capture d’écran 2022-10-02 à 12 28 54" src="https://user-images.githubusercontent.com/1700044/193449596-4acfcec0-6671-4cda-9251-654b38e769b7.png">

**Comment by Vinzent03** [comment]
@AlainRo See #67

**Comment by AlainRo** [comment]
Problem solved after : xcode-select --install
👍
Thank you for this plugin

**Comment by CupidTian** [comment]
> 

I use Win11 OS, and my git support the "3rd-party command"

**Comment by jiazhanhe** [comment]
![image](https://user-images.githubusercontent.com/45416227/196401601-28ffbb50-7f8d-4354-9a5c-c21fe31db0e1.png)

- Win 10
- Obsidian 1.0
- Git is installed 
- already git init

**Comment by Vinzent03** [comment]
@CupidTian That's strange, maybe git is installed in an unusual location that's not in the `PATH` env var of Obsidian?

**Comment by Vinzent03** [comment]
@marcluque how did you install Obsidian?

**Comment by marcluque** [comment]
> @marcluque how did you install Obsidian?

With snap

**Comment by Vinzent03** [comment]
@marcluque Snap is not reported as stated in the [README](https://github.com/denolehov/obsidian-git#desktop)

**Comment by lemonway64** [comment]
Excuse me, I meet same problem as marcluque in windows11. How can I slove this?

**Comment by marcluque** [comment]
How did you install Obsidian @lemonway64?

**Comment by lemonway64** [comment]
> How did you install Obsidian @lemonway64?

I just download through the official site with windows 11

**Comment by charlesNeedFocus** [comment]
Excuse me. I meet the same problem  in windows10. how can i slove this.? obsidian v1.1.8 . i added git install path to the Path variables.
![image](https://user-images.githubusercontent.com/37182312/209373682-b3a9e287-7a61-48da-9a15-272c23751dad.png)

**Comment by charlesNeedFocus** [comment]
> Excuse me. I meet the same problem in windows10. how can i slove this.? obsidian v1.1.8 . i added git install path to the Path variables. ![image](https://user-images.githubusercontent.com/37182312/209373682-b3a9e287-7a61-48da-9a15-272c23751dad.png)
 
ok，i put the whole path in the Git binary path: C:\Program Files\Git\bin\git.exe . and it works ! ! !

**Comment by lemonway64** [comment]
exactly. need to download this: 

https://git-scm.com/

**Comment by oneegin** [comment]
I use GitHubDesktop and windows 10, I put the whole path in the Git binary path 
c:\Users\....your_name.....\AppData\Local\GitHubDesktop\app-3.1.2\resources\app\git\cmd\git.exe

**Comment by talismangit** [comment]
My obsidian says "Git is not ready. WHen all setting are correct you can configure auto backup, etc.
I dont get any notificatons and I have everything set-up like in the tutorial by Danny Talks Tech.

**Comment by Vinzent03** [comment]
@talismangit Is there any error in the console (`CTRL + SHIFT + I`)? You should get a notification what exactly is wrong.

**Comment by Chang-Hoon** [comment]
I had the same issue and tried all siad on https://github.com/denolehov/obsidian-git/issues/405 and reisntall/update git, and downgrade `obsidian-git` but ALL didn't work.

It just backed to work when my Windows 10 laptop rebooted.

**Comment by bsridatta** [comment]
Having the same issue on startup it says cannot run git command while I have it in the standard location `/usr/bin/git`

**Comment by Harvey-myc** [comment]
> windows 10, I put the whole path in the Git binary path

I only works with this path : C:\Program Files\Git\cmd\git.exe. just for note

**Comment by jubiiz** [comment]
I had the same issue. I'm on Win 10 Pro.
I fixed it by adding Git to my PATH environment variable (it had gotten removed somehow).
