### ISSUE TITLE
[Feature Request]: option to additionally "Commit&Push" at program closure

### ISSUE THREAD

**Issue by Gewerd-Strauss** [denolehov/obsidian-git#317]
Hello,

would it be possible to add a feature to push all outstanding commits at program closure? I've just noticed that I was pending 220 committed changes from five days because I never gave the program time to push. At the same time, I don't want to reduce my timers even more because I already start encountering timing related issues with the program freezing sometimes when running through the routines.

Thank you.
Sincerely,
~Gw

**Comment by NomarCub** [comment]
There's already an issue for this, see #13

**Comment by Gewerd-Strauss** [comment]
Whoops, I somehow did not find issue. Will close this one then,
