### ISSUE TITLE
[Bug]: Do not backup automatically when using another sync service

### ISSUE THREAD

**Issue by Kitefr** [denolehov/obsidian-git#319]
### Describe the bug

I am using Sync but also Obsidian Git as a way to save all the history into a repository. Just in case.
I switched the sync method to "Other Sync Service".

When I run the command "Create Backup", It shows all the steps but nothing actually occur.
I have to Stage files, commit and push manually on the View Diff panel to actually make the backup.

### Relevant errors (if available)

```shell
loading Obsidian Git plugin
plugin:obsidian-git:30818 git obsidian message: Committed 41 files
plugin:obsidian-git:30818 git obsidian message: Pulled 41 files from remote
plugin:obsidian-git:30601 Pushing....
plugin:obsidian-git:30603 Pushed! 0
plugin:obsidian-git:30818 git obsidian message: No changes to push
plugin:obsidian-git:30818 git obsidian message: Committed 41 files
plugin:obsidian-git:30818 git obsidian message: Pulled 41 files from remote
plugin:obsidian-git:30601 Pushing....
plugin:obsidian-git:30603 Pushed! 0
plugin:obsidian-git:30818 git obsidian message: No changes to push
plugin:obsidian-git:30601 Pushing....
plugin:obsidian-git:30603 Pushed! 0
plugin:obsidian-git:30818 git obsidian message: No changes to push
plugin:obsidian-git:30818 git obsidian message: Committed 0 file
plugin:obsidian-git:30601 Pushing....
plugin:obsidian-git:30603 Pushed! 0
plugin:obsidian-git:30818 git obsidian message: No changes to push
plugin:obsidian-git:30601 Pushing....
plugin:obsidian-git:30603 Pushed! 41
plugin:obsidian-git:30818 git obsidian message: Pushed 41 files to remote
plugin:obsidian-git:30818 git obsidian message: No changes to commit
plugin:obsidian-git:30818 git obsidian message: No changes to push
```

### Steps to reproduce

Using "Other Sync Service"
Run command "Create Backup"
Data gets backup up to repository.

### Expected Behavior

Just wish for it to backup every 5 minutes (as I configured it) to the repository without merging or rebasing.
It was working fine before but now, nothing is updated. Have to do it manually each time.

### Operating system

Windows

### Plugin version

2.2.1

**Comment by Vinzent03** [comment]
Does the new release fix your issue?

**Comment by Kitefr** [comment]
Just tested and seems to be fixed. I will monitor. Thank you !
