### ISSUE TITLE
[Bug]:Can not use in ubuntu

### ISSUE THREAD

**Issue by Jarvi-sang** [denolehov/obsidian-git#324]
### Describe the bug

I can't use the plugin obsidian git.
When I open the software, the plugin hint me:  **Cannot run git command**

### Steps to reproduce

When I open the software, the plugin hint me:  **Cannot run git command**

### Operating system

Linux

### Plugin version

2.4.1

**Comment by Vinzent03** [comment]
Did you install Obsidian using snap? https://github.com/denolehov/obsidian-git#installation-on-desktop

**Comment by Jarvi-sang** [comment]
OK, Sorry I don't notice that.
