### ISSUE TITLE
How do Use a Custom Branch as the base

### ISSUE THREAD

**Issue by vkbytes** [denolehov/obsidian-git#325]
I wanted to configure a custom branch as the repository and push my files to it and then create a pull request from that branch to be merged with `main`. Essentially following the `pull-request` methods of github.

**Comment by Vinzent03** [comment]
You can create new branches and push to a new remote branch. I don't know what you are missing.

**Comment by vkbytes** [comment]
ah I was a bit confused as to which branch in the repo it is using. So It just commits to the current branch that is on the filesystem. 
So if I switch to a branch on the filesystem it just updates to those files on Obsidian. I was assuming that I need to configure the branch that Obsidian GIt will use in the plugin settings.

**Comment by Vinzent03** [comment]
It's just using Git. So it can only commit to the currently checked out branch.

**Comment by vkbytes** [comment]
Thank you, this is perfect, I can commit to a branch and create pull request for it to be merged. I love this.
Thank you @Vinzent03 for your help
