### ISSUE TITLE
[Bug]: Error: git: 'credential-manager-core' is not a git command.

### ISSUE THREAD

**Issue by m10x** [denolehov/obsidian-git#326]
### Describe the bug

I've setup [git-credential-manager](https://github.com/GitCredentialManager/git-credential-manager) with the following commands:
`sudo dpkg -i git-credential-manager.deb`
`git-credential-manager-core configure`
`git config --global credential.helper manager-core`
`git config --global credential.credentialStore secretservice`
`printf "host={redacted}.de\nprotocol=https\nusername=m10x\npassword={accesstoken}" | \git credential-manager-core store`
This way I don't have to specify any username or password when using git with my obsidian git repository. (ssh is not possible because I disabled SSH for gitea, the normal username + password login is also not possible because I have 2fa enabled).  
  
This works flawlessly when using the git command line tool. I don't have to specify any credentials anymore and can pull, push, whatever I want.
  
When trying to pull or push via obsidian-git I receive the following error message:
```
Uncaught (in promise) Error: git: 'credential-manager-core' is not a git command. See 'git --help'.
git: 'credential-manager-core' is not a git command. See 'git --help'.
fatal: could not read Username for 'https://{redacted}.de': No such device or address

    at Object.action (plugin:obsidian-git:23833:25)
    at PluginStore.exec (plugin:obsidian-git:23858:25)
    at eval (plugin:obsidian-git:21445:43)
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (plugin:obsidian-git:21443:16)
    at GitExecutorChain.eval (plugin:obsidian-git:21427:44)
    at Generator.next (<anonymous>)
    at fulfilled (plugin:obsidian-git:20276:24)
```
So, credential-manager-core is not a git command? The following works just fine
```
$ git credential-manager-core --version
2.0.785+6074e4e3d3
```
My .gitconfig looks like this
```
[user]
        email = {Email}
        name = m10x
[credential]
        helper = manager-core
        credentialStore = secretservice
        #helper = 
        #helper = /usr/local/share/gcm-core/git-credential-manager-core
[credential "https://{redacted}.de"]
        provider = generic
[credential "https://dev.azure.com"]
        useHttpPath = true
```
When interchanging `helper = manager-core` for `helper = /usr/local/share/gcm-core/git-credential-manager-core` the obsidian-git error message looks like
```
Uncaught (in promise) Error: /usr/local/share/gcm-core/git-credential-manager-core get: line 1: /usr/local/share/gcm-core/git-credential-manager-core: No such file or directory
git: 'credential-manager-core' is not a git command. See 'git --help'.
fatal: could not read Username for 'https://{redacted}.de': No such device or address

    at Object.action (plugin:obsidian-git:23833:25)
    at PluginStore.exec (plugin:obsidian-git:23858:25)
    at eval (plugin:obsidian-git:21445:43)
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (plugin:obsidian-git:21443:16)
    at GitExecutorChain.eval (plugin:obsidian-git:21427:44)
    at Generator.next (<anonymous>)
    at fulfilled (plugin:obsidian-git:20276:24)
```
However, the path is correct
```
$ /usr/local/share/gcm-core/git-credential-manager-core --version
2.0.785+6074e4e3d3
$ ls -l /usr/local/share/gcm-core/git-credential-manager-core
-rwxr-xr-x 1 1001 lpadmin 67313818 Jul  8 17:36 /usr/local/share/gcm-core/git-credential-manager-core
```
On my laptop (Linux Mint + Obsidian Flatpak), I have the same setup + config file and there it works fine. I have no clue why git-obsidian doesn't find credential-manager on my PC (PopOs + Obsidian Flatpak).

### Steps to reproduce

`sudo dpkg -i git-credential-manager.deb`
`git-credential-manager-core configure`
`git config --global credential.helper manager-core`
`git config --global credential.credentialStore secretservice`
`printf "host={redacted}.de\nprotocol=https\nusername=m10x\npassword={accesstoken}" | \git credential-manager-core store`
And try to pull or push with obsidian-git

### Operating system

Linux

### Plugin version

2.5.0

**Comment by helnokaly** [comment]
@m10x I have the same issue, did you manage to solve it?
I use Obsidian Flatpak on Ubuntu 22.04

**Comment by m10x** [comment]
@helnokaly No, I wasn't able to. As obsidian still does the commits, I use the terminal to manually git pull and git push

**Comment by Vinzent03** [comment]
It's weird that it works on your laptop, but not on your pc, although both use Flatpak. Is the flatpak installation on pc much older than on laptop? Maybe some config is different, allowing the access of the manager at that path or not. Since it got the correct absolute path, this can't be a `PATH` problem, right?

**Comment by helnokaly** [comment]
![Screenshot from 2022-10-21 01-06-52](https://user-images.githubusercontent.com/15964842/197076065-eb89cb7f-98c9-4c20-9440-77ed56814f1e.png)

The error I get, if is it helps.

**Comment by Vinzent03** [comment]
@helnokaly I guess it exists, but can you verify the file exists?

**Comment by helnokaly** [comment]
@Vinzent03 It exists
![image](https://user-images.githubusercontent.com/15964842/197392056-dc53963e-fbae-4e0c-ba64-7e761fbc1035.png)

**Comment by m10x** [comment]
@Vinzent03 Hey, on both devices are environment variables, paths, configs, and obsidian versions (the latest, didn't make a difference whether pre or after version 1.0) the same. However, on my laptop I had an old version of obsidian-git installed. With version 2.2.1 it works flawlessly. After updating to the latest version (2.8.0) the described issue happens now on my laptop, too. So it seems, that this is a bug which didn't exist (at least) for 2.2.1.

**Comment by Vinzent03** [comment]
Hey @m10x @helnokaly  I've added a setting to modify the PATH env car. This may solves your issue.

**Comment by helnokaly** [comment]
@Vinzent03 Thanks but I'm confused what should I write in the new setting?

Tried that and it did not solve the issue.
![image](https://user-images.githubusercontent.com/15964842/199791280-b2988b81-6837-42b6-8676-873618ce80ec.png)

**Comment by Vinzent03** [comment]
That should be correct, then the issue must be somewhere else. Sorry.

**Comment by Vinzent03** [comment]
@helnokaly I think the issue is that you installed Obsidian via flatpak. May you try another method like AppImage?

**Comment by bzq360** [comment]
@Vinzent03 Thank you! Uninstalling the flatpak one and then reinstalling the AppImage solved my issue.
