### ISSUE TITLE
[Bug]: Diff view shows whole file as changed when I click the stage button

### ISSUE THREAD

**Issue by NomarCub** [denolehov/obsidian-git#327]
![view header overlap](https://user-images.githubusercontent.com/5298006/193119923-753fdc4f-4bee-412e-a9a0-751f3d8465e3.gif)

It's not obvious to me what should happen, but this behaviour is definitely not useful. When the file of the current diff view is staged, it could either switch to it's staged diff view / show the diff view as empty / close it (which is what I'd prefer).

**Comment by skouzini** [comment]
What is enabling you to have the diff functionality in the sidebar?

**Comment by NomarCub** [comment]
This plugin has an `Open source control view` command, if that's what you mean, @skouzini.

**Comment by sjsadowski** [comment]
Popping in because I just ran into this. git diff on the same file is correct.
