### ISSUE TITLE
Does not push if no changes detected even though there are unpushed commits.

### ISSUE THREAD

**Issue by AlansCodeLog** [denolehov/obsidian-git#33]
For example, this can happen if a user manually adds a commit. Or they mess around with the history in such a way as to be have commits that have not been pushed but the working directory is clean.

To Reproduce:
```bash
touch test.txt
git add .
git commit -m "manual commit"
```
In Obsidian => commit all and push command => says no changes detected.
```bash
git status
# produces:
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
```

**Comment by denolehov** [comment]
good catch! plugin tries to do `git status` and if no files are changed, it assumes that there is nothing to push. I will address that, thank you!

**Comment by Vinzent03** [comment]
Is now available in the new [release](https://github.com/denolehov/obsidian-git/releases/tag/1.6.0)
