### ISSUE TITLE
[Bug]: plugin does not respect .gitignore

### ISSUE THREAD

**Issue by ddelange** [denolehov/obsidian-git#331]
### Describe the bug

Hi! 👋 

I've noticed that the plugin does not respect `.gitignore`.

My mac and android both have different files open etc in Obsidian, affecting the `.obsidian/workspace` file.

Hence, I added `.obsidian/workspace` to `.gitignore`, to avoid committing the workspace file as it is transient and device-dependent.

However this is not respected.

Currently, both parties are constantly committing their opinion on the file, also leading to conflicts (but they push through).

### Steps to reproduce

- write a `.gitignore` containing the line `.obsidian/workspace`
- commit the `.gitignore`
- run `git rm --cached .obsidian/workspace`, and commit that deletion (file should still exist locally but is now ignored)
- obsidian will now check in `.obsidian/workspace` again, commits, pushes.
- this renders `.gitignore` useless, because files that are already checked in will be tracked regardless of what `.gitignore` says.

### Expected Behavior

`.gitignore` is respected, and neither party tries to push `.obsidian/workspace` since the file was never staged.

### Operating system

macOS

### Plugin version

2.5.1

**Comment by Vinzent03** [comment]
I'm using the system installed git on desktop. So I'm **very** sure it's respected. I guess it's in the wrong directory or since you can't run `git rm --cached .obsidian/workspace` on mobile you got the file via mobile on desktop.

**Comment by ddelange** [comment]
Ok let me check!

**Comment by Vitor12xx** [comment]
I'm running into the same problem. 
Currently looking for a way to make it work

**Comment by ddelange** [comment]
i wansnt completely clear in step 4: its obsidian _on mobile_ that doesnt like the new commits from desktop: because workspace file is changed locally (mobile) and removed on remote. it does popups with a pull, conflict, push. 

the resulting pushed commit will contain the workspace file as it was on mobile.

**Comment by Vinzent03** [comment]
@ddelange So your issue is that gitignore is working on desktop. So you are able to commit the "deleted" workspace file. But when pulling that commit on mobile, you get a merge conflict because the workspace file has changed. May you try to discard the workspace changes on mobile and then pull?

**Comment by ddelange** [comment]
Thanks @Vinzent03, I can confirm that the plugin does respect `.gitignore`! Fix was to:

- on mobile, disable auto pulling/pushing temporarily, close app
- on desktop, `git rm --cached .obsidian/workspace`, commit again and push
- on mobile, open command palette -> `Obsidian Git: Open source control view`
- click the minus next to the workspace file  (under changed files) to discard the changes
- pull the removal commit, this time without conflicts
- enable auto pull/push again, all good! :tada:

**Comment by Vinzent03** [comment]
Great! Things are always a bit more complicated if you can only use the gui.

**Comment by ddelange** [comment]
on a similar note, it seems mobile and desktop are fighting over this one
```diff
--- a/.obsidian/plugins/obsidian-git/data.json
+++ b/.obsidian/plugins/obsidian-git/data.json
@@ -21,6 +21,6 @@
   "differentIntervalCommitAndPush": false,
   "changedFilesInStatusBar": false,
   "username": "__token__",
-  "showedMobileNotice": false,
+  "showedMobileNotice": true,
   "refreshSourceControlTimer": 7000
 }
```

**Comment by Vinzent03** [comment]
Did you correctly pull the `true` value on mobile? Does the mobile plugin change the `true` value to `false` by itself?

**Comment by ddelange** [comment]
sounds like it: desktop is committing&pushing `true`, mobile is committing&pushing `false`

**Comment by Vinzent03** [comment]
You may have to first commit the `false` on mobile and the `true` on desktop, and then just pull on mobile. Close Obsidian on mobile and reopen. I think the issue is that the `false` is still cached in the running obsidian-git plugin instance. And writes its cached settings to the disk, ignoring the previously pulled value.

**Comment by ddelange** [comment]
closed obsidian on android, manually edited data.json to `true`, started app, app pulled commit with `true` from desktop, no pushes with `false` coming from mobile as of yet 🎉
