### ISSUE TITLE
How do I know the last commit time and message? 

### ISSUE THREAD

**Issue by qiaoxingxing** [denolehov/obsidian-git#334]
Every morning at the office , I need to check the last commit time to confirm I haven't forgotten to commit and push at home last night. 

I have to open a terminal and type "git log". How can I do it within obsidian?

**Comment by Vinzent03** [comment]
When you pull in Obsidian, you should get a notice of the changed files count. This could help you to determine whether you have new changes or not. But this does not tell you the date of the last commit.

**Comment by qiaoxingxing** [comment]
@Vinzent03 
It helps,

**Comment by qiaoxingxing** [comment]
Finally, I find a way to do this by using plugins Templater and Hotkeys for templates.
1. define a new system command in templater.
```md
name: gitlog 
cmd: git log --pretty=format:'%s' -5
```
2. add a template file git-log.md
```md
<%_* 
const msgs = await tp.user.gitlog()
const array = msgs.split("\n")
//show a model listing latest commits
await tp.system.suggester(array,array)
//to avoid lost data
tR += tp.file.selection();
_%>
```
3. add hotkey for this template in setting

**Comment by Vinzent03** [comment]
That's great! I'm still thinking about a good way to maybe show that in Obsidian as well. Maybe another statusbar entry?

**Comment by mkczyk** [comment]
>  I'm still thinking about a good way to maybe show that in Obsidian as well. 

Maybe just "git log" in Obsidian Git like in [this feature request](https://github.com/denolehov/obsidian-git/issues/472)?

For those who still looking for solution (and don't want to use Templater for some reasons), you can use plugins Shell Command + Commander and put icon with your command for example `gitk`. With this you can quickly see last commit time and message (see Workaround section for details: https://github.com/denolehov/obsidian-git/issues/472).
