### ISSUE TITLE
[Bug]: TypeError: Promise.allSettled is not a function. (In 'Promise.allSettled(promises)'; Promise.allSettled is not defined) 

### ISSUE THREAD

**Issue by quacau** [denolehov/obsidian-git#337]
```
TypeError: Promise.allSettled is not a function. (In 'Promise.allSettled(promises)'; Promise.allSettled is not defined) 
```

I'm on iOS 12.5.5 (iPhone 6). Plugin version: 2.5.1

**Comment by Vinzent03** [comment]
I have no idea where that error occurs, and I'm not using `Promise.allSettled()` myself. Please use the provided template and describe what you are doing.

**Comment by quacau** [comment]
Sorry. At that time I haven't figured out the MRE yet. Here it is:

Here are my steps:

1. Create a new vault & install Obsidian Git
2. Make a dummy edit 
3. Commit
4. This bug happens

I have only test on iOS 12.5.5 (iPhone 6)

**Comment by Vinzent03** [comment]
I don't have an iPhone, but I can't reproduce on android. The error message doesn't help me either, so I have no way no fix this. Sorry.

**Comment by ooker777** [comment]
Do you think it's better to tag this issue with an iPhone tag so people can easily find it and help?

**Comment by mikegr** [comment]
I get the same error in the  Android app on a Chromebook. It happens when I want to stage my changes. Initializing the repo works without any issue. I cannot create or switch branches.

**Comment by huettner94** [comment]
I had the same issue on android. It is caused for me by an old version of the android webview component that does not yet know about the `Promise.allSettled`. The function is used in the git library used in this project https://github.com/isomorphic-git/isomorphic-git/blob/328fbba5d2eb8c17093786c2594001d3a109252a/src/api/add.js#L96.

Maybe updating android webview might help future readers, but it did not help me. However i build a ugly hack to make it work on all devices needing it:

1. Install and enable the `Dataview` community plugin
2. In the plugin settings enable javascript queries
3. Add a new note (or put it in one you have always open) and paste the following
```javascript
```dataviewjs
if (!Promise.allSettled) {
  Promise.allSettled = promises =>
    Promise.all(
      promises.map((promise, i) =>
        promise
          .then(value => ({
            status: "fulfilled",
            value,
          }))
          .catch(reason => ({
            status: "rejected",
            reason,
          }))
      )
    );
}
```
```

(Snippet taken from here https://stackoverflow.com/a/66673057)

Now you just need to open this note once before you want to commit your changes and it will patch the missing javascript method. For newer versions already having the javascript method it will do nothing

**Comment by anglinb** [comment]
Wow, what an insane hack! It totally works though. Got Obsidian running and syncing with git on my Quest 2

**Comment by testpass1982** [comment]
@huettner94 thank you very much! work like a charm on my old iphone 6
