### ISSUE TITLE
[Bug]: Checkout progress again and again, makes obsidian mobile cannot work well

### ISSUE THREAD

**Issue by Lynx3x** [denolehov/obsidian-git#338]
### Describe the bug

I just update the obsidian-git plugin to latest, and when I using on mobile, it will hint "Checkout progress: Analyzing workdir: xxxx". Seem like scanning something, but do this over and over again. I don't know why it happened. When scanning, I cannot search or open markdown file. It won't give the result until the checkout stopped.

### Steps to reproduce

1. Start Obsidian APP

### Operating system

Android

### Plugin version

2.4.1

**Comment by Vinzent03** [comment]
Do you have auto backup turned on? It might try to commit everything. The interval might be very low.

**Comment by conql** [comment]
Same issue in mobile. Checkout progress shows every time I try to pull. Taking roughly 30 secs which makes it impossible to use. Auto backups are disabled.

**Comment by Vinzent03** [comment]
I don't think that's fixable. See the added warning in the [documentation](https://publish.obsidian.md/git-doc/Getting+Started#Performance+on+mobile)
