### ISSUE TITLE
[Bug]: cannot authenticate in chrome os

### ISSUE THREAD

**Issue by twsau** [denolehov/obsidian-git#341]
### Describe the bug

I am not able to authenticate git when running in crostini on chrome os. Crostini itself has ssh setup and I am able to manually commit via crostini, but not using `obsidian-git`. Tested on appImage, .deb and flatpak

![image](https://user-images.githubusercontent.com/46389844/196186600-7fc3385f-7f91-4bb4-8e0e-16b7a512753b.png)

### Steps to reproduce

Install obsidian via flatpak, appImage or .deb on ChromeOS crostini. Attempt to backup / commit your vault.

### Expected Behavior

Obsidian authenticates via the ssh keys defined in crostini and commits the vault to the remote repository

### Operating system

Linux

### Plugin version

2.6.0

**Comment by Vinzent03** [comment]
I guess your ssh key has a passphrase, but since Obsidian can't ask you the passphrase, the auth fails. A solution is to remove the passphrase.

**Comment by twsau** [comment]
@Vinzent03 Thank you for your suggestion. Unfortunately, ssh key has no passphrase so this cannot be the cause

**Comment by twsau** [comment]
update: this was fixed by properly configuring ssh for Crostini. Useful guide [here](https://gist.github.com/parsley42/f1871360204bb55c3d69f10ec05f5cee)...

Thanks for your time! Closing now :)
