### ISSUE TITLE
Encrypt local storage

### ISSUE THREAD

**Issue by Arminius4** [denolehov/obsidian-git#345]
Is the local storage encrypted? At a first glance, I couldn't find evidence for this. 
Therefore, do I rightfully assume that the local storage gets saved in plain format?

If so, I would rather have the local storage encrypted, because it contains sensitive info, such as the password.

**Comment by Vinzent03** [comment]
I don't know for sure, but I don't think the local storage is encrypted. I couldn't find a better solution to store the password on mobile.
