### ISSUE TITLE
[Bug]: Cannot push commits: "Obsidian Git did not send all necessary objects" (push works through terminal)

### ISSUE THREAD

**Issue by MinaAlmasi** [denolehov/obsidian-git#347]
### Describe the bug

Hi :)

I suddenly cannot push commits through Obsidian git anymore after having used it since 2021 with no problems. It still makes commits, but it won't push them - I get exactly the same error message every time (see next box). I had 52 commits at some point that the plugin had not pushed. I can push through the terminal with absolutely no problem.

The error message seems to indicate that I have several branches open (main 2), but I only have one branch which is called main. 

Thanks in advance!

### Relevant errors (if available)

```shell
fatal: bad object rets/remotes/origin/main 2
error: httos://github.com/MinaAlmasi/reponame-
Obsidian.git did not send all necessary objects
```

### Steps to reproduce

1. I use the command "create backup" 
2. I see the message "X files committed" 
3. I get the error message immediately after (the error message does not change at all)

### Addition context

I have the latest version of Obsidian (version 1.0.0) but the issue was also prevalent on version 0.15.9

### Operating system

macOS

### Plugin version

2.8.0

**Comment by josephdong1000** [comment]
I had the same issue but it seems to have gone away in 2.9.0, although I haven't tested it rigorously yet

**Comment by josephdong1000** [comment]
After some more digging, it seems like the problem arises when there are extra branches in `.git/refs/remote/origin/`. I took a peek and found an extra `main 2` that was created yesterday (around when the problems began arising). Deleting that fixed the issue for me.

I got my info from here:
https://stackoverflow.com/questions/8788975/bitbucket-git-error-did-not-send-all-necessary-objects/70957667#70957667

**Comment by MinaAlmasi** [comment]
Thank you!!! Deleting main 2 worked !!!

**Comment by Vinzent03** [comment]
Hm that's strange. Where did that branch come from? Maybe from another sync service? I'm closing this now as it seems solved for you.

**Comment by MinaAlmasi** [comment]
I have no other sync device or anything. The branch did not appear when writing git branch -r and I could not remove it with git rm (nor with git symbolic-ref -d). Was able to find it with git prune and remove it by writing git prune origin. But everything works now! Thank you!

**Comment by josephdong1000** [comment]
@Vinzent03 I'm using Obsidian Git concurrently with iCloud (probably a bad idea, but I like having backup systems). I'm guessing iCloud saw 2 different mains and decided to add in an extra one. The weird thing is that I don't recall pulling from my repo, so I'm not sure exactly what's going on.
