### ISSUE TITLE
[Bug]: Sync with Git (Gitea) on iPad 15.7

### ISSUE THREAD

**Issue by thinkORo** [denolehov/obsidian-git#349]
### Describe the bug

By using "Obsidian Git: Clone an exisiting remote repo" I get the following error:

"RangeError: Out of memory".

### Relevant errors (if available)

```shell
"RangeError: Out of memory".
```

### Steps to reproduce

1. Install Obsidian Git
2. Configure Obsidian Git (User, Password)
3. Select "Obsidian Git: Clone an exisiting remote repo" from command list
4. Insert respective URL and confirm mentioned questions

### Expected Behavior

The repo should be cloned.

### Addition context

Number of folders in this vault: 120
Number of files in these folders: about 650
Size: ca. 85MB (because of some images (png))

### Operating system

iOS

### Plugin version

2.8

**Comment by Vinzent03** [comment]
I'm sorry it doesn't work for you, but I don't know how to fix this. Your repo seems too big for the underlying library to handle on your device. Related to #307
