### ISSUE TITLE
[Bug]: Git is not ready even when I can still use it in terminal

### ISSUE THREAD

**Issue by ooker777** [denolehov/obsidian-git#356]
After I run these commands
```git
git config --global core.quotePath false
git config --system core.longpaths true
```
Suddenly the plugin doesn't recognize the repo anymore. Do you have any idea?

I'm on Windows, plugin version 2.8.0

**Comment by Vinzent03** [comment]
I'm running `git rev-parse --is-inside-work-tree` to check for a valid repo. May you try it in the terminal?

**Comment by ooker777** [comment]
it returns true. But the plugin still can't recognize it

**Comment by Vinzent03** [comment]
That's strange. May you share your custom base path plugin setting? It should be empty/correct.

**Comment by shivenigma** [comment]
I have this same issue, and the command `git rev-parse --is-inside-work-tree` returns true as well and my path is empty.

**Comment by Vinzent03** [comment]
@shivenigma  Are there any errors in the console (`CTRL+SHIFT+I`)?
