### ISSUE TITLE
GIT history breaks each time a file is moved or renamed

### ISSUE THREAD

**Issue by alanalvarado** [denolehov/obsidian-git#362]
Whenever I rename a folder or move it creates a gazillion GIT deletes and adds them as new files, therefore the history for those files gets broken or lost.
Then the plugin says it can't show or stage anything because there are too many changes.

Can the Obsidian delete/move action be intercepted and replaced with git mv?

Thanks in advance.

**Comment by Vinzent03** [comment]
You have to stage the files. Then will Git detect the renaming. `git mv` is the same as a staged `mv`

**Comment by Vinzent03** [comment]
Closing because of no response. Just comment if you have still problems, and I'm open to reopen the issue.
