### ISSUE TITLE
[Bug]: ios can’t pull

### ISSUE THREAD

**Issue by MrChiu** [denolehov/obsidian-git#364]
### Describe the bug

ios mobile can’t pull from git, it makes obsidian restart when pulling。The version is v2.9.2。

### Steps to reproduce

。

### Operating system

iOS

### Plugin version

2.9.2

**Comment by Vinzent03** [comment]
Should be fixed in 2.9.3

**Comment by MrChiu** [comment]
> Should be fixed in 2.9.3

thanks 👍🏻👍🏻

**Comment by MrChiu** [comment]
> Should be fixed in 2.9.3

I have updated it to 2.9.3, but the problem is also exist . You try it？😂

**Comment by Vinzent03** [comment]
Did it work for you in 2.9.1?

**Comment by MrChiu** [comment]
> Did it work for you in prior 2.9.2?

In 2.9.1 there is no problem. It has not worked since it was updated to 2.9.2 this morning.

**Comment by MrChiu** [comment]
![a0c8484a-15df-4004-bd19-ee8b40f03174](https://user-images.githubusercontent.com/9016391/199679857-64c8e126-6c13-4640-81e1-0fb45a01149f.jpg)
![a5aa512f-992a-4b84-aaf8-a7eb69386ccd](https://user-images.githubusercontent.com/9016391/199679865-0eddfc59-b6a4-42bd-9903-ed48ede3614b.jpg)

there are screenshots. 1st is pulling, 2nd is obsidian restart.

**Comment by MrChiu** [comment]
> Did it work for you in prior 2.9.2?

It is no problem now, I pull it success on macos, then ios is OK. Maybe iCloud or something make it throw exception?
