### ISSUE TITLE
[Bug]: Can't push from obsidian. (fatal: could not read Username for 'https://github.com': No such device or address)

### ISSUE THREAD

**Issue by Metal-Toilet** [denolehov/obsidian-git#367]
### Describe the bug

When pushing my changes in obsidian to github remote I get the error below. However when I do git push in the terminal (within the obsidian folder) it asks me for my username (same on git and github) and a password. The password is a Fine-grained token as github doesn't support passwords anymore. After entering both in it sucessfully pushes to gh.

### Relevant errors (if available)

```shell
ncaught (in promise) Error: Pushing to https://github.com/Metal-Toilet/obsidian-vault.git
fatal: could not read Username for 'https://github.com': No such device or address

    at Object.action (plugin:obsidian-git:23937:25)
    at PluginStore.exec (plugin:obsidian-git:23962:25)
    at eval (plugin:obsidian-git:21549:43)
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (plugin:obsidian-git:21547:16)
    at GitExecutorChain.eval (plugin:obsidian-git:21531:44)
    at Generator.next (<anonymous>)
    at fulfilled (plugin:obsidian-git:20380:24)
```

### Steps to reproduce

Setup remote git repo to github. In obsidian (with obsidian git) commit, and push.

### Expected Behavior

Obsidian Git pushes to my github repo.

### Addition context

Fresh install of Fedora 37 and obsidian.

### Operating system

Linux

### Plugin version

I'm not sure how to find this out

**Comment by hansiebo** [comment]
My issue might be related:

https://github.com/denolehov/obsidian-git/issues/369

**Comment by Metal-Toilet** [comment]
@hansiebo It seems like it is. I think it may have something to do with personal acess tokens being used because github doesn't allow passwords anymore. Did you set yours up that way?

**Comment by hansiebo** [comment]
Yes, via personal access token. Like you said, GitHub doesn't allow password anymore.

I wonder how that might affect Obsidian Git. 
It seems to be an issue with authentication, however, Obsidian Git never asked me to authenticate anything. And there is also nothing in the settings (if i am not mistaken).

**Comment by Metal-Toilet** [comment]
I wonder why it seems like its only affecting us?

**Comment by Metal-Toilet** [comment]
I solved this issue by setting up github+git with an ssh key.

**Comment by kematzy** [comment]
For Googlers wondering how to fix this issue.  See: https://github.com/denolehov/obsidian-git/issues/369#issuecomment-1378281435 for a possible solution.
