### ISSUE TITLE
[Bug]: iOS Obsidian.md app crashes when cloning repo

### ISSUE THREAD

**Issue by TheJasonPlayz** [denolehov/obsidian-git#373]
### Describe the bug

I start with a clean vault. I install the plugin with no options changed, and run the Clone Repository command. I enter my command URL, click Vault Root. I click Yes to having a .obsidian dir in the repo, and I click DELETE ALL LOCAL CONFIG AND PLUGINS. I enter my credentials and wait for the Cloning Repo notification to go away. Suddenly, my Obsidian.md app crashes. I have tried reinstalling the entire app multiple times, and nothing works. Can I have some help please?
Thank you,
Jason

### Steps to reproduce

1. Start with a clean vault
2. Install plugin with no options changed
3. Enter "Clone Repository" command
4. Click "Vault Root"
5. Click "Yes" to having a .obsidian dir in remote repo.
6. Click "DELETE ALL LOCAL CONFIG AND PLUGINS"
7. Enter credentials after it says there are none

### Expected Behavior

1. Start with a clean vault
2. Install plugin with no options changed
3. Enter "Clone Repository" command
4. Click "Vault Root"
5. Click "Yes" to having a .obsidian dir in remote repo.
6. Click "DELETE ALL LOCAL CONFIG AND PLUGINS"
7. Enter credentials after it says there are none
8. Repo clones and I can continue with pushing, pulling, etc.

### Operating system

iOS

### Plugin version

2.9.4

**Comment by Vinzent03** [comment]
I'm very sure, same reason as #349
