### ISSUE TITLE
Feature Request: Enable multiple Repositories

### ISSUE THREAD

**Issue by fea17e86** [denolehov/obsidian-git#376]
## Why?

Sometimes the notes can't all exist within a single repository. Think of architecture documentation for a system, that is spread over multiple products/repositories. I can still create an Obsidian vault that spans the local versions of those repositories and therefore enables referencing beyond repository borders. But I can't manage that with Obsidian Git.

## What would be nice

Obsidian Git could scan the vault for sub dirs, which are git reposiories and list them in the Source View. The current functionality would then be made available for each repository. Shortcut scripts like `backup` could be executed for all repositories at "the same time".

I would love this! :)

**Comment by Vinzent03** [comment]
I think this feature needs some huge refactoring, so I expect this feature to take a long time.

**Comment by fea17e86** [comment]
Okay, sad though. 🙂
