### ISSUE TITLE
[FR] Diff View to open & focus new tab if current tab pinned

### ISSUE THREAD

**Issue by huyz** [denolehov/obsidian-git#377]
When I open "Diff View" via command palette or shortcut, the behavior is a bit inconsistent.
On a regular tab, the diff view opens in the current tab.
If the tab is pinned, then the diff view opens in the first non-pinned tab it can find (and doesn't focus the view).

It would be nice if when the current tab is pinned, the "Diff View" opened in a brand new tab and changed focus to it.

**Comment by Vinzent03** [comment]
I'm using the default Obsidian behavior with reusing an existing tab, when the current tab is pinned. So I won't change that for now. But I fixed the focus when using the command instead of the source control view.

**Comment by huyz** [comment]
Cool, thanks.

I will point out that the default Obsidian behavior is not good either (they do make a lot of UX mistakes). I will file a FR with core Obsidian for that.

**Comment by Vinzent03** [comment]
You can use ctrl click in the source control view. At the moment, I don't plan to add an extra command for this.
