### ISSUE TITLE
[Bug]: UI freeze when run.

### ISSUE THREAD

**Issue by Toxblh** [denolehov/obsidian-git#378]
### Describe the bug

UI freeze if open any another editor with the same folder/file. 
Sometimes need to use vscode (part of code, or resolve conflicts) and in the case obsidian fully freeze with error message in console (below present). 
Looks like need to catch state if git is locked right now, and skip/delay/wait to do some work.

For me is reproduced in mac and linux as well.

### Relevant errors (if available)

#69

### Steps to reproduce

Open VSCode with enabled auto-check git with the same folder as obsidian vault at the same time.
Change any file in Obsidian
Wait a collision `git status`(vscode) vs `git commit`(obsidian)

### Expected Behavior

No any freezes.

### Addition context

```shell
git obsidian error: fatal: Unable to create '/Users/toxblh/obsidian/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
```

```shell
Uncaught (in promise) Error: fatal: Unable to create '/Users/toxblh/obsidian/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.

    at Object.action (plugin:obsidian-git:23964:25)
    at PluginStore.exec (plugin:obsidian-git:23989:25)
    at eval (plugin:obsidian-git:21550:43)
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (plugin:obsidian-git:21548:16)
    at GitExecutorChain.eval (plugin:obsidian-git:21532:44)
    at Generator.next (<anonymous>)
    at fulfilled (plugin:obsidian-git:20381:24)
```

### Operating system

macOS

### Plugin version

2.10.1

**Comment by Vinzent03** [comment]
Do you have the issue on every commit? I can't reproduce on linux.

**Comment by Toxblh** [comment]
No, It's only when happen git status in vscode (do it sometimes) and obsidian try pull/push new changes. 
I just received maybe 3-4 times in a day.

**Comment by Toxblh** [comment]
Main point why I wrote here and think git-plugin is root cause. I received notification with some git related message immediately after unfreeze.

**Comment by Toxblh** [comment]
From performance profiling, I saw before/at the same time of freeze it start to work "Create Backup" function

**Comment by Toxblh** [comment]
Next callStack is appeared only after close the task 
<img width="977" alt="image" src="https://user-images.githubusercontent.com/2198153/205291449-ea1e1a56-2155-4be6-b5fe-6d9816ac0551.png">
