### ISSUE TITLE
Resoving Conflicts in repo

### ISSUE THREAD

**Issue by dariuszkowalski-com** [denolehov/obsidian-git#38]
It would be fantastic to implement a way to manage conflicts in the repo. Now,  when I am using a vault on two computers sometimes I need to resolve each conflict manually by the console.

The solution could be done by adding the possibility lu launch an external tool to do this.

**Comment by Vinzent03** [comment]
Why do you need the console? Because you want to find the conflict files? Because if you resolve the conflicts. A commit with the plugin should work then.
