### ISSUE TITLE
[Bug]: Error: "Precomosed unicode is not supported"

### ISSUE THREAD

**Issue by agfaur** [denolehov/obsidian-git#382]
### Describe the bug

The following error occurs when starting Obsidian or running **any** command such as e.g. Git: Pull, or Git: List changes.

```
git obsidian error: fatal: iconv_open(UTF-8,UTF-8-MAC) failed, but needed:
    precomposed unicode is not supported.
    If you want to use decomposed unicode, run
    "git config core.precomposeunicode false"
```

and the command stops. Meaning I cannot execute anything. 

### Steps to reproduce

In my case:
- macOS 13.0.1 - Apple Chip
- CL Tools for Xcode installed
- git version 2.37.1 (Apple Git-137.1)

Have a repo with manual version control tracking from the CLI. Install osbidian-git. Execute any command.
DISCLAIMER: I can only successfully run the command "Git: edit .gitignore".

### Operating system

macOS

### Plugin version

2.10.2

**Comment by Vinzent03** [comment]
Can you run `git status` on the terminal without issues?

**Comment by agfaur** [comment]
Yes I can. However, I realized the following. Whenever I start my terminal, a conda virtual env starts immediately -- which I use for work --, in my conda venv there is also git installed. So effectively there are two git binaries in my computer. I would imagine that obsidian-git goes to the default one installed via the CL Tools. I will, however, force obsidian git to look for that binary by providing the path and see what happens.

**Comment by agfaur** [comment]
The problem has been solved by explicitly providing the plugin with the path to the "correct" git binary. 

I hope this helps any future user facing a similar error.
Thanks for the quick reply!
