### ISSUE TITLE
[Bug]: Can't find a valid repository 

### ISSUE THREAD

**Issue by pcuellar** [denolehov/obsidian-git#386]
### Describe the bug

Upon updating to 2.12.0, the plugin began showing this error
<img width="332" alt="Screenshot 2022-11-28 at 6 56 17 AM" src="https://user-images.githubusercontent.com/20482146/204152614-d0ff4f43-1b05-4c9f-b148-8ccef615e1ff.png">
I rolled back to 2.11.0 and things are working fine. 

### Steps to reproduce

Update to 2.12.0

### Operating system

macOS

### Plugin version

2.12.0

**Comment by saku123hh** [comment]
I have the same bug..

**Comment by Vinzent03** [comment]
@saku123hh Please create a new issue since this one is very old and already solved. Did you try to create a new repository or clone an existing one?
