### ISSUE TITLE
[Bug]: SSH doesn't work anymore

### ISSUE THREAD

**Issue by davidkopp** [denolehov/obsidian-git#387]
### Describe the bug

Upon updating to 2.12.0, the following error occurs

```
UnknownTransportError: Git remote "git@github.com:davidkopp/notes.git" uses an unrecognized transport protocol: "ssh"
```

I rolled back to 2.11.0 and everything works again.

### Steps to reproduce

Update to 2.12.0 and use a Git repository with SSH

### Operating system

Windows

### Plugin version

2.12.0

**Comment by sammorley-short** [comment]
@Vinzent03 I’m still seeing this issue when trying to push and pull on iOS. Any idea if it’s related?

**Comment by Vinzent03** [comment]
You are using the wrong remote url. You have to use the https one. ssh in not supported on mobile.

**Comment by sammorley-short** [comment]
That sorted it! Thanks!
