### ISSUE TITLE
[Bug]: cloning remote repo: authentification failed

### ISSUE THREAD

**Issue by m-beau** [denolehov/obsidian-git#390]
### Describe the bug

I do not manage to clone a remote repo as my authentication fails, despite using a freshly generated personal access token.

### Steps to reproduce

- open obsidian app on iOS
- create local vault
- add your github usermail and your github personal token in the plugin settings
- run the command 'clone remote repo'
-> authentication fails. Then try to re-fill in the username and token when prompted: keeps failing.

### Expected Behavior

The repo should be successfully cloned.

### Operating system

iOS

### Plugin version

2.12.1

**Comment by m-beau** [comment]
Sure - it is a private repo, https://www.github.com/m-beau/Zettel

Thanks!

**Comment by Vinzent03** [comment]
This is wrong. It has to be of type https://github.com/username/reponame.git

**Comment by m-beau** [comment]
Oh cheers! Then feature suggestion: add some kind of url parser which flexibly accepts alternative formattings (with/out www, http/https, with/out the http:// part, with/out the .git) or add the required format in the documentation.

Thanks a lot!

**Comment by Vinzent03** [comment]
I've added it to the mobile installation in the wiki. I expect users to be already familiar with git. That's why I don't document everything.
