### ISSUE TITLE
[Bug]: about 'Preview commit message '

### ISSUE THREAD

**Issue by L-Super** [denolehov/obsidian-git#394]
### Describe the bug

when I add `{{hostname}}`, I want to preview message, so clicked  preview button, but the preview message didn't update.

### Steps to reproduce

1. add {{hostname}}
2. clicked preview button

### Operating system

Windows

### Plugin version

2.12.1

**Comment by Vinzent03** [comment]
Where exactly did you add `{{hostname}}`?

**Comment by L-Super** [comment]
here
![image](https://user-images.githubusercontent.com/40905056/205547168-c2c26805-38ac-4672-b81c-4f0004ed1eb7.png)

**Comment by Vinzent03** [comment]
As you can see the preview button is under the commit message heading. It previews the commit message template and not the one for auto backup.

**Comment by Vinzent03** [comment]
As you can see the preview button is under the commit message heading. It previews the manual commit message and not the one for auto backup. I need to move the setting for manual commit to the second heading.
