### ISSUE TITLE
What protocol to use on android?

### ISSUE THREAD

**Issue by richardeakin** [denolehov/obsidian-git#398]
Hi,

What protocols have people had success with on android, particularly when storing notes in a github repo? Github won't let us use HTTPS anymore and SSH doesn't appear to be supported with isomorphic-git, so what are the options?

Thanks,
Rich

**Comment by Vinzent03** [comment]
Why shouldn't GitHub support
https? That's the way to go.

**Comment by richardeakin** [comment]
Okay thanks for the tip, I followed some directions I found on the forum a little closer and noticed they are using `gh` to login from termux - worked for me too! 👍
