### ISSUE TITLE
Using rebase optoin

### ISSUE THREAD

**Issue by danraymond** [denolehov/obsidian-git#399]
Hi, fabulous plugin!!

I use Obsidian syncing between two laptops and a private git server (OneDev) to sync between the 2 laptops.This mostly works great but  I commonly get conflicts on a few files in the .obsidian directory. particularly apps.json. data.json and some others. 

This is no biggy, as I can do git commands to fix it at the Git command line level, but I am thinking if there was an option to use the rebase command as part of the pull/push command then maybe these could be avoided as its really just syncing between the laptops.

Any thoughts??

**Comment by Vinzent03** [comment]
I don't think using rebase prevents merge conflicts, but you can try using rebase as merge strategie in the settings. Best way is probably to ignore these files per .gitignore.

**Comment by danraymond** [comment]
Thank you. I might  try the rebase option first. I didn't realize it was an option (bad me!)
