### ISSUE TITLE
Attempting to push when the remote is ahead of the local branch causes odd behaviour

### ISSUE THREAD

**Issue by jamiebrynes7** [denolehov/obsidian-git#4]
### Actual behaviour

If your remote branch is ahead of your local branch and you attempt to push, the status bar indicates `git: pushing changes` until the next operation. 

An error is logged to the console, but this isn't surfaced to the user.

### Expected behaviour

A notice which indicates the operation failed and the status bar reflects this too.

**Comment by denolehov** [comment]
In [v1.4.0](https://github.com/denolehov/obsidian-git/releases/tag/1.4.0) all the messages (including error ones) are being displayed in status bar.
