### ISSUE TITLE
Help: Error on startup, please help out

### ISSUE THREAD

**Issue by dummifiedme** [denolehov/obsidian-git#40]
![image](https://user-images.githubusercontent.com/68785729/104843400-77c92b80-58f0-11eb-8c38-441315160234.png)

**Comment by JoshKing56** [comment]
There's a lock file that was created by some application. I would try these steps:
1. Save all of your work
2. Close any other application that uses git
3. Remove that lock file (.git/refs/remotes/origin/main.lock)

**Comment by Vinzent03** [comment]
@dummifiedme Did that help?

**Comment by Vinzent03** [comment]
Closing because of no response.
