### ISSUE TITLE
[Bug]: Unable to fetch/push changes from Obsidian Git Plugin

### ISSUE THREAD

**Issue by g33kyshivam** [denolehov/obsidian-git#416]
### Describe the bug

```
SYSTEM INFO:
	Obsidian version: v1.1.9
	Installer version: v1.1.9
	Operating system: Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:22 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T6000 21.6.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Spectrum
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Obsidian Git v2.14.0
```
Access/Push to the repo works fine. 
![image](https://user-images.githubusercontent.com/24518185/211047246-e912fde5-c066-49bf-9e55-9a0791a9b233.png)

But it seems like plugin is unable to authenticate. 
![image](https://user-images.githubusercontent.com/24518185/211047318-913bc4e9-b223-4183-9eae-0eeebce1372b.png)

### Relevant errors (if available)

```shell
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

### Steps to reproduce

1. Install plugin
2. Change internal to push changes. 
3. Edit file

### Operating system

macOS

### Plugin version

2.14.0

**Comment by g33kyshivam** [comment]
It's working fine

**Comment by SelinJodhani** [comment]
Please reopen this. Currently facing the same issue. I am using flatpak version of obsidian.

**Comment by gordonn** [comment]
![image](https://github.com/user-attachments/assets/bc98d820-d25e-4c21-8f40-be7836c063bc)

**Comment by Vinzent03** [comment]
@gordonn You are facing a different issue. It can't find the `ssh-askpass` bianry. Please open a new issue to debug your case.
