### ISSUE TITLE
[Feature request]: Quick way to reach the terminal

### ISSUE THREAD

**Issue by guo-yong-zhi** [denolehov/obsidian-git#418]
Sometimes I want to manage my repo directly with git command. So, can we have an integrated terminal or just a shortcut to open my repo with the system terminal?

**Comment by Zachatoo** [comment]
The below plugin may be better suited to handle this, rather than obsidian-git.

https://github.com/clevcode/obsidian-terminal-plugin

**Comment by Vinzent03** [comment]
Yeah, I think that's a better way to go. Additionally, in a quick research, I didn't see an easy way to implement that.
