### ISSUE TITLE
[Bug]: Doesn't allow the cursor to be moved to a new line

### ISSUE THREAD

**Issue by porobidev** [denolehov/obsidian-git#420]
### Describe the bug

It's the same issue **[as here](https://forum.obsidian.md/t/bug-the-cursor-is-not-moved-to-a-new-line/23862/1)**, but the thread got closed.

### Steps to reproduce

Enable Android's keyboard's option  **Text correction > Show correction suggestions**.
**Workaround**: disable it to fix the problem, but then you don't get word suggestions.

I'm using OpenBoard keyboard. I haven't tried other keyboards, but I believe it doesn't matter.

<details>
  <summary>Show GIF</summary>
<img src="https://forum.obsidian.md/uploads/default/original/3X/7/5/75e01e29144049e55013870e7e77be9a27a15170.gif" width="300">
</details>

### Addition context

<h2 id='devprops'>Device properties</h2>
<table class='block' id='tab_prodinfo'>
 <tr><th colspan='2' class='title'>Product Info</th></tr>
 <tr><th>Manufacturer:</th><td>motorola</td></tr>
 <tr><th>Model:</th><td>moto g(8) power (sofiar)</td></tr>
 <tr><th>Chipset:</th><td>qcom</td></tr>
 <tr><th>Platform:</th><td>trinket</td></tr>
 <tr><th>CPU:</th><td>arm64-v8a</td></tr>
 <tr><th>CPU compatibility:</th><td>arm64-v8a,armeabi-v7a,armeabi</td></tr>
 <tr><th>Screen density:</th><td>420</td></tr>
</table>

<table class='block' id='tab_osdetails'>
 <tr><th colspan='2' class='title'>OS details</th></tr>
 <tr><th>SDK/Android version:</th><td>30/11</td></tr>
 <tr><th>Fingerprint:</th><td>motorola/sofiar_reteu/sofiar 11/RPES31.Q4U-47-35-12/24aaf7 user/release-keys</td></tr>
 <tr><th>Kernel:</th><td>4.14.180-perf+</td></tr>
 <tr><th>Configured language:</th><td>en-US_</td></tr>
</table>

### Operating system

Android

### Plugin version

1.4.1 (83)

**Comment by Vinzent03** [comment]
I'm confused. What makes you think this plugin is responsible?

**Comment by Zachatoo** [comment]
The thread says that the issue happens with all community plugins disabled, this is likely not related to this plugin or any plugin.

**Comment by porobidev** [comment]
> I'm confused. What makes you think this plugin is responsible?

The keyboard works fine in any other app, so it should be a bug of Obsidian. The other(s) who reported the same bug in other places had different keyboard too.

> The thread says that the issue happens with all community plugins disabled, this is likely not related to this plugin or any plugin.

Yes, I don't have any community plugin enabled.

**Comment by Vinzent03** [comment]
This is NOT the repo for the source code of Obsidian. It's a plugin to manage a git repository in Obsidian. Use the forum for issues of Obsidian.
