### ISSUE TITLE
No Authentication Section in Settings

### ISSUE THREAD

**Issue by mpfp** [denolehov/obsidian-git#426]
I don't see an Authentication section in the Settings.  I'm on Windows and I have git installed and on the path (can use it on the command line).  Where do I put an authentication token or password?

![image](https://user-images.githubusercontent.com/50591136/213891574-d547e0a7-4f13-4d6f-9efe-a1ca112309d3.png)

**Comment by ajmazz** [comment]
Same. Macbook Air M1, OS Ventura 13.1

**Comment by FnigePython** [comment]
Same here. Linux, Fedora 37, Flathub

**Comment by kevinnmark** [comment]
+1
Macbook Pro
OS Big Sur 11.7.2
Obsidian v.1.1.9 (Installer 0.15.9)

**Comment by albinotonnina** [comment]
Same, OSX, Version 1.1.9 (Installer 1.1.9)

**Comment by sawasawasawa** [comment]
+1
Macbook Pro
OS Monterey 12.0

**Comment by r-menezes** [comment]
I had the following error:

```
git obsidian error: /usr/bin/gh auth git-credential get: line 1: /usr/bin/gh: No such file or directory
fatal: could not read Username for 'https://github.com': No such device or address
```

using the suggestion by @sawasawasawa  worked and I was able to commit, pull and push.

**Comment by mikes-bowden** [comment]
Lort, this was a 3-hour endeavor to find this. Why in the world is this not set by default?

Also, for anyone confused, the file @sawasawasawa mentioned, which did fix my issue, is located inside the /YOURVAULT/.obsidian/plugins/obsidian-git/main.js

Search for:

`this.gitManager = new SimpleGit(this);`

**Comment by Vinzent03** [comment]
@sawasawasawa I understand using isomorphic-git makes authentication a lot easier, BUT it's **way** slower and doesn't support all featuers, because it's a complete reimplementation of Git in javascript. For example is the merge conflict solver not as good as native git.

I tried to come up with the most general solution as possible, without having to install too much packages or write many config. I summarized it [here](https://github.com/denolehov/obsidian-git/wiki/Authentication). May you try it out and tell me how it's working? I can't test it on all operating systems. Especially not macOS.

**Comment by sawasawasawa** [comment]
@Vinzent03 Can't promise, but I will try to arrange some time for that on the weekend ;) Just to clarify - you want me to test the macOs part here https://github.com/denolehov/obsidian-git/wiki/Authentication#macos ?

Is your testing procedure described somewhere? I'd rather not mess too much with my main vault ;)

**Comment by Vinzent03** [comment]
@sawasawasawa I doesn't change anything in your vault. It changes a global git config, which doesn't affect your vault in any way currently, because you use isomorphic-git.

**Comment by sawasawasawa** [comment]
@Vinzent03 Ok I think I understand better now what was causing the confusion. 

2 weeks ago I initiated the vault on my mobile, connected it to the repo and afterwards created a new vault on desktop, and imported the vault using the plugin. After doing so when I reloaded obsidian some config from the mobile must have been used and it was missing the some data. 

I did it the other way round today:
1. Initiated a new repo on github
2. Wired it up with using obsidian git (**and here I can confirm that macOs keychain authentication indeed is working as expected**)
3. created a new vault on mobile
4. added obsidian git on mobile, configured using a PAT
5. cloned the vault to mobile - then I have to restart the application, and the PAT config disappears.

I am not sure if @mpfp @albinotonnina @kevinnmark @FnigePython @r-menezes @mikes-bowden were facing the same issue. Anyways it seems like the authentication procedure and iOs/OSX combination setup could be better described (and probably mentioned somehow in the settings). Having said that, and having solved my issues the hacky way - I am not sure how it should look like :P

**Comment by Vinzent03** [comment]
@sawasawasawa
> some config from the mobile must have been used and it was missing the some data.

Please be more specific, what exactly was the issue?

> then I have to restart the application, and the PAT config disappears.

Do you mean that the password field was empty? That's by design, it's still stored, but not shown.

I don't think it was necessary to create a new GitHub repository and vault, but great it's working now.

**Comment by lowercasename** [comment]
I'm experiencing this too. New vault created today, never used the plugin before.

**Comment by Vinzent03** [comment]
Please follow the [documentation](https://publish.obsidian.md/git-doc/03+Getting+Started#For+existing+remote+repository)
