### ISSUE TITLE
[Bug]: Diff doesn't work on iPad

### ISSUE THREAD

**Issue by robertandrews** [denolehov/obsidian-git#429]
### Describe the bug

When I click a changed file, the diff window opens, but it remains blank.
Title is Diff View but nothing happens. Also it locks up the window as "busy".
It did just eventually see it display "File without changes", which isn't accurate since I clicked a file with changes.

### Steps to reproduce

Click a changed file in the Source Control tree on iPad.

### Expected Behavior

Should show a diff of the changed file.

### Operating system

iOS

### Plugin version

2.16.0

**Comment by tamiroh** [comment]
According to my debugging, the issue seems to be caused by the error `NotFoundError: Could not find refs/heads/master.` in the following line.

https://github.com/denolehov/obsidian-git/blob/master/src/isomorphicGit.ts#L761

**Comment by tamiroh** [comment]
OK, I roughly found out how to fix it. I will submit a pull request later.
