### ISSUE TITLE
Commit -> pull -> push

### ISSUE THREAD

**Issue by dflock** [denolehov/obsidian-git#43]
I'm not sure what the current plugin does, but the only pull related setting is "Pull updated on startup". What would probably be better, would be to just do what people do manually, which is to always pull before pushing. So commit locally, pull, then push if OK.

**Comment by dflock** [comment]
Thanks!

**Comment by Vinzent03** [comment]
Is now available in the new [release](https://github.com/denolehov/obsidian-git/releases/tag/1.6.0)
