### ISSUE TITLE
[Bug]: can't use with git-crypt?

### ISSUE THREAD

**Issue by rxng** [denolehov/obsidian-git#434]
### Describe the bug

I have installed git-crypt and using it with my repo. it works perfect except for when doing so through obsidian-git, which gives the error below. 

I can't figure this out, because it seems that somehow obsidian-git cannot find the executable for git-crypt which is in /usr/bin/git-crypt

### Relevant errors (if available)

```shell
Uncaught (in promise) Error: "git-crypt" clean: line 1: git-crypt: command not found
error: external filter '"git-crypt" clean' failed 127
error: external filter '"git-crypt" clean' failed
fatal: .obsidian/plugins/obsidian-git/data.json: clean filter 'git-crypt' failed

    at Object.action (plugin:obsidian-git:23985:25)
    at PluginStore.exec (plugin:obsidian-git:24010:25)
    at eval (plugin:obsidian-git:21571:43)
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (plugin:obsidian-git:21569:16)
    at GitExecutorChain.eval (plugin:obsidian-git:21553:44)
    at Generator.next (<anonymous>)
    at fulfilled (plugin:obsidian-git:20402:24)
```

### Steps to reproduce

set up git-crypt successfully using the standard way. All working as expected using git pull or push with user commands.
e.g. in .git/config
[filter "git-crypt"]
        smudge = \"git-crypt\" smudge
        clean = \"git-crypt\" clean
        required = true
[diff "git-crypt"]
        textconv = \"git-crypt\" diff

Then, toggle on obsidian-git from within Obsidian plugins. It fails to find git-crypt. Even if I update the config with full path as /usr/bin/git-crypt 

### Expected Behavior

obsidian-git upon toggling should just be able to find git-crypt. or tell us how we can make use the system installed git and git-crypt?

Any help would be appreciated.

### Operating system

Linux

### Plugin version

2.16.0

**Comment by Vinzent03** [comment]
Have you Obsidian installed via flatpak?

**Comment by rxng** [comment]
@Vinzent03 nice one! yes that was indeed the issue. I used AppImage and it is fine. Except now everytime I save and obsidian-git auto backsup , it somehow pushes everything in plain text!

If I do git commit and then push on the terminal directly however, then it is encrypted. So it seems like for some reason obsidian-git auto backup will push to repo without doing any of the crypt process.

Yet, there are no errors in the console.

**Comment by Vinzent03** [comment]
I'm not familiar with git-crypt. For commit etc you use the standard git binary, but with the special config in .git/config ? The plugin should respect the config file.

**Comment by rxng** [comment]
@Vinzent03 thanks for your help. The setup works everywhere with git crypt.the only place it fails is on Android. Guess it's just the limitation for now

**Comment by Vinzent03** [comment]
Yeah it not gonna work on mobile, because there is no real git nor git-crypt installation on mobile.

**Comment by rxng** [comment]
@Vinzent03 FYI you can get git crypt on mobile. In fact. I did it through termux and.got it working.it just doesn't work if through obsidian git

**Comment by cooparo** [comment]
Yep, it's what I was searching about. Tnx u

**Comment by ashu-otaku** [comment]
> @Vinzent03 FYI you can get git crypt on mobile. In fact. I did it through termux and.got it working.it just doesn't work if through obsidian git

have you found any solution of how to run git-crypt through obsidian-git mobile ??
