### ISSUE TITLE
Is there docs on how to set up the plugin ?

### ISSUE THREAD

**Issue by xhw1** [denolehov/obsidian-git#44]
thanks

**Comment by finn-matti** [comment]
I'm asking myself the same. As it stands, at least the installation instructions are incomplete.

**Comment by ronnyandre** [comment]
Seems like it's missing...

**Comment by same-difference** [comment]
I followed this guide and after step 4 the settings panel for obsidian git appeared after restarting obsidian. Finished up the rest of the guide and its working nicely now: https://docs.github.com/en/github/importing-your-projects-to-github/adding-an-existing-project-to-github-using-the-command-line

**Comment by redstreet** [comment]
That worked, @same-difference, thanks.

**Comment by meefen** [comment]
> I followed this guide and after step 4 the settings panel for obsidian git appeared after restarting obsidian. Finished up the rest of the guide and its working nicely now: https://docs.github.com/en/github/importing-your-projects-to-github/adding-an-existing-project-to-github-using-the-command-line

Where is the setting panel please? I could not find it even after restarting Obsidian. thanks!

**Comment by same-difference** [comment]
> > I followed this guide and after step 4 the settings panel for obsidian git appeared after restarting obsidian. Finished up the rest of the guide and its working nicely now: https://docs.github.com/en/github/importing-your-projects-to-github/adding-an-existing-project-to-github-using-the-command-line
> 
> Where is the setting panel please? I could not find it even after restarting Obsidian. thanks!

The setting panel for obsidian git is very fickle. Make sure you have the plug in toggled on, then scroll through the options categories to see if it's there (edit, appearance, etc). If it's still not there, another help thread found that reinstalling git bash with "git from the command line and also from 3rd party software" helped

**Comment by Vinzent03** [comment]
Added better instructions, hope that helps in the future. https://github.com/denolehov/obsidian-git/commit/cb184a74a1ca1e37000440699357a4a537fa125e
