### ISSUE TITLE
[Bug]: Obisidan Git on Android hasn't ignored .obsidian folder

### ISSUE THREAD

**Issue by vutruong-dev** [denolehov/obsidian-git#440]
### Describe the bug

Hi, I have added .obsidian folder to .gitignore file but Obsidian Git still push the folder to the remote repo when creating backup.

Has anyone encountered this problem?

### Steps to reproduce

1. Add ".obsidian" to .gitignore file
2. Run "Create Backup" command

### Expected Behavior

Obsidian Git ignore .obsidian folder

### Operating system

Android

### Installation Method

None

### Plugin version

2.16.0

**Comment by Vinzent03** [comment]
Does it still commit changes or do you want the existing folder to be removed?

**Comment by carlos-gamedev** [comment]
I've fixed it by adding "/" at the end of the line. 
".obsidian" does not work but ".obsidian/" does work well.

**Comment by Vinzent03** [comment]
I tried to reproduce it, but when adding only `.obsidian` to .gitignore in a new initialized repo everything works as expected.
