### ISSUE TITLE
[Bug]: Security issue (Mobile)

### ISSUE THREAD

**Issue by hidegh** [denolehov/obsidian-git#441]
### Describe the bug

based on: https://github.com/denolehov/obsidian-git/wiki/Installation

Mobile

8. Under the "Authentication/Commit Author" section, fill in the username on your git server and your password/personal access token.

the commit then looks like this:
![image](https://user-images.githubusercontent.com/6331063/220753692-603b5086-765b-4087-9606-dc2500813898.png)

so there's a SECURITY LEAK, as when I do download the repo into a new folder, these details (so the private security key) will get also downloaded.

### Relevant errors (if available)

```shell
No errors, just security leak
```

### Steps to reproduce

Use a GIT tool like Fork. Other GIT tools also download these data, they just might not show it, but the security-related info is shared by every fork!

### Expected Behavior

Separate INPUT for private token authentication.

### Operating system

Windows

### Installation Method

None

### Plugin version

2.16.0

**Comment by Vinzent03** [comment]
Where exactly did you enter your personal access token?

**Comment by hidegh** [comment]
@Vinzent03 as it was written in the docs:
![image](https://user-images.githubusercontent.com/6331063/220954347-ae6eefbf-e8da-457d-84d8-fe889000ff2f.png)

**Comment by Vinzent03** [comment]
The text box clearly says "Author name", which has nothing to do with password for authentication. You re following the mobile installation guide, but you are on windows, right?

**Comment by hidegh** [comment]
Exactly, on windows, but authorizing via personal token is the easiest and most generic way, so...

**Comment by Vinzent03** [comment]
That is correct, but the guide won't work for you on desktop, because the guide is for mobile.

Please do an authentication command like pull, fetch, push in the terminal and set your username and PAT there. This should store them in Git Credential Helper.

**Comment by thesocialdev** [comment]
question: what about the use case for vaults being shared cross-device?

Although the documentation says it's not well supported, there should be a workaround on the commit messages and author when that's setup.

**Comment by Vinzent03** [comment]
The author details can be set your global git config. For different commit messages on different machine, you would have to use a different config folder in the obsidian settings for each device.

**Comment by thesocialdev** [comment]
> The author details can be set your global git config. For different commit messages on different machine, you would have to use a different config folder in the obsidian settings for each device.

I thought about that, wouldn't the commit messages still be leaked when using the mobile settings? If it isn't possible to mask the secrets in the commit message/author, a documentation with a warning about it is needed. What do you think?

**Comment by Vinzent03** [comment]
What secrets are you talking about?

**Comment by thesocialdev** [comment]
> What secrets are you talking about?

I'm referring to the github access token referred in this issue that's leaking in the git logs.

**Comment by Vinzent03** [comment]
I'm really confused now. Where did you set your github personal token and on which os?

**Comment by LightTemplar** [comment]
@thesocialdev, "If it isn't possible to mask the secrets in the commit message/author" - there are no secrets in commit messages, and is no need of them for plugin to work. Unless you set them in commit settings for whatever your reason. 
And exactly this was made by author of this issue by, actually, mistake, and not intentionally.

**Comment by thesocialdev** [comment]
I see now the confusion, the configuration UI renders different between mobile and desktop (macOS in my case) and I didn't see. Sorry for the disruption and thanks for the support!
