### ISSUE TITLE
Plugin will commit but not push on Windows

### ISSUE THREAD

**Issue by JoshKing56** [denolehov/obsidian-git#45]
I am trying to get the plugin to work on my windows machine, and can't seem to get it to push. The plugin will display the message "git obsidian: committed x files," and will print the same thing to the console:

![image](https://user-images.githubusercontent.com/19408926/106407316-bf2fdb80-6409-11eb-9653-d3a4c7f4a39d.png)

But when I check the git repo using the git cli, I find the following:
![image](https://user-images.githubusercontent.com/19408926/106407353-d53d9c00-6409-11eb-96c1-7b1ddf4aa0d8.png)
So clearly it's able to commit files, but isn't pushing. 
I have git set up with ssh so that there is no extra prompts or passwords required when using `git push`. So in the cli, if I type `git push`, I don't need to type anything else and it will push fine.

Any help would be appreicated!

**Comment by JoshKing56** [comment]
Apologies if this is a duplicate of #39, but in my case there is no error message. It looks like it succeeds, but just doesn't push.

**Comment by xinaesthete** [comment]
Works ok for me.

**Comment by same-difference** [comment]
> Apologies if this is a duplicate of #39, but in my case there is no error message. It looks like it succeeds, but just doesn't push.

Check your obsidian git settings. There's a setting that toggles automatic pushing

**Comment by JoshKing56** [comment]
@same-difference That was it! Somehow the "Disable push" setting was on. Thanks!
