### ISSUE TITLE
[Bug]: Repository not found

### ISSUE THREAD

**Issue by carloslab-ai** [denolehov/obsidian-git#451]
### Describe the bug

After update from 2.16.0 to 2.17.0 Obsidian git cannot find the remote repository.

### Steps to reproduce

1. Install 2.16.0
2. Clone any repo
3. Push anything to the repo
4. Update to 2.17.0
5. Pull or push any thing to the remote repo and Obsidian Git cannot find the remote repo now

### Operating system

Windows

### Installation Method

None

### Plugin version

2.17.0

**Comment by Vinzent03** [comment]
Please share any error you encounter or what exactly happens.

**Comment by carlos-gamedev** [comment]
This is the error I get after upgrading to 2.17.0

<img width="269" alt="image" src="https://user-images.githubusercontent.com/126215834/222689581-0a158639-f965-429c-8336-c4a1049f4dce.png">

**Comment by Vinzent03** [comment]
I can't reproduce that. Does it still work in the command line? Maybe your personal access token is expired?

**Comment by vutruong-dev** [comment]
I've reverted to 2.16.0 and it works so this error is not caused by the access token.

**Comment by carlos-gamedev** [comment]
I've reverted to 2.16.0 and it works so this error is not caused by the access token.

**Comment by Vinzent03** [comment]
Ah I think your repo url is wrong. Please remove the last `/`.  You can edit it via the edit remotes command.

**Comment by carlos-gamedev** [comment]
I've checked the file ".git/config" and run the command "git remote -v" and the url doesn't contain the last "/"

**Comment by vutruong-dev** [comment]
<img width="404" alt="image" src="https://user-images.githubusercontent.com/87231786/223362828-a37f45ea-dceb-4270-912a-7fd31907e762.png">

This is the error I get from the console.

Obsidian Git 2.17.2

**Comment by vutruong-dev** [comment]
I've fixed this by removing all github credentials from Credential Manager :D

**Comment by Vinzent03** [comment]
I'm unsure if this issue still persists. In case you encounter this, please open a new issue.
