### ISSUE TITLE
[Bug]: Git in Obsidian subfolder : the plugin try to add file external to this folder

### ISSUE THREAD

**Issue by Lisandra-dev** [denolehov/obsidian-git#457]
### Describe the bug

I tryed to install the obsidian-git plugin because I have a git subfolder. 
I changed the `.git` to add the `.git` subfolder in hard path lile : `K:\vault\folder\.git`

The plugin add multiple external file, like my .obsidian, assets... And block in a loop of adding one file. 

### Relevant errors (if available)

```shell
git : too many change to display
```

### Steps to reproduce

- Create a git folder in a vault 
- Configure the git plugin to this folder with hard path 
- See bug

### Expected Behavior

Commit & pull only file in this folder

### Operating system

Windows

### Installation Method

None

### Plugin version

2.17.4

**Comment by Vinzent03** [comment]
So your git repo is in a directory below your vault? Please use the "Custom base path" setting with a **relative** path to the vault.

**Comment by Lisandra-dev** [comment]
Same bug occurs with relative : Too many change to display. 

Note : I don't have anything in commit for the moment, and I exclude everything external to this repo using the gitignore : 
```
.obsidian/
*
!.gitignore
!Cataclysme/
!Civil/
!Légion/
!Sentinelle/
!Tableau des personnages
```
Normally, I can keep only the folder and file prepended by `!`

The bug `too many change to display` continue to occur :/

**Comment by Vinzent03** [comment]
May you share a screenshot of the advanced section in the settings?

**Comment by Lisandra-dev** [comment]
```json
{
  "commitMessage": "Update {{numFiles}} files:s",
  "commitDateFormat": "YYYY-MM-DD HH:mm:ss",
  "autoSaveInterval": 0,
  "autoPushInterval": 0,
  "autoPullInterval": 3,
  "autoPullOnBoot": true,
  "disablePush": true,
  "pullBeforePush": true,
  "disablePopups": false,
  "listChangedFilesInMessageBody": true,
  "showStatusBar": true,
  "updateSubmodules": false,
  "syncMethod": "merge",
  "customMessageOnAutoBackup": false,
  "autoBackupAfterFileChange": false,
  "treeStructure": true,
  "refreshSourceControl": true,
  "basePath": "",
  "differentIntervalCommitAndPush": false,
  "changedFilesInStatusBar": false,
  "showedMobileNotice": true,
  "refreshSourceControlTimer": 7000,
  "showBranchStatusBar": true,
  "setLastSaveToLastCommit": false,
  "submoduleRecurseCheckout": false,
  "gitDir": "10. PROJECT\\ETERNITY\\Wiki\\.git",
  "autoCommitMessage": "Update {{numFiles}} files:s"
}
```

**Comment by Lisandra-dev** [comment]
Trying
