### ISSUE TITLE
Why it is so slow on android?

### ISSUE THREAD

**Issue by carlos-gamedev** [denolehov/obsidian-git#458]
Currently, it takes about 5 minutes each time I pull or push anything on my Android phone whereas it only takes 30s on my Laptop with the same network.

I wonder why there is such a big difference.

**Comment by Vinzent03** [comment]
I'm using the native system-wide installed git on Desktop, but on mobile I'm using a reimplementation of Git in javascript as stated in the [README#mobile](https://github.com/denolehov/obsidian-git#mobile). It's way slower, but there's nothing I can do.

**Comment by vutruong-dev** [comment]
Ok, I got it.
Many thanks.

**Comment by carlos-gamedev** [comment]
Ok, I got it.
Next time I will read the readme carefully before asking

Many thanks
