### ISSUE TITLE
[Bug]: UnknownTransportError: unrecognized transport protocol: "ssh"

### ISSUE THREAD

**Issue by rastilization** [denolehov/obsidian-git#459]
### Describe the bug

Unable to operate git repo through ssh.

I've done this through termux. I've setup SSH keys. Cloned vault from github. Pointed Obsidian to cloned vault. Obsidian-Git asked me to provide remote, so I've done, after that it tried to fetch remote branches and showed this error message:

```
UnknownTransportError: Git remote "git@github.com:<username>/<repo>.git" uses an unrecognized transport protocol: "ssh"
```

### Steps to reproduce

Setup SSH keys.
Clone github repo vault.
Point Obsidian to cloned vault.
Setup remote.
???????
Bug

### Operating system

Android

### Installation Method

None

### Plugin version

2.17.4

**Comment by Vinzent03** [comment]
- As stated in the [README](https://github.com/denolehov/obsidian-git#restrictions-of-the-mobile-version), ssh is not supported on mobile.

**Comment by ackvf** [comment]
OH my :🤭
When I was adding ssh or https, I initially started with ssh, but it was a PITA, so I thought, "maybe I'll just slap https onto it", but then I was like "naah, I what if I want to access other services that I set up with ssh, maybe it will come in handy", so I spent an hour setting this up, figuring all issues one by one and then this error :) :) 

Well, I wish I had read the manual first.

Never mind, I'll still be using ssh.

---

@Vinzent03 As for the "`isomorphic-git` not supporting ssh" issue, is it possible to rely on native git in the system instead?

**Comment by Vinzent03** [comment]
Neither is there a system git on mobile nor could I access it from an Obsidian plugin. On desktop it uses system git so everything is supported.

**Comment by ackvf** [comment]
I see, my apologies. It seems that I don't understand it correctly. I did install git through Termux and cloned the Obsidian repo manually using ssh, after that I launched Obsidian app and received the above error. Is this version of git not available outside of Termux?

**Comment by Vinzent03** [comment]
Yeah exactly. Termux is its own app and Obsidian cannot access anything from it. (Only the files it writes back to the usual file system)
