### ISSUE TITLE
.gitignore example not working

### ISSUE THREAD

**Issue by pmbaumgartner** [denolehov/obsidian-git#46]
The example `.gitignore` file is the following:

```
.obsidian/  # to exclude Obsidian workspace settings (including plugin and hotkey configurations)
# OR
.obsidian/workspace  # to exlude workspace cache

# Add below lines to exclude OS settings and caches
.trash/
.DS_Store
```

When I use this, because of the comments in lines 1 and 3, it actually won't ignore those folders/files by default, you have to remove the comments. In order to allow people to just copy paste this .gitignore and have it work, I propose the following reformatting.

```
# to exclude Obsidian workspace settings (including plugin and hotkey configurations)
.obsidian/  
# OR only to exlude workspace cache
.obsidian/workspace 

# Add below lines to exclude OS settings and caches
.trash/
.DS_Store
```

I'm on macOS 10.15.6 with Obsidian v0.10.11.

**Comment by hnsol** [comment]
Thank you @pmbaumgartner , I've been wondering why my `.gitignore` doesn't work. Example above helps me so much !

**Comment by Vinzent03** [comment]
Thanks for the hint.
