### ISSUE TITLE
Documentation link in the README is broken

### ISSUE THREAD

**Issue by OscarBarrett** [denolehov/obsidian-git#464]
It currently links to https://publish.obsidian.md/git-doc, which shows a 502 error from CloudFlare. Looking at the commits it's not clear how/where this is published.

**Comment by Vinzent03** [comment]
Obsidian Publish is currently down. For the meantime, you can view the same files [here](https://github.com/denolehov/obsidian-git/tree/master/doc)

**Comment by Vinzent03** [comment]
Obsidian Publish is up again.
