### ISSUE TITLE
[Question] Can it be used in read-only mode?

### ISSUE THREAD

**Issue by meins111** [denolehov/obsidian-git#465]
First: Great plugin, thanks!

I was wondering whether it might also work in a read-only mode. So you would just configure a (public) repo with an obsidian vault and the plugin performs regular pulls - but never a push.

Use-case: give users the full obsidian experience of a documentation without them needing to authenticate as they are not expected to make any changes anyway

**Comment by Vinzent03** [comment]
You can just disable automatic backup, but enable automatic pull. I don't know what else is needed for "read-only mode"

**Comment by Vinzent03** [comment]
There's nothing called "Commit name". Do you mean Author name and email?

**Comment by meins111** [comment]
At mobile there is "Author Name for Commit", which is different than the username.

The former one seems to be required for a pull operation (but not for clone interestingly).
