### ISSUE TITLE
Proofreading - transposed words in settings for autobackup

### ISSUE THREAD

**Issue by onefellsloop** [denolehov/obsidian-git#468]
I noticed that the instructions for autobackup on line 99 didn't make sense (last sentence). I think the words are transposed.

"If turned off, it's independent from last the change."
This makes more sense to read "If turned off, it's independent from the last change."

I don't know the actual functionality to know if this is accurate or not,.

https://github.com/denolehov/obsidian-git/blob/76698921f687ce801490397f973a22d526a8a9f6/src/settings.ts#L99

(I love the project, btw, thanks!)

**Comment by Vinzent03** [comment]
Thanks for pointing out, will be in the next release.
