### ISSUE TITLE
[Feature request]: git log and show commit changes

### ISSUE THREAD

**Issue by mkczyk** [denolehov/obsidian-git#472]
I would like to see possibility of of seeing what has been committed last time. 

# User story

- [Current behavior] You have changes:

![image](https://user-images.githubusercontent.com/11051213/226185338-64c362dc-23c5-4db8-8ffa-235048fa6b28.png)

- [Current behavior] Commit this. Changes in window disappeared.
- [New] Click new icon "Commits".
- [New] It opens list of last commits. For example last 10 commits. (Extended feature: number of commits configurable in settings or by click button "Load more" at bottom of list.)

![image](https://user-images.githubusercontent.com/11051213/226185206-6f2f3214-65f8-4cf8-8a16-13437dbc2dd1.png)

- [New / Current behavior] When click on commit name it shows commit changes (the same as it is now in current "Changes", but this from specified commit).

![image](https://user-images.githubusercontent.com/11051213/226185280-538b39e2-908c-495b-b68e-68ec325b0273.png)

# Motivation

I have installed Obsidian Git and set:
- "Vault backup interval (minutes)": 10
- "Auto backup after file change": on

And I have synchronization via Dropbox (for syncing desktop and mobile - Android app). 

On mobile I disabled Obsidian git ([due to restrictions/performance](https://github.com/denolehov/obsidian-git#restrictions-of-the-mobile-version)). 

My workflow is:
- Write notes on mobile.
- Automatically sync via Dropbox.
- Open Obsidian on desktop.
- After opening Obsidian on desktop it commits immediately (due to setting "Auto backup after file change").

It works like a charm.

But then I would like to see what I just committed - what files I added/edited on mobile - usually I need to tidy/read them on desktop. 

# Workaround

Of course you can open console and type: `git log` or `gitk` to see what changes was made:

![image](https://user-images.githubusercontent.com/11051213/226186295-60a70ae9-109c-436d-a787-db9a17ea1db5.png)

But you have to manually open folder with vault, open console, type command.

To speed up this flow you can install two plugins:
- Shell Command
- Commander

In Shell Command add "gitk" command:

![image](https://user-images.githubusercontent.com/11051213/226186579-c2467b8b-735f-431d-8450-95c1dbeea990.png)

In Commander add icon to added command:

![image](https://user-images.githubusercontent.com/11051213/226186604-628b905b-ebea-4ef1-962f-abda7c0bed20.png)

Now you can easily click one icon which opens gitk and you can see commits:

![image](https://user-images.githubusercontent.com/11051213/226186637-344835ad-0a63-4924-8c40-0c845c5952ae.png)

It works good.

But it would be nice if I can see Changes in Obsidian Git in the same way as current changes. With this feature you could quickly open notes from last commits just by clicking on icon "Open file" (like now from "Changes"):

![image](https://user-images.githubusercontent.com/11051213/226187155-595bf2aa-50b4-457c-a98d-451fee680f2b.png)

**Comment by Vinzent03** [comment]
I suggest you the [Version History Diff](obsidian://show-plugin?id=obsidian-version-history-diff) plugin. I shows the history per file. Or do you really want to see the changes per commit?

**Comment by mkczyk** [comment]
Thanks for suggest plugin. It have nice command "Version history diff: Show Diff view for active file". But with this you can only see changes in selected file:

<img src="https://user-images.githubusercontent.com/11051213/226188307-5c5c4af2-05f3-4417-b9ab-fbee920b1af2.png" data-canonical-src="https://user-images.githubusercontent.com/11051213/226188307-5c5c4af2-05f3-4417-b9ab-fbee920b1af2.png" width="300" />

(I see also command "Obsidian Git: Open file history on GitHub" which is similar - but of course on GiHub instead of locally). 

But if you don't know what files changes you can't use it (see my use case in "Motivation": add note on mobile, after some days open Obsidian on desktop - you don't know which file to open).

I found another workaround:

# Workaround 2

Plugin Templater: https://github.com/denolehov/obsidian-git/issues/334#issuecomment-1282069968.

Result with command `gitlog`:  `git log --pretty=format:'%s' -5` and code from link above:

![image](https://user-images.githubusercontent.com/11051213/226188828-30785fa8-6865-4ffb-a33e-2bffc6956648.png)

Result with new command `gitshow`: ` git log --name-status --pretty=format:'%s' -1` (and code as before with replaced command):

```
<%_* 
const msgs = await tp.user.gitshow()
const array = msgs.split("\n")
await tp.system.suggester(array,array)
tR += tp.file.selection();
_%>
```

![image](https://user-images.githubusercontent.com/11051213/226188847-2229d8a8-6a27-4b24-86fa-4367bc04f8d9.png)

Now you have list of files from last commit. It nice, but I should extend it more (if it possible with Templater):
- select commit instead of just present changes from last commit (open first dialog, select commit, and pass selected commit as parameter to second dialog),
- select file, press enter, open this file.

If these extension are possible with Templater it would be nice workaroud for the feature request. 

But still Obsidian Git "Changes" window is really nice and reusing it for commits changes seems like the best, natural solution.

**Comment by Vinzent03** [comment]
Available in new release. Use a command to show the history view.

**Comment by mkczyk** [comment]
Thank you. It is awesome.

 
![image](https://user-images.githubusercontent.com/11051213/227048566-4eebf2c6-8842-4503-aae2-b8bf4bebc4ab.png)

**Comment by joellti** [comment]
I like this new feature a lot, but it only shows history globally. I would like to be given option to see the History view of the current active file, if it's all possible. Hope it can be considered. Thanks in advance.

**Comment by tamiroh** [comment]
@joellti 
I tried to implement the feature in the past (https://github.com/denolehov/obsidian-git/pull/463), but the Version History Diff plugin has almost the same functionality, so I started using it. It is good and easy to use.

**Comment by joellti** [comment]
Thx for the hint. I tried Version History Diff plugin before but it had a limitation with handling files renamed/moved. I tried it again with latest version and that limit is also addressed so it's perfect for my need now. Thanks again.

**Comment by jimpfaff** [comment]
I can go into Git and find the logs. That's simple. What I'd like to see is a record of the error messages or other notifications that come up from time to time. Those aren't always in the logs as far as I can tell.
