### ISSUE TITLE
[Bug]:  git obsidian error: fatal: bad object 

### ISSUE THREAD

**Issue by yannlk** [denolehov/obsidian-git#474]
### Describe the bug

The vault stopped backing up after no known change. Commit still works but won't push to the repository. 

### Relevant errors (if available)

<img width="300" alt="image" src="https://user-images.githubusercontent.com/104253173/226626935-e0a4f3af-06fa-4553-934d-2ccacd89485b.png">

### Steps to reproduce

Unknown what caused this behaviour...

### Expected Behavior

Push would work. 

### Operating system

macOS

### Installation Method

None

### Plugin version

2.18.0

**Comment by Vinzent03** [comment]
Your git repo is somehow a bit corrupted, that has nothing to do with this plugin. Please try some answers from [here](https://stackoverflow.com/questions/8788975/bitbucket-git-error-did-not-send-all-necessary-objects)
