### ISSUE TITLE
GitHub RSS SSH Host key changed

### ISSUE THREAD

**Issue by davidkopp** [denolehov/obsidian-git#476]
This is not a problem regarding this plugin, but I assume that many who use this plugin and have hosted their remote repo on GitHub currently have some problems because of that.
GitHub changed their RSS SSH Host key: https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/

At first I had to remove the old keys for github.com in `~/.ssh/known_hosts` and import the new key. See the linked article for instructions.

After that I still had some problems with Git inside Obsidian. Unfortunately there were no error/warning logs in the dev console (maybe something that can be improved). On the terminal I was able to see the problem:

```
Warning: the ECDSA host key for 'github.com' differs from the key for the IP address '140.82.121.4'
...
Are you sure you want to continue connecting (yes/no)?
```

So I also had to remove old entries in `known_hosts` for all IP addresses of github.com (there were many entries with 140.82.x.x in the file). 
Finally the git integration in Obsidian worked again.

Optional improvement:
I don't want that my `known_hosts` file includes multiple entries for all the ip addresses github.com is using (github.com uses DNS load balancing). Instead it should be sufficient to only have one entry with the host name github.com.
There I have now disabled the SSH option `CheckHostIP` for github.com in the config file (`~/.ssh/config`):

```
Host github.com
  CheckHostIP no
```

**Comment by GameFixxer** [comment]
I guess this one cannot be solved on the plugin side

**Comment by davidkopp** [comment]
@GameFixxer You are right. I created this issue especially to help others who had the same problems and were unsure whether the problem was perhaps caused by the plugin (it wasn't, GitHub is to blame).
