### ISSUE TITLE
插件可以commit但无法push到远程仓库

### ISSUE THREAD

**Issue by haoye11** [denolehov/obsidian-git#477]
<img width="144" alt="image" src="https://user-images.githubusercontent.com/111723832/227771265-27cb2674-aafc-47b0-b8de-a485e52feb79.png">
显示commit后会一直报上图的错误

**Comment by tamiroh** [comment]
I am in a similar situation. In my case the remote repository is not configured, but I get "fatal: bad revision 'null'" after commit every time.
I have recently investigated but have not yet found the cause.

**Comment by haoye11** [comment]
我刚刚改了一下，用了git push -u xxx master后好像不报错了
