### ISSUE TITLE
[Bug]: Custom date format does not follow standard UTS #35

### ISSUE THREAD

**Issue by caizefeng** [denolehov/obsidian-git#478]
### Describe the bug

When I use `yyyy-MM-dd HH:mm:ss` as the `{{date}} placeholder format`, messages like `2023-03-Su 18:51:43` are generated instead of `2023-03-26 18:51:43`, which does not follow the widely-accepted formatting pattern specified in `Unicode Technical Standard #35`. After some tests, I figure that this plugin probably mistake "d" for "E" and "D" for "d".
![image](https://user-images.githubusercontent.com/47969919/227771438-ae839d9f-5c64-4b34-9a65-ac4e82f78048.png)
![image](https://user-images.githubusercontent.com/47969919/227771449-5c30d9cb-c632-40d1-9e0e-0db094e0b711.png)

### Steps to reproduce

Change the custom date format to `yyyy-MM-dd HH:mm:ss` in `{{date}} placeholder format` entry and hit "Preview" below.

### Operating system

Windows

### Installation Method

None

### Plugin version

2.19.0

**Comment by Vinzent03** [comment]
I'm using the same format Obsidian uses for their daily note feature, which is the format [momentjs](https://momentjs.com/) uses. I'm sorry it's not following the standard, but I won't change that, because most of the other plugin use momentjs as well.
