### ISSUE TITLE
Rendering problem with mermaid

### ISSUE THREAD

**Issue by MichaelLhomme** [denolehov/obsidian-git#48]
Hello, I'm currently playing with mermaid in Obsidian and I encountered a problem with [user journey diagrams](https://mermaid-js.github.io/mermaid/#/user-journey)

Input (example from documentation) :
```mermaid
journey
  title My working day
  section Go to work
    Make tea: 5: Me
    Go upstairs: 3: Me
    Do work: 1: Me, Cat
  section Go home
    Go downstairs: 5: Me
    Sit down: 5: Me
```

Rendering (missing text):
![Screenshot_20210218_132947](https://user-images.githubusercontent.com/78609394/108357282-822b5d80-71ed-11eb-97ef-4eff6554e997.png)

**Comment by denolehov** [comment]
hey @MichaelLhomme, what makes you think this issue is related to the plugin? does text disappear after you commit or pull using the plugin?

**Comment by MichaelLhomme** [comment]
My bad I chose the wrong repository in my tabs, I read "Obsidian Git" as in "the repo for obsidian" and not the plugin for git. Closing this now

BTW great work on this (the plugin this time), I'm planning to use it to collaborate with students !
