### ISSUE TITLE
fatal: bad revision "null"

### ISSUE THREAD

**Issue by 2022Jean** [denolehov/obsidian-git#480]
## description
<img width="226" alt="image" src="https://user-images.githubusercontent.com/105527253/228128280-07ab62f4-7834-418e-8068-ff6764a04b45.png">
This keeps popping up and I don't know how to fix it.

## version
obsidian-git: 2.19.0
obsidian: 1.1.16
windows: 11 64X
git: 2.40.0

## console
<img width="430" alt="image" src="https://user-images.githubusercontent.com/105527253/228231578-08b86319-decc-453c-ba5c-a539c62f2257.png">

## other
I am not connected to the remote warehouse.

**Comment by Vinzent03** [comment]
Please open the console (ctrl + shift + i) to see if there are any other errors.

**Comment by KruznickMeta** [comment]
Hi, I'm having the same issue and this is what the console shows me.

<img width="507" alt="image" src="https://user-images.githubusercontent.com/111281168/228171748-1f6d85ef-251b-4e62-acc1-033bac18b67a.png">

**Comment by 2022Jean** [comment]
> Please open the console (ctrl + shift + i) to see if there are any other errors.

The exception in the console is the same as his.@KruznickMeta
<img width="684" alt="image" src="https://user-images.githubusercontent.com/105527253/228230020-bd3bdbce-1869-489d-af29-2ff7a4c57492.png">

**Comment by 2022Jean** [comment]
> 

Thank you very much for your reply. Forgot to say, I am not connected to the remote warehouse.

**Comment by Vinzent03** [comment]
@2022Jean Have you tried, what @erdivartanovich suggested?

**Comment by 2022Jean** [comment]
> @2022Jean Have you tried, what @erdivartanovich suggested?

I am not connected to the remote warehouse.

**Comment by tamiroh** [comment]
I am in a similar situation. I don't have a remote repository too, and every time I execute a commit or other git-related operation, this error pops up.

**Comment by tamiroh** [comment]
OK, I fixed it.

**Comment by 2022Jean** [comment]
> OK, I fixed it.

I would like to ask, how can I use the latest version of the plugin? I don't know how to convert the source code to the plug-in format.😢

**Comment by tamiroh** [comment]
@2022Jean 
This fix has not yet been released. When it is released by @Vinzent03, you will receive the update via Obsidian as usual!

**Comment by 2022Jean** [comment]
> @2022Jean This fix has not yet been released. When it is released by @Vinzent03, you will receive the update via Obsidian as usual!

got it

thank you!😊(❁´◡`❁)

**Comment by Vinzent03** [comment]
Please try new version `1.19.1`.

**Comment by 2022Jean** [comment]
> Please try new version `2.19.1`.

After some groping, I found that "fatal: bad revision "null"" is related to the config configuration file in the .git folder. I have two local warehouses, and one of them has no "fatal: bad revision "null"" exception , its configuration file content is in the following format:
```
[core]
	repositoryformatversion = 0
	filemode = false
	bare = false
	logallrefupdates = true
	ignorecase = true
[http]
	sslVerify = false
[user]
	name = ++++++++
	email = ++++++++@gmail.com
```
And the configuration file of another abnormal warehouse is like this:
```
[core]
	repositoryformatversion = 0
	filemode = false
	bare = false
	logallrefupdates = true
	ignorecase = true
```
When I copied the content of the configuration file of the normal warehouse to the configuration file of the abnormal warehouse, everything returned to normal.
Finally, thank you very much for your patient reply!

**Comment by tamiroh** [comment]
Yes, the error seems to continue to occur even after the bug fix update unless the editor is restarted.

**Comment by ostweg** [comment]
This fix worked for me:
1. Go to your folder where you want to push/pull changes and open command line.
2. type this => git remote add origin https://github.com/[your username]/[your repository name].git, to see if remote origin already exists
3. then type this => branch -M main
4. lastly type this => git push -u origin main

Now git in obisidian should work.

**Comment by sei-so** [comment]
> This fix worked for me:
> 
> 1. Go to your folder where you want to push/pull changes and open command line.
> 2. type this => git remote add origin [https://github.com/[your](https://github.com/%5Byour) username]/[your repository name].git, to see if remote origin already exists
> 3. then type this => branch -M main
> 4. lastly type this => git push -u origin main
> 
> Now git in obsidian should work.

@ostweg And it worked for me too! Thanks a lot, feller.

**Comment by idossha** [comment]
> This fix worked for me:
> 
> 1. Go to your folder where you want to push/pull changes and open command line.
> 2. type this => git remote add origin [https://github.com/[your](https://github.com/%5Byour) username]/[your repository name].git, to see if remote origin already exists
> 3. then type this => branch -M main
> 4. lastly type this => git push -u origin main
> 
> Now git in obsidian should work.

worked great. Tnx!

**Comment by ddzzkk** [comment]
when you are pushing a local repo to a EMPTY remote repo, this error pops up. what you should do is  just like what @ostweg said

**Comment by MangoBee** [comment]
> Fixed! I was having the same issue. I suspect this plugin need exact bind to specific branch in remote git, this shown when I try to run command `Git: Push`, a dialog pop up asking for selecting a remote branch. So to fix this is simply by syncing the state of your local and remote first. At my end I just run this from terminal
> 
> ```shell
> # make sure local and remote are synced
> git fetch origin
> # push your local state to remote branch in this case for me is master
> git push origin master
> ```
> 
> After that every thing seems work well, the error is not shown anymore.

Thanks, this work for me, only small different is after `git push`, i follow suggestion `git push --set-upstream origin main` instead.
