### ISSUE TITLE
[Bug]: Installing fig.io terminal tool causes Bad permissions/Owner error

### ISSUE THREAD

**Issue by namefailed** [denolehov/obsidian-git#486]
### Describe the bug

Things worked fine, until I installed fig from fig.io. It hooks into .ssh/config and adds an include which for whatever reason causes obsidian-git to not be able to Authenticate. 

I commented out the lines that cause fig SSH autocomplete integrations (located in .ssh/config) and it works fine, however this is only a bandaid.

### Relevant errors (if available)

```shell
git obsidian error: Bad owner or permissions on /home/grey/.fig/ssh
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
plugin:obsidian-git:26501 Uncaught (in promise) Error: Bad owner or permissions on /home/grey/.fig/ssh
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

    at Object.action (plugin:obsidian-git:26501:25)
    at PluginStore.exec (plugin:obsidian-git:26526:25)
    at eval (plugin:obsidian-git:24031:43)
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (plugin:obsidian-git:24029:16)
    at GitExecutorChain.eval (plugin:obsidian-git:24013:44)
    at Generator.next (<anonymous>)
    at fulfilled (plugin:obsidian-git:22858:24)
```

### Steps to reproduce

install fig, and properly set up all its integrations (specifically SSH integrations for Autocomplete)

### Expected Behavior

No Authentication Error

### Addition context

This is on linux. The lastest Pop_Os Version. 

### Operating system

Linux

### Installation Method

Flatpak

### Plugin version

Most Recent

**Comment by namefailed** [comment]
# Steps to be able to reproduce
comment out the automatically generated fig code from .ssh/config to temporarily solve the issue

**Comment by Vinzent03** [comment]
I don't think this is an issue with this plugin, because you are changing something on your ssh config. Nevertheless, please try running `chmod 600 <your-new-ssh-dir>`. Or try a different Obsidian installing method than Flatpak, best AppImage.

**Comment by namefailed** [comment]
Changing permissions of the .fig folder with the suggested command fixed the problem.  Thanks for the suggestion!
