### ISSUE TITLE
[Bug]: cloning repo on mobile

### ISSUE THREAD

**Issue by progressify** [denolehov/obsidian-git#488]
### Describe the bug

When I try to clone my repo I receive a 422 error

### Steps to reproduce

- download obsidian
- create a fresh repo
- download obsidian-git
- set the username and gitlab token
- start the procedure for cloning the repo
- insert the gitlab url
- and follow the tour

At the end of procedure: 
![Screenshot_20230407-211110](https://user-images.githubusercontent.com/11472632/230664558-0bafc1c2-45aa-4445-9da7-ad6325c95cf4.png)

### Operating system

Android

### Installation Method

Other

### Plugin version

latest

**Comment by progressify** [comment]
Resolved!
You need to add `.git` at the end of the url of the repository

**Comment by alexcochran** [comment]
Thanks for this.

For anyone else here in the future like me, be sure to check the .git/config file and see that ".git" is at the end of your URL

![Image](https://github.com/user-attachments/assets/ca4d2b33-950c-493e-b2d4-61264a79ec0f)
