### ISSUE TITLE
Assign hotkeys for pulling/pushing changes to a remote repository

### ISSUE THREAD

**Issue by HermanThiart** [denolehov/obsidian-git#49]
Hey there.
Really love your plugin.     Good work!   A coffee is definitely due.   :-)

I cannot see the option to assign hotkeys for pulling/pushing to Github?  Apologies if I need new spectacles.

K.rgds

**Comment by HermanThiart** [comment]
No hot key needed after using it for a while. :)

**Comment by Vinzent03** [comment]
Just as a side note. Nothing to do with this plugin. You can set hotkeys for every command listed in the command palette (`Ctrl + p`) in the Settings under Hotkeys.
