### ISSUE TITLE
[Bug]: Android can use git via Termux, this option should be available to provide native git.

### ISSUE THREAD

**Issue by jasonm23** [denolehov/obsidian-git#497]
### Describe the bug

There's a number of issues using the js git implementation, in my case I want to use ssh as transport.

Git is available on Android via Termux, yet the README states incorrectly that

> [isomorphic-git](https://isomorphic-git.org/), which is a re-implementation of git in JavaScript, **because you cannot use native git on Android** or iOS.

Emphasis added.

Will you accept a pull request which adds the option to use system git on Android?

### Operating system

Android

### Plugin version

2.19.1

**Comment by jasonm23** [comment]
https://github.com/denolehov/obsidian-git/blob/782f8105280edba22486745b03efeb95a3b5094d/src/main.ts#L682-L687

We can add a clause here to allow `Platform.isAndroidApp` to use `SimpleGit`.

e.g.

```js
if (Platform.isDesktopApp) {
  this.gitManager = new SimpleGit(this);
  await (this.gitManager as SimpleGit).setGitInstance()};
else if (Platform.isAndroidApp) {
  this.gitManager = new SimpleGit(this);
  await (this.gitManager as SimpleGit).setGitInstance()};
else {
  this.gitManager = new IsomorphicGit(this)};
```

It may be preferable to add `settings.androidUseGitCommand`, as opposed to just throwing an error message, so that the user can opt for isomorphic-git.

**Comment by jasonm23** [comment]
Adding to settings something like this:

```js
new Setting(containerEl)
  .setName("Use Termux/git on Android")
  .addToggle((toggle) =>
                toggle
                    .setValue(plugin.localStorage.getAndroidUseGitCommand())
                    .onChange((value) => {
                        plugin.localStorage.setAndroidUseGitCommand(value);
                    }) 
  );
```

So we'd do this in `main.ts`

```
if (Platform.isDesktopApp) {
  this.gitManager = new SimpleGit(this);
  await (this.gitManager as SimpleGit).setGitInstance()};
else if (Platform.isAndroidApp && this.settings.androidUseGitCommand) {
  this.gitManager = new SimpleGit(this);
  await (this.gitManager as SimpleGit).setGitInstance()};
else {
  this.gitManager = new IsomorphicGit(this)};
```

**Comment by Vinzent03** [comment]
This won't work, because simplegit uses node js, which is not available on mobile, but only on desktop. This plugin can only ship JavaScript and can't interact with any native libraries. That's why I can only use a reimplementation.

**Comment by jasonm23** [comment]
Thanks for the info @Vinzent03 

It's very annoying that Obsidian Android has this limitation but I suppose I can get around it via Termux widget to do the git pull-push.

Thanks again for your help and the git integration

**Comment by jasonm23** [comment]
I use a termux widget script to do the pull/push.

Thanks though,  someone reading this thread could use the method you described and it'd work ok.

My script basically does

```
git pull --rebase
git push -u origin master
```

And isomorphic does the commits ok.

**Comment by elvisisvan** [comment]
i have been syncing obsidian with git via termux for months and it works flawlessly; the trick is to successfully clone target repo, after that i'm pretty much set, termux is truly the catalyst here.
