### ISSUE TITLE
Pull from remote which causes merge conflicts causes odd behaviour

### ISSUE THREAD

**Issue by jamiebrynes7** [denolehov/obsidian-git#5]
### Actual behaviour

If your pull from remote causes merge conflicts in your local state, the status bar indicates `git: pulling changes from remote repo...` until the next command.

An error is logged to the console, but this isn't surfaced to the user.

### Expected behaviour

A notice which indicates the operation failed and the status bar reflects this too. 

I don't expect the plugin to help me resolve the conflicts necessarily, but just a heads up that this happened 😄

**Comment by denolehov** [comment]
oh yes! this is definitely something that needs to be improved, thank you!

**Comment by denolehov** [comment]
In [v1.4.0](https://github.com/denolehov/obsidian-git/releases/tag/1.4.0) all the messages (including error ones) are being displayed in status bar.
