### ISSUE TITLE
Github Token Authentication is coming this year

### ISSUE THREAD

**Issue by MCalder423** [denolehov/obsidian-git#50]
Hi Denis,
I've started getting emails from Github like this:

You recently used a password to access the repository at blahblah/obsidian with git using git/2.20.1.

Basic authentication using a password to Git is deprecated and will soon no longer work. Visit https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information around suggested workarounds and removal dates.

Thanks,
The GitHub Team

It looks like Github is going to be doing away with username/password authentication in July/August of this year, and if nothing is done about it in this plug-in, it will stop working for everyone then.

I'm pretty sure you are aware of this already, but I didn't see it listed in the open issues so I thought I would post this so we can track your  progress on it.  LOVE the plugin, by the way!

**Comment by Larandar** [comment]
Hello, I think this is not due to the way the plugin work but how you configured git on your side.

This is the way all git server expect authentication currently: https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh

**Comment by Vinzent03** [comment]
You have to change your global git credentials. Not related to this plugin.
