### ISSUE TITLE
[Bug]: flush notifition forever

### ISSUE THREAD

**Issue by godlmk** [denolehov/obsidian-git#502]
### Describe the bug

after open obsidian,It flush notifition forever,only open ”disable notifications“ can stop it.
![image](https://user-images.githubusercontent.com/64939927/235040015-b10121de-a638-404f-9ef6-c722e483f560.png)

### Steps to reproduce

no more info

### Operating system

Windows

### Installation Method

None

### Plugin version

2.19.1

**Comment by Vinzent03** [comment]
Please share all your plugins settings. Best multiple screenshots.

**Comment by pastafizia** [comment]
i have the same problem but it only occurs when leaving obsidian in idle for a while... it only started happening lately i don't know when precisely

**Comment by pastafizia** [comment]
it's not closed at all... it's still happening even after last update

**Comment by godlmk** [comment]
> it's not closed at all... it's still happening even after last update

you can  try reconfig your git.

**Comment by andreadellacorte** [comment]
Happening to me too

**Comment by andreadellacorte** [comment]
How do I do that? Sorry, still an early user.

**Comment by Vinzent03** [comment]
Just some screenshots of the first Automatic section

**Comment by smeredith** [comment]
Here are my settings (copied from dupe #518):

Split automatic commit and push: off
Vault backup interval (minutes): 60
Auto backup after latest commit: on
Auto pull interval: 0
Pull updates on startup: on
Push on backup: on
Pull changes before push: on
Advanced settings all default

**Comment by smeredith** [comment]
No errors in the console.

**Comment by badcc** [comment]
Yep, I have been having this same issue for at LEAST a couple months.

**Comment by Vinzent03** [comment]
Please share the `git status` output while the notifications are coming up.

**Comment by smeredith** [comment]
I don't know what you are asking for here.

**Comment by Vinzent03** [comment]
Please run `git status` in the terminal in your git repository, while you are experiencing these many notifications. The message "Committed 0 files" shouldn't be possible, because it checks before that for any changes.

**Comment by smeredith** [comment]
```
PS C:\Users\smere\steve> git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
```

**Comment by Vinzent03** [comment]
Thanks, I may found the reason. What's the output of `app.plugins.plugins["obsidian-git"].localStorage.getConflict()` in the console in Obsidian?

**Comment by smeredith** [comment]
'true'

**Comment by smeredith** [comment]
'true'

**Comment by Vinzent03** [comment]
Thanks for your assistant! Should be fixed in 2.20.2

**Comment by smeredith** [comment]
Well done and thank you.

**Comment by badcc** [comment]
Thank you @Vinzent03 !
