### ISSUE TITLE
[question]I was unable to use the obsidian for a few seconds every minute after using the plugin

### ISSUE THREAD

**Issue by wangtianzhaxinle** [denolehov/obsidian-git#506]
version：2.19.1
![image](https://user-images.githubusercontent.com/49827896/236359204-9559f1ff-1de6-4035-9c18-82522ec4de09.png)
For a few seconds every minute, the software gets stuck，the console information is as follows
![image](https://user-images.githubusercontent.com/49827896/236363320-ff922fa2-988a-4f6f-8a3c-d59d97da4061.png)
Operating system
windows10
The video can be seen below
https://user-images.githubusercontent.com/49827896/236364739-ed7433b1-7cab-4779-ba4e-7341102df338.mp4

**Comment by Vinzent03** [comment]
Sorry for now answering, but I didn't know a way to fix this. Maybe an Obsidian installer update could fix this by now. If not, I still don't know what's the reason. Maybe your machine is just too slow.
