### ISSUE TITLE
Plugin tries to push through Obsidian Mobile

### ISSUE THREAD

**Issue by szfkamil** [denolehov/obsidian-git#507]
Hey,

Obsidian Git plugins seems to try syncing via the mobile app, but is unsuccessful, I cannot specify the path on mobile because the path does not exist on mobile, but on my desktop.

**Comment by Vinzent03** [comment]
You can't specify a path, because there is no way to install git on a mobile device. The plugin ships it's own git implementation.

**Comment by szfkamil** [comment]
Actually, there was an option to "disable on this device" as the very last option in settings which fixed the issue.

**Comment by szfkamil** [comment]
> You can't specify a path, because there is no way to install git on a mobile device. The plugin ships it's own git implementation.

What I mean by that, by the way, is that the notification implied I need to specify the path. I forgot to include the prompt screenshot so it might have been unclear!
