### ISSUE TITLE
[Question] "Buffer Error" when I try to push the changes when I make from my phone onto the repo.

### ISSUE THREAD

**Issue by AJCGxD** [denolehov/obsidian-git#508]
When I make changes on my laptop and pull the changes on my phone there is no error, but when I make changes on my phone and try to push it to the repo it shows me "Buffer error". I have deleted and reinstalled the app, made a new repo, still it has not been fixed.

**Comment by AJCGxD** [comment]
I am not even able to clone the repo on my new vault now, I look into and then check if I have problems

**Comment by bjr29** [comment]
Can we reopen this unless someone knows a fix? I'm now having this issue.

**Comment by Vinzent03** [comment]
I'm not reopening as there is no fix available. Duplicate of #307
