### ISSUE TITLE
[Bug]: Documentation Starting Page broken link

### ISSUE THREAD

**Issue by GollyTicker** [denolehov/obsidian-git#509]
### Describe the bug

When opening the documentation (as linked in the README) https://publish.obsidian.md/git-doc/Start+here, we expect to see the rendering of [this web-page](https://github.com/denolehov/obsidian-git/blob/master/docs/Start%20here.md). However, instead we see this:

![grafik](https://github.com/denolehov/obsidian-git/assets/4527862/844abcec-6a72-4e4b-a3be-c86636ea0641)

The same problem happens for the https://publish.obsidian.md/git-doc/Authentication page. All other pages work correctly though.

### Steps to reproduce

Open https://publish.obsidian.md/git-doc/Start+here

### Expected Behavior

Show rendering of https://github.com/denolehov/obsidian-git/blob/master/docs/Start%20here.md

### Operating system

Windows

### Installation Method

None

### Plugin version

2.19.1

**Comment by Vinzent03** [comment]
Should be fixed now.
