### ISSUE TITLE
Empty files after Git Update

### ISSUE THREAD

**Issue by InvisbleO** [denolehov/obsidian-git#51]
Hi, i have had the same error multiple times: After the vault is synced with github, some fiels are empty except for heading. I have disabled pull update and push and am working only on one device.

**Comment by luckman212** [comment]
Not sure if this plugin is to blame for that. I think there may be something else going on:
[Data loss - 0.11.3 - zero byte .md file in vault - Bug reports - Obsidian Forum](https://forum.obsidian.md/t/data-loss-0-11-3-zero-byte-md-file-in-vault/13538)

**Comment by Vinzent03** [comment]
I don't think this is related to this plugin.
