### ISSUE TITLE
[Bug]: Items fold is not working as expected

### ISSUE THREAD

**Issue by juanbretti** [denolehov/obsidian-git#512]
### Describe the bug

With the current version 1.3.1, the item folding is not working as expected.
Currently is shown:

<img width="241" alt="image" src="https://github.com/denolehov/obsidian-git/assets/10165911/27a8cc1a-2b55-4dbb-969f-9da8f41a1718">

I tried multiple themes, but it is always looking like the previous.
Obsidian release log version 1.3.1, mentions some changes on the folding: https://forum.obsidian.md/t/obsidian-release-v1-3-1-insider-build/59810

### Steps to reproduce

Using insider version 1.3.1 on Windows

### Expected Behavior

It should look like:

![image](https://github.com/denolehov/obsidian-git/assets/10165911/48bcb8a1-1aa4-45f2-99ca-6155ff62d8c2)

### Addition context

Edition	Windows 11 Pro
Version	22H2
Installed on	‎10/‎12/‎2022
OS build	22621.1702
Experience	Windows Feature Experience Pack 1000.22641.1000.0

Obsidian
Insider 1.3.1

### Operating system

Windows

### Installation Method

Other

### Plugin version

2.19.1

**Comment by Vinzent03** [comment]
I've already a fix ready, just have to push and release it.
