### ISSUE TITLE
how do i change ssh port?

### ISSUE THREAD

**Issue by renjithravindran** [denolehov/obsidian-git#516]
my network does not allow git to use ssh over port 22, so i use ssh over an https port as given [here](
https://docs.github.com/en/authentication/troubleshooting-ssh/using-ssh-over-the-https-port).

So how do i tell obsidian-git to do the same?

**Comment by Vinzent03** [comment]
Your existing ssh config should be respected and there is nothing else to configure within the plugin.

**Comment by renjithravindran** [comment]
the plugin does not seem to go with my ssh config.
It says connection refused on port 22!
My ssh config config is set to use port 443 for github, and it is working generally..
Thanks

**Comment by Vinzent03** [comment]
So it works when you run just `git push` in the terminal, but not when invoked in Obsidian? Strange. You may try the `GIT_SSH_COMMAND` env var. https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables

**Comment by Vinzent03** [comment]
You should be able to add that env var in the plugin settings as well. But I see now that you are using flatpak. That explains the issue, as I think flatpak restricts the access to that file for Obsidian and thus this plugin.

**Comment by renjithravindran** [comment]
I just kept forgetting to reply :/
Great so the mystery is solved.. flatpak!
Anyways I added perms for ssh-config in flatseal and everything is fine!
Thank you!

**Comment by arathunku** [comment]
In my case, I have a bit more than just a port change. Instead of using AppImage, missing desktop files, I've overwritten some flatpak permissions:

```
$ cat ~/.local/share/flatpak/overrides/md.obsidian.Obsidian --plain
[Context]
sockets=gpg-agent
filesystems=~/.ssh;host-etc;host-os;host
```

It works without a problem and uses my yubikey to authenticate.
