### ISSUE TITLE
[Bug]: Missing multithreading lock on Source Control buttons

### ISSUE THREAD

**Issue by ddelange** [denolehov/obsidian-git#517]
### Describe the bug

If I press the Backup (leftmost) button in source control (especially on mobile where it's a bit slower), and I press it again 1 second later, there will be duplicate notifications. Two pulls, two commits, etc running concurrently. I was now left with a broken branch on mobile, because the commit referenced an object that only existed because there was another thread that was writing git objects.

### Relevant errors (if available)

```shell
`NotFoundError: could not find ab42cd42...`
```

### Steps to reproduce

Run Backup twice in short succession on mobile.

### Expected Behavior

When any of the actions is currently running (wheel is spinning in source control), I expect all the buttons to be grayed out. It should only release / make the buttons clickable again, once the last action has finished.

### Addition context

From the command palette options, I see no way to correct here. I would like a `git reset --hard origin/master`, now I'm resorting to copying my desktop `.git` to my phone.

### Operating system

Android

### Installation Method

Other

### Plugin version

2.20.0

**Comment by Vinzent03** [comment]
Thanks for reporting!
