### ISSUE TITLE
[Bug]: Continuous stream of messages: "Committed 0 files" and "No changes to push"

### ISSUE THREAD

**Issue by smeredith** [denolehov/obsidian-git#518]
### Describe the bug

When it's time to automatically backup, I get a continuous stream of messages: "Committed 0 files" and "No changes to push". The only way I have found to make it stop is to set the backup interval to 0.

<img width="229" alt="image" src="https://github.com/denolehov/obsidian-git/assets/6439539/d7018067-903a-490f-a787-f4e3b4c90df5">

### Steps to reproduce

Split automatic commit and push: off
Vault backup interval (minutes): 60
Auto backup after latest commit: on
Auto pull interval: 0
Pull updates on startup: on
Push on backup: on
Pull changes before push: on
Advanced settings all default

### Operating system

Windows

### Installation Method

None

### Plugin version

2.20

**Comment by LightTemplar** [comment]
It looks like this: https://github.com/denolehov/obsidian-git/issues/502
