### ISSUE TITLE
No options panel and constantly on `git: ready` without committing after updating Obsidian to v0.11.0

### ISSUE THREAD

**Issue by yotamDvir** [denolehov/obsidian-git#52]
Hi, thanks for this nice plugin.

It's been working great until I updated Obsidian to v0.11.0.

After the update, at least that's when I happened to notice, the settings panel disappeared and the status was stuck on `git: ready` without ever committing. I uninstalled and tried to install again, but it just says "installation failed".

Just as I'm writing this, I tried again and it worked, but the options panel still isn't there and still stuck on `git: ready`.

Git still works fine when I use it manually.

I'm on a Mac. Happy to provide more debugging info if you can guide me how to do so.

Thanks!

**Comment by vishae** [comment]
I'm also experiencing this issue. I've tried uninstalling and reinstalling the plugin and Obsidian and it doesn't make any difference.

**Comment by vishae** [comment]
This is the error log I get when I open Developer Tools:

[obsidian.md-1615551306225.log](https://github.com/denolehov/obsidian-git/files/6129939/obsidian.md-1615551306225.log)

<img width="902" alt="Screen Shot 2021-03-12 at 11 16 46 pm" src="https://user-images.githubusercontent.com/6110232/110939703-efb05100-8389-11eb-94fa-4085e6d3a13e.png">

**Comment by s10** [comment]
Looks like this error is not related to the Obsidian upgrade.

I faced same issue after minor MacOS security update. Error has gone after reinstalling Xcode Command Line Tools:
```
xcode-select --install
```

**Comment by Vinzent03** [comment]
@yotamDvir Does @s10 fix help?

**Comment by vishae** [comment]
I reinstalled homebrew and git via command line and then it worked.

**Comment by cristianmtr** [comment]
I am getting this error in the dev console:

![image](https://user-images.githubusercontent.com/8330330/111322319-18c23180-8669-11eb-9a35-c86d6c6b8033.png)

Ubuntu 20.04, `git` is installed.

**Comment by Vinzent03** [comment]
@cristianmtr How did you install Obsidian?  Via Snap?

**Comment by cristianmtr** [comment]
I don't remember. Which one is supposed to work? I just got an update for Git Obsidian actually. It seems to add the panel but the command always fails because it doesn't find `git`.

**Comment by Vinzent03** [comment]
Yes the new update adds the commands and settings pane, although it couldn't find git. That part has not changed and I can't do anything to solve this.
If you type `snap list` in your terminal you see your installed applications. If Obsidian is in that list you have installed Obsidian with Snap. I would suggest you to install it with Flatpak or appImage.

**Comment by cristianmtr** [comment]
That worked

**Comment by Vinzent03** [comment]
Snap apps are in a kind of sandbox, so it has no access to other system applications like git.

**Comment by yotamDvir** [comment]
Thanks @s10 I can now write in peace.

Off topic, I wonder why we have to `xcode-select --install` after security updates; not the first time this happened to me, though back then it caused a problem with something else on my machine.
