### ISSUE TITLE
Why is snap not supported?

### ISSUE THREAD

**Issue by TangentFoxy** [denolehov/obsidian-git#521]
From browsing closed and open issues, it seems that snap is said to not be supported because of the sandbox.

Is this the only reason? I have installed Obsidian with snap, but with the sandboxing disabled. Does this mean I shouldn't encounter these issues or is there a more fundamental issue?

**Comment by Vinzent03** [comment]
Yeah the sandboxing should be the only issue. It should work, if you somehow disabled that.
