### ISSUE TITLE
[Bug]: How to put it back in sidebar?

### ISSUE THREAD

**Issue by yarub123** [denolehov/obsidian-git#522]
### Describe the bug

Is it removed because of the new update? If so how to put it back?

### Steps to reproduce

Start up obsidian.

### Expected Behavior

As per usual for it to be in the right sidebar so you can commit, stage, etc.

### Operating system

macOS

### Installation Method

None

### Plugin version

2.20.1

**Comment by Vinzent03** [comment]
I guess you mean the source control view. There is a command to open that. See readme
