### ISSUE TITLE
[Bug]: Cannot Run command

### ISSUE THREAD

**Issue by flowingblaze** [denolehov/obsidian-git#528]
### Describe the bug

I am on a windows machine. I installed git and github desktop, I followed the steps on Danny Hatcher's Tutorial and the plugin isn't working. I tried turning the plugin off and on and I also uninstalled the plugin and reinstalled. I have the .git and .gitattributes folder in my vault.

### Steps to reproduce

The steps in the tutorial I followed:
- Install Git
- Install Github desktop
- Install Obsidian Git plugin and enable
- Create repository 
- Push to remote repository 

and that's around where the tutorial stops working and I get the message. 

### Operating system

Windows

### Installation Method

None

### Plugin version

2.20.3

**Comment by Vinzent03** [comment]
Please share the link of the tutorial and the exact error in the console (CTRL + shift + I)

**Comment by flowingblaze** [comment]
For whatever reason now It works ever since yesterday. https://www.youtube.com/watch?v=XR7PYaMVDw0 is the tutorial I was using, just in case if you still need the link for some reason. I think I just needed to restart my computer to get git to work for some reason.
