### ISSUE TITLE
[Bug]: NodeJS 14 EOL need to upgrade to NodeJS 18

### ISSUE THREAD

**Issue by peterzhu1992** [denolehov/obsidian-git#534]
### Describe the bug

NodeJS 14 ends support on 20230430, NodeJS 16 will end support in roughly 3 months. (https://endoflife.date/nodejs)
This repo should start the migration to NodeJS 16.

Thanks.

### Steps to reproduce

This repo is still using nodejs 14.

### Operating system

Linux

### Installation Method

None

### Plugin version

n/a

**Comment by Vinzent03** [comment]
Thanks for pointing out. Done in 4565af2

**Comment by Vinzent03** [comment]
Should be fixed now as well. I'm already using nodejs 19 locally.
