### ISSUE TITLE
[Bug]: GPG signing doesn't work on macOS

### ISSUE THREAD

**Issue by akaralar** [denolehov/obsidian-git#535]
### Describe the bug

I'm failing to sign my commits using `gpg` on macOS and hence can not make a backup of my data.

### Relevant errors (if available)

```shell
caught (in promise) Error: error: gpg failed to sign the data
fatal: failed to write commit object

    at Object.action (plugin:obsidian-git:23833:25)
    at PluginStore.exec (plugin:obsidian-git:23858:25)
    at eval (plugin:obsidian-git:21445:43)
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (plugin:obsidian-git:21443:16)
    at GitExecutorChain.eval (plugin:obsidian-git:21427:44)
    at Generator.next (<anonymous>)
    at fulfilled (plugin:obsidian-git:20276:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95
```

### Steps to reproduce

- Try to back up
- It fails with the error above

### Expected Behavior

I expect the backup to happen with signed commits

### Addition context

in my global config file at `~/.config/git/config` I have 

```
[user]
  name = <my_name>
  email = <my_email>
  signingkey = <my_signing_key>
[commit]
  gpgsign = true
[gpg]
  program = /opt/homebrew/bin/gpg
```

I can sign and commit properly in my terminal, so git signing works from the terminal. When I launch Obsidian from the terminal git signing also works but when launch the app normally it doesn't work. 

```
$ which -a gpg
/opt/homebrew/bin/gpg

$ which -a gpg-agent
/opt/homebrew/bin/gpg-agent
```

I'm on macOS Ventura 13.4 and Obsidian 1.3.5 (Installer 1.3.5)

### Operating system

macOS

### Installation Method

None

### Plugin version

2.20.3

**Comment by Vinzent03** [comment]
Do you have to enter a password on commit? So a prompt comes up when launched from terminal and this prompt doesn't come when launched normally?

**Comment by akaralar** [comment]
No I commit without entering a password, the password might be in the keychain though as I have in my git config `credential.helper=osxkeychain`, however I'm not sure if it's for gpg credentials or general git service credentials

**Comment by Vinzent03** [comment]
Did you set any environment variables in your shell config?

**Comment by akaralar** [comment]
in my `.zprofile` I have

```bash
# Edit gnupg config directory
export GNUPGHOME="${HOME}/.config/gnupg"

# collect passwords for gpg from the terminal
if [ -t 0 ]; then
	# Set GPG_TTY so gpg-agent knows where to prompt.  See gpg-agent(1)
	export GPG_TTY="$(tty)"
	# Set PINENTRY_USER_DATA so pinentry-auto knows to present a text UI.
	export PINENTRY_USER_DATA=USE_TTY=1
fi
```

**Comment by jbehrens94** [comment]
I am experiencing this issue too. When I cmd+p > create backup, I get an error notification from Obsidian that gpg signing failed.

**Comment by Vinzent03** [comment]
@akaralar Please try setting the "Additional environment variables" setting under "Advanced" in the plugin settings to `GNUPGHOME=HOME/.config/gnupg` and replace `HOME` to your actual home path. When Obsidian is not started via terminal the environment variables are different, so it doesn't catch the config dir change.

**Comment by akaralar** [comment]
@Vinzent03 doing that and restarting Obsidian fixed it, thanks!
