### ISSUE TITLE
[Bug]: Empty commits genereated and pushed to repo (when exluded from `.gitignore` file is changed) 

### ISSUE THREAD

**Issue by mwoz123** [denolehov/obsidian-git#538]
### Describe the bug

Obisdian git produces & pushes empty commits.
~~Probably~~ due to changes in (not ignored) hidden config `.obsidian` file.

I stops to happen after I manually commited the file in `.obsidian` folder

### Relevant errors (if available)

![image](https://github.com/denolehov/obsidian-git/assets/4487025/895c604c-5a10-4e2f-80ba-0265e64a97a2)
... and many more empty commits that didn't fit in screen shot....

### Steps to reproduce

~~I'm not 100% sure but I guess~~ it's related to hidden by obsidian file manager (as it stopped to happen after commiting that file) :
1. turn on auto commit and push every couple minutes - for testing e.g. 1minute
1. add one of .obsidian files to git tracking e.g. ` .obsidian/plugins/cmdr/data.json`
2. do a change in this file.
3. it seems that obsidian-git is trying to commit the files

### Expected Behavior

no empty commits in git history

## Empty commit example:
1)  
![image](https://github.com/denolehov/obsidian-git/assets/4487025/5f749c7a-a69c-41cf-900f-abb230d7bb17)
2)
![image](https://github.com/denolehov/obsidian-git/assets/4487025/1fa42337-aaba-4eff-b06b-116110658667)

## commit .obsidian config file
![image](https://github.com/denolehov/obsidian-git/assets/4487025/1c4c732c-ee14-40c6-82f3-f74f86c2948f)

## .gitignore

```
.obsidian/*
!.obsidian/hotkeys.json
!.obsidian/appearance.json

!.obsidian/plugins
.obsidian/plugins/*
#.obsidian/plugins/**/node_modules/**

!.obsidian/plugins/cmdr/
.obsidian/plugins/cmdr/*
!.obsidian/plugins/cmdr/data.json

```

### Operating system

Android

### Installation Method

None

### Plugin version

2.20.3

**Comment by Vinzent03** [comment]
The issue is that the underlying isomorphic-git library tracks the data.json file as ignored. From the .gitignore spec, it looks like your .gitignore is not valid, right? I see that native Git does what you expect, but it looks like it's not following the spec?

> An optional prefix "!" which negates the pattern; any matching file excluded by a previous pattern will become included again. It is not possible to re-include a file if a parent directory of that file is excluded. Git doesn’t list excluded directories for performance reasons, so any patterns on contained files have no effect, no matter where they are defined.

**Comment by mwoz123** [comment]
I'm not sure if this applies to my config. 
I'd rather say this config is not "re-including" file as the parent directory hasn't been excluded. 


It only exclude files (`/*`) that are located in (`!` ) not git ignored parent folder. 
And then not (`!`) gitignore (remove from excluded) `data.json` file.

**Comment by mwoz123** [comment]
I changed git ignore file to :
```
.obsidian/*

!.obsidian/hotkeys.json
!.obsidian/appearance.json

!.obsidian/plugins/cmdr/data.json
```

(Which shouldn't fall into re-include uncertainty) but still on Android it generates and push the empty commit messages

**Comment by mwoz123** [comment]
I was able to find a working `.gitignore` version, on which Obsiadin Mobile, doesn't push/generate empty commits, 
and is able to stage, commit and push changed config file:

```
.obsidian/*.json
!.obsidian/hotkeys.json
!.obsidian/appearance.json

.obsidian/plugins/*

!.obsidian/plugins/cmdr
.obsidian/plugins/cmdr/*
!.obsidian/plugins/cmdr/data.json

```
