### ISSUE TITLE
[Bug]: Plugin stopped reading saved passphrase from keychain

### ISSUE THREAD

**Issue by mayukhc** [denolehov/obsidian-git#539]
### Describe the bug

I use [keychain](https://wiki.archlinux.org/title/SSH_keys#Keychain) to save SSH passphrases, so after entering only once per login, every program can use it. It used to work perfectly with obsidian-git, however since last month or so, I am getting constant passphrase prompts, even though key is already in keychain and pull/push is working normally via terminal. 

I have tried deleting and re-installing the plugin. Also deleted and let Obsidian recreate the $USER/.config/obsidian folder, but didn't help.

### Relevant errors (if available)

```shell
debug1: Server accepts key: /home/adminm/.ssh/id_ed25519_cshark_gitea ED25519 SHA256:b5RRawomkBCKnFX3gAZlZnjIn/UEgO2MO2VKNC3zQvk explicit
debug3: sign_and_send_pubkey: using publickey-hostbound-v00@openssh.com with ED25519 SHA256:b5RRawomkBCKnFX3gAZlZnjIn/UEgO2MO2VKNC3zQvk
debug3: sign_and_send_pubkey: signing using ssh-ed25519 SHA256:b5RRawomkBCKnFX3gAZlZnjIn/UEgO2MO2VKNC3zQvk
debug1: read_passphrase: can't open /dev/tty: No such device or address
```

### Steps to reproduce

1. Create SSH key with passphrase and add it as auth to a remote repo (github etc) containing a Obsidian vault.
2. Load the SSH key to keychain with `keychain --eval`. Verify with `keychain -l`
3. Try to pull/push from the vault using terminal and Obsidian-git.  

### Expected Behavior

Obsidian git uses the saved passphrase.

### Operating system

Linux

### Installation Method

AppImage

### Plugin version

2.20.3

**Comment by Vinzent03** [comment]
I'm pretty sure I've changed nothing that could affect this. So maybe something changed on your end? Some classic issues are access rights on config files. Otherwise I don't know how to help, sorry.

**Comment by jeffscottward** [comment]
?? completed?

**Comment by mayukhc** [comment]
It was a config issue on my side, unrelated to plugin.
