### ISSUE TITLE
[Bug]: Selection file in (history view)

### ISSUE THREAD

**Issue by 7Codez** [denolehov/obsidian-git#545]
### Describe the bug

The selection box disappears when selecting a file from the history view list in Obsidian (Android system).

I mean when we select one of the lines(file) in the history view. We return to the comparison and once again open another file from (histore view). We find that it has disappeared from (selection box disappears), which we opened a while ago.

And the second suggestion: Please change the address. When we select one of the files from the list (histore view). The name of the list title is not changed to the name of a specified file.
For example, its name (date). Let her name appear. Because in phones, side menus disappear and someone gets confused.
Solution: Consider these suggestions, thank you.

### Steps to reproduce

up

### Operating system

Android

### Installation Method

None

### Plugin version

2.19.0

**Comment by Vinzent03** [comment]
I have no idea what you mean with selection box, but for me everything works as expected. Please update the plugin to the latest version and try again and maybe show some screenshots.
