### ISSUE TITLE
Valid git repository not found

### ISSUE THREAD

**Issue by jorgb** [denolehov/obsidian-git#55]
Hi, I am using an indirect git repository. This means my git folder itself is not stored in the obsidian folder but outside. This worked well in the past, and also works with the git client and SourceTree (atlassian product). 

It means there is a textfile in your folder called .git (not a folder) in which a redirect link is located. The contents of that file is:
```
gitdir: C:/Users/ZZZ/Documents/repos/Obsidian.git
````
This worked in the past, and is broken now, I assume there is a check before push if the .git folder is there? It does not have to be, it can also be a file.

It would be great if this can be fixed.

**Comment by Vinzent03** [comment]
So the `Obsidian.git` folder is your actually git folder? And that's your root repo?

**Comment by Vinzent03** [comment]
Fixed in new [release](https://github.com/denolehov/obsidian-git/releases/tag/1.6.1)

**Comment by jorgb** [comment]
> So the `Obsidian.git` folder is your actually git folder? And that's your root repo?

Yes but I am using the git repository directory option to specify my git files outside the obsidian directory since I am syncing the obsidian files to Google Drive and I don't want to sync all git files too. It is a nifty option to keep your working folder clean.

**Comment by Vinzent03** [comment]
Thanks for the tip. Had exact that problem too.
