### ISSUE TITLE
[BUG] Self-Signed Certificate Error On Mobile

### ISSUE THREAD

**Issue by gr4ysku11** [denolehov/obsidian-git#552]
When dealing with self-signed certificates (for example from a self-hosted gitlab server), the app won't sync properly stating:
`Error: Request Failed. SSLHandshakeException java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.`

native git has the `-c http.sslVerify=false` option but I'm not sure if isomorphic-git can do this...

**Comment by Vinzent03** [comment]
I don't know that well, but I don't think this is specific to git/isomorphic-git here, but rather the http client used. I'm using a method provided by Obsidian, which doesn't support any settings like this, so I don't think there is a way to fix this.

**Comment by tomaszduda23** [comment]
Old feature request related to this https://forum.obsidian.md/t/feature-request-allow-user-supplied-root-certificates-weaken-security/26764. It looks that policy won't be changed any time soon. User defined CA certificates works in all apps which I tested so far: e.g. bitwarden, home assistant, gitnext.
@Vinzent03 would it be possible to allow user to add CA or self signed certificate in plugin settings?

**Comment by Vinzent03** [comment]
As I said in my previous comment I'm very sure I can't configure this. Even if I could, I would follow the recommendation from the forum post and not implement it.
