### ISSUE TITLE
Using obsidian-git as a git front-end / editor in Obsidian

### ISSUE THREAD

**Issue by mirek186** [denolehov/obsidian-git#556]
Is there a plan to use the Obsidian Git source view as a Git front-end? I often have to manage docs for various projects. It's easier for me to keep them inside my vault, and I would love to push those changes from Obsidian as well. At the moment, the source is only available for the Obsidian repo but it looks like all the code is there, and there could be a switch, or the source tree could just look for any folder where there is a .git and process that.

**Comment by Vinzent03** [comment]
> At the moment, the source is only available for the Obsidian repo

What do you mean? The plugin works in every vault.
