### ISSUE TITLE
FR: XX Ahead / XX Behind of remote branch (Mobile info)

### ISSUE THREAD

**Issue by mwoz123** [denolehov/obsidian-git#557]
On mobile, I'm missing information whether my local branch is behind or ahead of remote branch.
As there's no status bar on mobile this information is missing :( 

As the space on mobile is limited, 
I was wondering if it could be at least visualized by (background) coloring "Pull" or "Push" icons?

**Comment by mwoz123** [comment]
Actually this information should be already in status bar for desktop. So would be good to have it also somewhere in mobile

**Comment by Vinzent03** [comment]
I'm not frequently running `git fetch`, so I don't know when new commits are available to pull, and I'm unsure I want to add this. But I agree that the information whether a push is possible or not should be visible.
I currently have the following implemented. I'm not using a background, because it looks like the button would somehow be hovered or selected. What do you think? I'm unsure if I want to include this in desktop as well or not.

![image](https://github.com/denolehov/obsidian-git/assets/63981639/870d87c7-508d-4083-a194-d3a0e5d88b93)

**Comment by mwoz123** [comment]
Well, I'm also not fetching too much, but already had couple situations when running pull failed (due to changes in same file), so git knew it was behind origin (and it was visible in termux git commandline), but it wasn't visible in obsidian-git. 

Due to not merged remote changes push was blocked.
But this couldn't be known without looking to termux git:/

I'm not insisting to indicate it by background color... 
Maybe a number next to icon then ? just as it is with "Recently pulled files" ?

**Comment by Vinzent03** [comment]
I won't add a number in that ui, because that's too much. I will add a fetch command. You can then see exactly where you are by looking at the history view, which is a basic git log. It should show you which commit the remote is on.

**Comment by mwoz123** [comment]
Thanks for you change, but could we get (in UI) information that something hasn't been pushed yet?

Don't know why but example from last hour: for 20minutes I was waiting for Android obsidian-git (v2.22.0) to push changes to remote (which didn't happen). 

In UI it wasn't visible I was ahead of remote all this time.
While checking in termux it turned our that I was 3 commits ahead and had 2 unstaged files that should have been committed.

After doing refesh in UI, it found the changes but still wasn't willing to add them to staged, even after pressing "+" button (I was waiting for it ~15 min to be staged but it also didn't happen). 

While termux git add, commit, and push - didn't had any issues with doing that (even pull was not required).

I've auto backup every 1 minute, auto pull every 3 minutes. I'm on Samsung Galaxy s22 which seems to have quite good processor. I've 213 note files inside 25 folders so probably not so much?

**Comment by Vinzent03** [comment]
I don't know what exactly happened in your case, but showing that commits are ready to be pushed was added in `2.21.0`. It highlights the push button in the source control view.

**Comment by mwoz123** [comment]
> I don't know what exactly happened in your case

sure it was just to ilustrate the need of that change ;) 

> but showing that commits are ready to be pushed was added in 2.21.0

Oh to be honest I didn't even spot it was implemented :/ sorry :/

The reason behind that is I'm using light theme and on it, it's really hard to spot the difference between normal font color and the accent one. 
Is there a change for a more contrasted font color for light theme? 

It's way better contrast on the dark ones...
