### ISSUE TITLE
More customizability for commit messages

### ISSUE THREAD

**Issue by wobbba** [denolehov/obsidian-git#559]
It would be very nice to have both commit headings and multiline commit messages. #157 claims that this is implemented but I cannot replicate it and do not see how it would be from the linked code.

To be more precise: I mean multi-line when adding a custom commit message to the backup ("Create backup with specific message"). I want to be able to have multiple lines so I can do bullet lists and such. An easy fix would be to use shift+Enter to create a newline, enter alone can still initiate the action.

With commit headers I mean just that. Apparently it is just as easy as using -m twice. More info here: https://stackoverflow.com/a/40506149

**Comment by Vinzent03** [comment]
I see the issue. For now you can use the source control view to manually stage, commit and push your files with a custom message.

**Comment by Vinzent03** [comment]
The modal from Obsidian I'm using doesn't support multiline, so I just suggest using the source control view for longer or more complex commit messages. Auto commit messages already support multiline.
