### ISSUE TITLE
provide push and pull button

### ISSUE THREAD

**Issue by linfz94** [denolehov/obsidian-git#56]
Dear developer, i think it will better to provide buttons for push and pull on the right side bar.

**Comment by Vinzent03** [comment]
What do you mean by the right side? Do you want an extra pane like backlinks or outline?

**Comment by linfz94** [comment]
yes, that is what i mean, it would be much efficient to manage my note, at the present i need always open an terminal to submit my last alternation before i shutdown.

**Comment by Vinzent03** [comment]
Oh I think you don't know Obsidian commands right? When you press `Ctrl`  + `p` a command palette should open. There you can search for `git` and should see commands for committing -> pushing and pulling. When you press `Enter` the command is called. You should get notifications, when the plugin commits and pushes/pulls

**Comment by phibr0** [comment]
The command pallete needs to be activated from the Core Plugins:
![image](https://user-images.githubusercontent.com/59741989/111970628-c31fd600-8afb-11eb-8a66-f42e61802931.png)

Otherwise you can add a Hotkey.

**Comment by linfz94** [comment]
omg,what a easy way, thank all of you.

**Comment by Vinzent03** [comment]
Almost every plugin has commands in addition to the default Obsidian ones, which can be invoked there.
