### ISSUE TITLE
[Bug]: Minor - Unpushed Commits in Status Bar

### ISSUE THREAD

**Issue by jun6lee** [denolehov/obsidian-git#566]
### Describe the bug

It shows committed pushes pending in the status bar if you hover.
Corrects itself on Obsidian restart.

### Steps to reproduce

Open Obsidian. 
Make an edit.
Let it Commit. (timed) - Git committed 1 file | Last Commit XXXX
Let it Push. (timed) - Git pushed 1 file | Last Push XXXX **(1 unpushed commits)**

Status bar shows 0 as it updates.
Hover over the 0.
Shows X unpushed commits on the tooltip.

### Operating system

macOS

### Installation Method

Other

### Plugin version

2.20.6

**Comment by Vinzent03** [comment]
I don't quite get what the issue is. You mean that after you pushed, it says you have unpushed commits? Which is of course wrong then.

**Comment by jun6lee** [comment]
Yep, exactly that.
