### ISSUE TITLE
"Corrupt loose object" error

### ISSUE THREAD

**Issue by macrospecter** [denolehov/obsidian-git#567]
I installed the plugin, which otherwise seems great, about a week ago on my work computer. To do so, I installed Git Desktop, according to [these](https://dannyhatcher.com/obsidian-git-for-beginners/) instructions; but then I ended up switching to ssh for authentication, rather than https. The plugin was saving my backups regularly and all was going well until today. Now no backups are committing and I get the error "corrupt loose object [long name with letters/numbers]" and "fatal: loose object [same name, but with a storage location] is corrupt" every time a backup would be committed according to my automation schedule. (One intervening event: over the weekend, I tried to set the plugin up on a different, synced machine at home and couldn't get it to work because I got the xcrun missing error.) 

Any ideas what could be causing this?

**Comment by Vinzent03** [comment]
Your repo is somehow broken. I suggest you to google your errors and try to resolve them. There's nothing specific I can do here.

**Comment by macrospecter** [comment]
Thank you for the response. I wasn't able to find the solution on Google, though perhaps some resources out there ([like this](https://stackoverflow.com/questions/4254389/git-corrupt-loose-object)) might help others with variations on my problem. Ultimately I just deleted the repo and created a new one, and all now works just fine.
