### ISSUE TITLE
This project is not used to its full capacity

### ISSUE THREAD

**Issue by weliii** [denolehov/obsidian-git#568]
I have tinkering with the behavior of this plugin and I believe i could write an adequate guide to have multiple backed up vaults relatively easily through 1 repository. The set up is also a little easier to understand then the currently documented one. As you can see in the screenshot provided I have my main vault saved to the repo (I also have a back up of my plugins folder in .obsidian). ~~This leaves room for many other vaults theoretically which can be created through Obsidian normally then backed up to the repo using git, which is very easy~~ not necessary due to automatic commit and push. (I would just write the whole guide but I don't want to waste my time if this has already been addressed and I am unaware.)
Let me know i should make an example?

![image](https://github.com/denolehov/obsidian-git/assets/140657993/cfb3456a-e5dc-43a4-a33c-6690656a0d25)
 edit: !! WORKING THEORY !!

**Comment by ParkerRobb** [comment]
I'd love to see a very brief overview of how you did that!

**Comment by Vinzent03** [comment]
I really don't understand your message. From what I see, you are just using the plugin as intended to back up your vault to GitHub. The [documentation](https://publish.obsidian.md/git-doc/Start+here) has been improved since your issue creation as well.
