### ISSUE TITLE
Let mobile users use private git repos

### ISSUE THREAD

**Issue by smechaab** [denolehov/obsidian-git#573]
Would be great to be able to sync mobile plugin data with private repo, and not with Github only (e.g. for local git servers). AFAIK this is not possible yet.
If maintainers are interested, I would be happy to consider adding this feature on a pull request.

Thanks

**Comment by Vinzent03** [comment]
What makes you think only GitHub is supported? Everything should work just fine. Of course you need nothing like a personal access token, but the password for you service instead.

**Comment by smechaab** [comment]
> What makes you think only GitHub is supported? 

On desktop, Obsidian retrieve the .git directory inside your obsidian tree, thus username info. However, on mobile it asks for this username ("E.g your username on GitHub") and doesn't ask for any git server target, so it looks like it doesn't work by retrieving the .git directory but instead trying to sync with GitHub. 
![image](https://github.com/denolehov/obsidian-git/assets/25881911/9c731608-278c-44cd-80a7-0e8712d8d04f)

**Comment by Vinzent03** [comment]
That username and password is used for authentication not usually not stored in your .git directory. The remote url can be specified on clone or via a command, but is also read from `.git/config`.

**Comment by smechaab** [comment]
So basically you need to have a shell on your mobile to clone your repo in the obsidian directory ? I couldn't find any working git client on play store yet. Is there a solution for mobile users that doesn't want to root or install git clients from untrusted source ?
Thanks

**Comment by Vinzent03** [comment]
There is a command to clone a repository. Just set your credentials before in the settings and then call the command and provide your remote url.

**Comment by smechaab** [comment]
> There is a command to clone a repository. Just set your credentials before in the settings and then call the command and provide your remote url.

Do you mean CLI command ?

**Comment by Vinzent03** [comment]
No a command in Obsidian. Those you run from the command palette.

**Comment by Vinzent03** [comment]
Sorry that it crashes, but that's a known issue I can't solve. Downloading the zip doesn't contain a `.git` directory, so that's not usable.

**Comment by StormLight14** [comment]
You can clone on a PC and transfer files directly
