### ISSUE TITLE
[Bug]: Doesn't commits and pushes automatically

### ISSUE THREAD

**Issue by alexcmx** [denolehov/obsidian-git#575]
### Describe the bug

Appears notification that there are no changes in repo, but actually I can make git commit and push and there is a lot of changes. Looks like plagin woks a bit strange or maybe I understand it not so well
May be it can't make commit?

![изображение_2023-08-05_162030400](https://github.com/denolehov/obsidian-git/assets/32741401/a263c4ac-771e-4630-83c1-bf7b59993439)
![image](https://github.com/denolehov/obsidian-git/assets/32741401/bb30363f-2016-469d-b761-f89d41d758c5)
![image](https://github.com/denolehov/obsidian-git/assets/32741401/368a1acc-a862-4e10-a85a-40a593a7ae8e)
![image](https://github.com/denolehov/obsidian-git/assets/32741401/56b24ce6-57e8-4322-a1ff-40f1d9fe9dd1)
![image](https://github.com/denolehov/obsidian-git/assets/32741401/06ac2a63-a65a-4a25-828d-be92f038b273)

### Steps to reproduce

I've used the guide to create repo and link it to the git. And checks connection by commit and push using command pallete in obsidian. But automatically it doesn't work.

### Operating system

Windows

### Installation Method

None

### Plugin version

2.20.7

**Comment by alexcmx** [comment]
![image](https://github.com/denolehov/obsidian-git/assets/32741401/d79c654a-00ed-49d2-97fb-fe49ff4dc31e)
This push I made manually

**Comment by Vinzent03** [comment]
Sorry, but I couldn't understand what your issue exactly is. Please describe what exactly doesn't work and what you changed in the settings.

**Comment by alexcmx** [comment]
I think the problem is in 
![image](https://github.com/denolehov/obsidian-git/assets/32741401/084fd914-e23e-4fc5-93fa-f19ca2d947fc)
 this setting. After switching it off. My vault commits and pushes correctly. But when it was switched on. Commits did't create automatically.
 Thank you)

**Comment by Vinzent03** [comment]
That setting means, you have to edit a file and stop editing any file for 5 minutes for a new commit to happen. Did you wait 5 minutes after last edit and still no commit got created?

**Comment by Mindstormer619** [comment]
Hey @Vinzent03, I'm unrelated to this issue, but got here googling to understand how this specific feature works -- does this mean that I should not be editing _any file in the entire vault_ for the duration of the timeout?

My understanding was that it would prevent committing the _current file under edit_ when the timeout struck, but would continue to add other files which got updated earlier but are not backed-up yet.

**Comment by Vinzent03** [comment]
No, your first case is the case. You have to stop editing for the specified time duration any file in your entire vault.

**Comment by DysphoricUnicorn** [comment]
I feel like the wording of this could be improved quite a lot.

From reading the help text, I had assumed that this setting makes it so that obsidian always creates a backup instantly after I'm done editing a file (which would be quite useful behavior)

Maybe you could change it to something along the lines of "Do not auto backup while editing" to make this more clear
