### ISSUE TITLE
Add notification configuration options to minimize obscuring UI on mobile

### ISSUE THREAD

**Issue by ericbiewener** [denolehov/obsidian-git#577]
When I open the app on my mobile device, the series of notifications admitted by this plugin obscures the top third of the screen for a few seconds. I'm not sure what the ideal UX would be, but introducing configuration options to mitigate this while still preserving plugins critical notification communications (eg failures) would be nice. Some possibilities that come to mind (without any knowledge of whether they are possible via the obsidian API)

1. Display only errors or a single final "success" message
2. Display all notifications but immediately remove the previous one when showing a new one so that only a single one emitted by this plugin is visible at a time

Thanks for a great plugin! I use mine for syncing between machines rather than backup and so far it has been flawless.

**Comment by Vinzent03** [comment]
Have you tried the existing option to disable notifications? It should still show errors, so exactly what you are searching for.

**Comment by ericbiewener** [comment]
Wow, totally missed this. Thanks!
