### ISSUE TITLE
Can not run git command

### ISSUE THREAD

**Issue by Saurav109** [denolehov/obsidian-git#58]
i am getting this after freshly installed obsidian-git
![2021-03-24-124257_641x406_scrot](https://user-images.githubusercontent.com/22970775/112266860-858e8a80-8c6c-11eb-8db6-e40d3ce6a9ac.png)

**Comment by Vinzent03** [comment]
Obsidian cannot access your git installation. Which OS are you on and have you read the [instructions](https://github.com/denolehov/obsidian-git#windows-installation)?

**Comment by Vinzent03** [comment]
With what method did you install Obsidian?

**Comment by echo-saurav** [comment]
ops sorry, after download flatpackref it working fine

**Comment by Saurav109** [comment]
ops sorry , after download the flatpackref version ,its working
