### ISSUE TITLE
[Feature] Git commit submodule

### ISSUE THREAD

**Issue by shlyapp** [denolehov/obsidian-git#582]
Hello!

Please add commit capability in git submodules. It is desirable that this be all automatic.

Let's say I have a private repository with a public repository submodule (for example, I maintain my wiki there). I want to have a commit function in the submodule, and then a commit in the main module with changes in the submodule.

Or is there an option to do it differently? Thank you!

**Comment by Vinzent03** [comment]
There is an option in the settings to commit everything and push in the submodule when committing all changes via command or doing backup in your vault.

**Comment by shlyapp** [comment]
Thank you!
