### ISSUE TITLE
[Feat]: *Mobile* no backup when switching to Home

### ISSUE THREAD

**Issue by amitkot** [denolehov/obsidian-git#589]
### Describe the bug

On the mobile, when switching to "Home", the app closes and git backup is not performed.

### Steps to reproduce

1. Make some change to a note
2. Move to phone "Home"

### Expected Behavior

Backup should be performed on leaving the app, otherwise the last changes will not be backed up until next time the app opens

### Operating system

Android

### Installation Method

None

### Plugin version

2.22.0

**Comment by Vinzent03** [comment]
I don't think this is possible. The backup on mobile already takes quite a while so it's not possible to do that while it's closing. And I don't think doing that in the background is possible as well. It's not even possible on desktop.
