### ISSUE TITLE
Auto-pull

### ISSUE THREAD

**Issue by xeor** [denolehov/obsidian-git#59]
I use this plugin to sync notes between multiple computers. It would be nice with an option to automatically pull changes as well as commit/push.

Now, I haveto do a change to a document, or manually call the "pull from repo" command for it to pull in new changes. It can easily cause conflicts with the workflow, since I am ending up changing a document that I have changed on another pc..

**Comment by Vinzent03** [comment]
You have already two options to 
1. Pull on Obsidian startup
2. Pull before pushing, so Commit -> pull -> push

What else do you want?

**Comment by xeor** [comment]
Thanks for the quick response..

The problem with those options is that none of them will let obsidian just sit there an get it's note updated by itself.
What I propose is to have an option, like the `Vault backup interval`, but for pulling. Alternative is to let the `backup` job pull first, even if there are no changes.

`Pull updates on startup` is nice, but I usually start obsidian very rarely :)

**Comment by xeor** [comment]
Thanks a lot!! You should get a "buy me a coffee" link in your readme and I'll get you some :)

**Comment by Vinzent03** [comment]
Thanks a lot for the tip and your support. See [README](https://github.com/denolehov/obsidian-git#tips) for the link.

**Comment by Vinzent03** [comment]
Available in new [release](https://github.com/denolehov/obsidian-git/releases/tag/1.7.0)!
