### ISSUE TITLE
Stuck at : git: Checking Repo status

### ISSUE THREAD

**Issue by phibr0** [denolehov/obsidian-git#6]
as soon as I activate the plugin it gets stuck at: ```git: Cecking Repo Status``` 
Thats the error in the Dev Console: 
 
![D-11-20-3](https://user-images.githubusercontent.com/59741989/98080501-cdf00c00-1e75-11eb-8f42-a6e6a6e0331d.jpg)

I'm using SSH instead of https, might that be a problem?
My remote origin isn't named the default "origin", i named it "remote".
The branch is called mainVault.
(So i can do: git push remote mainVault)

**Comment by denolehov** [comment]
Hello! The error says that it cannot find `git` executable. I've been just debugging very similar case yesterday, and what helped is going to your vault directory from the command line and re-initializing the git repo.

Please try it and let me know how it goes?
```bash
cd C:\path\to\your\vault
git init
```
After this, please restart the app.

**Comment by phibr0** [comment]
Still the same error..
I am using Linux if that helps

**Comment by gtrias** [comment]
I'm having the exact same error. Also in linux

**Comment by denolehov** [comment]
Could you please verify that `git` is indeed installed and is in system's `$PATH`? There also might be a directory permission issue, when process cannot access the working directory, but provided that you can save/load your vault files from within Obsidian, this shouldn't be the case. 
```bash
which git
echo $PATH
```

People who had similar issues report that reinitializing local repo (`git init`) helps. I will play around with that and push a patch version, we could try that and see if it helps.

**Comment by phibr0** [comment]
it is indeed installed and I can use it normally 
i will comment the outputs of both commands tomorrow

**Comment by xavierroy** [comment]
I get the same error in Windows. I tried the above steps. Right now, I'm pushing the files manually.

**Comment by gtrias** [comment]
I've tried to reinitialize by running `git init` again and it makes no differente.

The output of the commands is:

```
❯ which git
/usr/bin/git

❯ echo $PATH
/home/genar/.rbenv/shims:/home/genar/.yarn/bin:/home/genar/.nvm/versions/node/v14.15.0/bin:/home/genar/.rbenv/plugins/ruby-build/bin:/home/genar/.rbenv/bin:/home/genar/.cargo/bin:/home/genar/.npm-global/bin:/home/genar/go/bin:/home/genar/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/genar/src/android-sdk-linux/tools:/home/genar/src/android-sdk-linux/platform-tools:/bin:/home/genar/go/bin:/home/genar/Android/Sdk/platform-tools:/home/genar/Android/Sdk/tools
```

I can use git with no problems in terminal.

**Comment by denolehov** [comment]
@gtrias Yeah, your binary seems to be ok. Honestly, I am not sure why Obsidian process does not have access to `git` executable.
Could you double check directory persmissions? Is it read-only/write-only by any chance?

**Comment by sanjeed5** [comment]
> I get the same error in Windows. I tried the above steps. Right now, I'm pushing the files manually.

Same case with me. I tried re-initializing like given above. Still stuck on git: checking repo status..

**Comment by weiss-d** [comment]
Hi! I've got this problem too on Pop!_OS 20.04. Obsidian is installed via `Flatpak`.
First the error message was the same as @phibr0 has. I thought it might be a permission issue, so I used `Flatseal` to make a risky thing: give the Obsidian permission to all system files:
![image](https://user-images.githubusercontent.com/62437174/98377913-6e9d2200-2056-11eb-84b8-47cb44281f8c.png)

After that the error changed, and now it looks like this:
![image](https://user-images.githubusercontent.com/62437174/98378088-a1dfb100-2056-11eb-801f-e4c4a7ac1f37.png)

I'm not into JS, but I can perform some additoinal actions and post results here if needed.

**Comment by denolehov** [comment]
hey @weiss-d, it looks like the same error to me - `Error: spawn git ENOENT`, which indicates that Obsidian process cannot access `git` executable. The official [troubleshooting section](https://github.com/steveukx/git-js#every-command-returns-enoent-error-message) of the underlying lib that talks to `git` for this kind of error indicates two possibilities:
- `git` binary isn't available to the user running the Obsidian process
- vault directory isn't read/write accessible by the user running the Obsidian process 

GIven that directory permissions are fine and you can use `git` commands from command line, I am not sure what could be the problem :/ I will let you know if I stumble upon a solution for this.

**Comment by phibr0** [comment]
Since it seems to be an issue with Obsidian (at least thats what i think) i contacted the Obsidian Team, maybe they can help

**Comment by denolehov** [comment]
Good idea, even though it's probably not related to Obsidian itself, they might point out something obvious that we're missing.

**Comment by Goetterwind** [comment]
Maybe it is not related to the issues above, but I was stuck at the "Checking repo status" as well.

My solution was to add .gitignore and manually pull it. Obviously the .gitignore is needed...

**Comment by weiss-d** [comment]
> Maybe it is not related to the issues above, but I was stuck at the "Checking repo status" as well.
> 
> My solution was to add .gitignore and manually pull it. Obviously the .gitignore is needed...

I also have `.gitignore` file, but this make no difference in my case.

**Comment by phibr0** [comment]
also have one
doesnt make a difference to me

**Comment by monishkumar7** [comment]
I have the same issue "git: checking repo status" even after reinitializing the git repo in the folder.

If I change the automatic backup time to 1 min, it works. I then reset it to 60 and it continues to work until my computer goes to sleep.

**Comment by Goetterwind** [comment]
What message do you get when you open the console (using ctrl+shift+i)? Maybe you are stuck somwhere with git and it throws back some issues.

**Comment by weiss-d** [comment]
> I have the same issue "git: checking repo status" even after reinitializing the git repo in the folder.
> 
> If I change the automatic backup time to 1 min, it works. I then reset it to 60 and it continues to work until my computer goes to sleep.

@monishkumar7 and where are these options in your case? I didn't find any tab for this plugin in Obsidian settings window.

**Comment by monishkumar7** [comment]
> > I have the same issue "git: checking repo status" even after reinitializing the git repo in the folder.
> > If I change the automatic backup time to 1 min, it works. I then reset it to 60 and it continues to work until my computer goes to sleep.
> 
> @monishkumar7 and where are these options in your case? I didn't find any tab for this plugin in Obsidian settings window.

Under the plugin options. It showed up for me only after I initialized a git repo in my vault. 

![image](https://user-images.githubusercontent.com/9054287/98958286-2192d300-24d0-11eb-80f2-f9c379c5d6bc.png)

**Comment by denolehov** [comment]
Hey people, whoever is on Windows - please try installing [official git for Windows](https://git-scm.com/download/win), some people report that it solves their problems with the plugin.

**Comment by inputsh** [comment]
Same issue here on Linux.

My suspicion is that this is somehow related to Obsidian being installed via flatpak. The plugin used to work just fine for me, and I recently switched from AppImage to flatpak.

**Comment by phibr0** [comment]
Snap doesnt work either..

**Comment by Ghost-Coffee** [comment]
I'm on Pop_OS! and installed with Flatpak, I found that it does work if you start obsidian from the command line.
```bash
/home/$USER/.local/share/flatpak/app/md.obsidian.Obsidian/current/active/files/obsidian 
```

**Comment by weiss-d** [comment]
> I'm on Pop_OS! and installed with Flatpak, I found that it does work if you start obsidian from the command line.
> 
> ```shell
> /home/$USER/.local/share/flatpak/app/md.obsidian.Obsidian/current/active/files/obsidian 
> ```

That's interesting. I started the Obsidian this way and it asked me to make or open a vault like there have never been one.

Then I selected 'Open' and pointed it to the repo dir. The vault opened, I enabled Git plugin and there a tab for its configuration appeared in configuration window.

No username or password fields were in settings. I set it to pull changes on startup and sync every minute after, and restarted Obsidian. After this restart the plugin configuration tab disappeared and the status hanged on `git: pulling changes...`.

I restarted it once again, and configuration tab was there. I looked into the terminal from which it was started and saw a prompt to enter Github login and password.
After entering them, the status changed to `git: last update 1 minute ago...`. Then after a minute it asked for Github login in the terminal once again, and then every minute.

**Comment by denolehov** [comment]
@weiss-d to permanently cache the credentials run:
```bash
git config --global credential.helper store
```
after that it should stop asking for credentials

**Comment by weiss-d** [comment]
@denolehov thanks, that makes sense! :)

As for successful work only after launching as a binary file, looks like it might be a `Flatpak` issue.

Maybe @joshua-stone, who's the main contributor to Obsidian Flatpak package, may help somehow?

**Comment by joshua-stone** [comment]
@weiss-d @Ghost-Coffee @inputsh @phibr0 [I've made a change to the Obsidian flatpak by bundling `git`](https://github.com/flathub/md.obsidian.Obsidian/commit/de18cbed20463ad0408719578f6c68e98a318673). I think a more ideal solution would be to package git and other common binaries required by third-party plugins until a Plugins runtime extension, but for now this is a quick fix that'll hopefully address this issue.

Simply update and reset any permissions overrides you set before restarting Obsidian:
```
$ flatpak update md.obsidian.Obsidian
$ flatpak override --reset md.obsidian.Obsidian
$ flatpak run md.obsidian.Obsidian
```

Let me know if you still have issues with git!

**Comment by phibr0** [comment]
Thank you!
it works fine

**Comment by weiss-d** [comment]
@joshua-stone, big thanks!

**Comment by DBreitigan** [comment]
I'm having the same issue -- I tried `git init` in the directory, along with verifying git was on my path. I'm having this issue on Mac. 

Strangely, I have this working fine on my other macbook. The only real difference between the two is that the MacBook that this is working on is on Catalina, and the one it is not working on is on Big Sur.

**Comment by DBreitigan** [comment]
Strangely enough, opening obsidian via the command line with `open -a obsidian` made everything work. I'm no sure how to make this work when opening obsidian via the GUI though.

**Comment by lsilvam** [comment]
> Hey people, whoever is on Windows - please try installing [official git for Windows](https://git-scm.com/download/win), some people report that it solves their problems with the plugin.

I am still facing this issue :/ hope it can be fixed somehow

**Comment by lsilvam** [comment]
> > Hey people, whoever is on Windows - please try installing [official git for Windows](https://git-scm.com/download/win), some people report that it solves their problems with the plugin.
> 
> I am still facing this issue :/ hope it can be fixed somehow

I manage to open and launch the plugin by having this option:
![path_git](https://user-images.githubusercontent.com/53966548/100637838-3f16c800-332b-11eb-916b-a49c9014dcec.png)

but when I tried to push it gave me this error, and the plugin does not launch:
![obsidian_git_error](https://user-images.githubusercontent.com/53966548/100638084-81400980-332b-11eb-97ba-06a4d0bd0bfc.png)

I tried to `git init` but did not solve it. before it crashed I used the command in obsidian to push, after setting the time interval to sync. 
Any ideas on what is going on here? Thank you

**Comment by inputsh** [comment]
@lsilvam From that error message, it looks to me like you've cloned your repository using HTTPS instead of using SSH. Use SSH instead, since the plugin can't ask for your username/password.

Here's GitHub's docs on how to do that: https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/connecting-to-github-with-ssh

**Comment by lsilvam** [comment]
> @lsilvam From that error message, it looks to me like you've cloned your repository using HTTPS instead of using SSH. Use SSH instead, since the plugin can't ask for your username/password.
> 
> Here's GitHub's docs on how to do that: https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/connecting-to-github-with-ssh

I tried but I am having an issue somewhere that I can't solve; it works with git/CMD but does not work with Obsidian Git nor with Github Desktop.
The ssh agent seems to have the keys, on the Web I can see that they were successfully used; but only when I use the CMD line.
Ah, and the 'git remote - v' shows the correct url...

**Comment by Vinzent03** [comment]
Linux problems should be fixed by the flatpak changes. Snap versions should be working with `--classic?`? Windows problems should be fixed by installing git with `3rd-party software` access enabled. Authentication issues are another problem. See #23

**Comment by fahmifan** [comment]
> Strangely enough, opening obsidian via the command line with `open -a obsidian` made everything work. I'm no sure how to make this work when opening obsidian via the GUI though.

Is it still working on the obsidian v0.12.12 ? 

I got this error from the DevTools
```
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.
```

**Comment by Vinzent03** [comment]
@fahmifan Can you try running `git push` without extra arguments from the terminal in your vault? It should prompt you a command to set the tracking branch.

**Comment by fahmifan** [comment]
@Vinzent03 this is the output
```
➜ git push
fatal: The current branch master has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin master
```

**Comment by Vinzent03** [comment]
> It should prompt you a command to set the tracking branch.
tracking branch is like upstream branch. Just run this command

**Comment by fahmifan** [comment]
@Vinzent03 thanks it works!

**Comment by harsha-kadekar** [comment]
I had the similar problem in my Ubuntu 20. The error in the debug log said `spawn git ENOENT`. I was able to use git via terminal and verified git binary path was in `$PATH`.  I had installed obsidian using snap package. I uninstalled obsidian and installed it using deb file. After that it started working.
