### ISSUE TITLE
When the local repo has multiple remotes, it concats them as one and push fails

### ISSUE THREAD

**Issue by samxsmith** [denolehov/obsidian-git#60]
Until recently this plugin has worked amazingly, so thank you !!

I added a second remote repo for a specific use case, and now the plugin errors.

example:
```
$ git remote
gitlab
github
```

When the plugin attempts to push I get the following error:
`Pushing to gitlab origin fatal: 'gitlab github' does not appear to be a git repository`

It is concatenating the two remotes. I glanced briefly at the code and can see no explanation.
Is it possible this is a bug with `simple-git` ?

**Comment by Vinzent03** [comment]
If you run `git status` what remote does it compare to? Should be the second line in output.

**Comment by samxsmith** [comment]
It compares to `origin`

**Comment by samxsmith** [comment]
Worth noting that pushing to both manually works fine.
Can't quite see how the plugin reads in the remote, but I guess it is just reading both and assuming a single string.

**Comment by Vinzent03** [comment]
Your output of `git remote` is `gitlab`and `github`? I think this does not make sense if your branch compares to `origin`. If you run `git remote get-url gitlab`. Is the output correct? It should push/pull to the upstream branch.

**Comment by samxsmith** [comment]
No sorry my description was just an example. My remotes are called `origin` and `wiki`

**Comment by samxsmith** [comment]
I can confirm that pushing to both remotes manually works fine. The plugin also works perfectly with just one remote

**Comment by Vinzent03** [comment]
If you run just `git push`(no extra arguments). Does it work?

**Comment by samxsmith** [comment]
It does yep, it pushes to origin by default

**Comment by samxsmith** [comment]
This is definitely related to the plugin, or its simple-git dependency.
I would imagine that one of them is calling `git remote` and assuming only a single name returned.

**Comment by Vinzent03** [comment]
I cannot reproduce. Can you please run `git push --set-upstream origin master` again?

**Comment by samxsmith** [comment]
```
λ git branch -vv
* master 5c9b539 [origin/master] vault backup: 2021-03-31 17:49:14
```

**Comment by samxsmith** [comment]
I am an update behind on the plugin. If you can't reproduce then it could be that this occurred in an older version of simple-git. If this doesn't fix I'll start adding logs.

**Comment by samxsmith** [comment]
Aha! Yes the update has solved the issue. Sorry to have bothered you !

Appreciate your work on the plugin, couldn't use Obsidian without it.
If you ever need help maintaining, give me a shout.

**Comment by samxsmith** [comment]
![image](https://user-images.githubusercontent.com/68220350/113183513-05f45300-924c-11eb-8d49-f9f3f26b02eb.png)

Yep, `1.5.0`

**Comment by Vinzent03** [comment]
Okay that explains it. A lot has changed since then.

**Comment by samxsmith** [comment]
Rookie error not checking the version first, my apologies

**Comment by Vinzent03** [comment]
No problem! Should have asked too.
