### ISSUE TITLE
[Bug]: Fatal Detected Dubuious Ownership

### ISSUE THREAD

**Issue by rxerium** [denolehov/obsidian-git#614]
### Describe the bug

![image](https://github.com/denolehov/obsidian-git/assets/59293085/e896b1b5-2a76-4787-9dc6-f5412af582b6)
Hello, I would like to backup my vault to a github repo however I have the follow error:

### Steps to reproduce

Not entirely sure, this issue started occurring out of the blue last week. 

### Expected Behavior

The vault should backup without any issues.

### Operating system

Windows

### Installation Method

None

### Plugin version

2.22.0

**Comment by Vinzent03** [comment]
That's not an issue with this plugin. Somehow your user id has changed. But this is system level. Pease run the command provided in the error message in the terminal. But your repo is not stored locally, but on some server?

**Comment by rxerium** [comment]
I forgot to mention I did run the command but the issue persists (even are reinstalling the plugin). Yes, that is correct my vault is stored on my NAS server. I understand this is not an issue with the plugin but any guidance is appreciated. Thanks

**Comment by Vinzent03** [comment]
Hmm I don't know how to fix that as I have no experience with that. Maybe ask on stackoverflow or some other git forums.

**Comment by jippy89** [comment]
By the way, for people who got this problem, I solved this by initiating the `git` using the Command Prompt from the Obsidian itself. Add my remote repository, then tried to push it myself. And it worked.

I'm on Windows 11, saving my stuff using SSH on my personal laptop if anyone wondering.
