### ISSUE TITLE
Feature Request: Use git mv when moving or renaming notes

### ISSUE THREAD

**Issue by kalitara** [denolehov/obsidian-git#62]
When files are moved or renamed with Obsidian, git sees them as being simply deleted and recreated--losing all revision information.

If the hooks are available, it would be nice to have this plugin use git mv when Obsidian performs a move or rename operation on a note.

**Comment by Vinzent03** [comment]
That's normal git. If you run `git add .` and look again in Obsidian or run `git status` you see it detects the rename.

**Comment by drozzy** [comment]
I didn't even know `git mv` existed lol. Been doing git add all my life and it detects renames.

**Comment by Vinzent03** [comment]
@kalitara Can I close this? Or do you have further questions?

**Comment by kalitara** [comment]
Yes. Go ahead and close. I just verified for myself that "git add ." does identify files that were renamed. I was looking at git status before running add.

Thank you.
