### ISSUE TITLE
Feature Request: "Commit all and push" command

### ISSUE THREAD

**Issue by TylerR909** [denolehov/obsidian-git#620]
I have my timer set pretty high (~2-5m) before the plugin will commit and push, but when I know I'm about to close-out for the night it'd be nice to be able to do that with a single "Commit all staged and push" command. Heck I'd even remap Ctrl+S to that in a heartbeat.

**Comment by Vinzent03** [comment]
In this plugin the term "Backup" mostly refers to exactly this. So you should be able to do that with the backup command. I think there is a setting to disable push on backup, but as long as you configured it correctly, it should do exactly that.

**Comment by TeemuSailynoja** [comment]
> In this plugin the term "Backup" mostly refers to exactly this. So you should be able to do that with the backup command. I think there is a setting to disable push on backup, but as long as you configured it correctly, it should do exactly that.

Thank you for clarifying this.
