### ISSUE TITLE
[Feature]: Add ability to see Diff Views

### ISSUE THREAD

**Issue by mahyarmirrashed** [denolehov/obsidian-git#626]
I'm wondering if there is an ability to see diff views for files similar to how https://github.com/ivan-lednev/obsidian-automatic-changelog has it. Buttons to select which rev you want would be great too.

**Comment by Vinzent03** [comment]
As shown in the [README](https://github.com/denolehov/obsidian-git?tab=readme-ov-file#available-commands), there is a command to open the diff of the current file. Additionally, you can open the diff of any changed file in the source control view (which can be opened with a command).

**Comment by mahyarmirrashed** [comment]
You're correct, would this also work when trying to resolve rebase merges? Like, would it show me what is being added from which branch?

**Comment by Vinzent03** [comment]
I haven't tested this, so I don't really know.

**Comment by mahyarmirrashed** [comment]
Tested this, the answer is no:
<img width="1185" alt="image" src="https://github.com/denolehov/obsidian-git/assets/59240843/1dd36c68-567b-457c-8ba5-92b1291c8cef">

**Comment by mahyarmirrashed** [comment]
In this case, it would be great if we could have a resolution feature for rebase changes. I'm not sure how out-of-scope or niche that is for a project like this but, it would be a good feature to have.

**Comment by Vinzent03** [comment]
Building a merge/rebase conflict resolve view is out of scope for now. I suggest you to open the file in source mode and solve the conflict yourself.
