### ISSUE TITLE
[Bug]: Branching might need some working

### ISSUE THREAD

**Issue by SrGeneroso** [denolehov/obsidian-git#634]
### Describe the bug

_note: I know to use git for everyday use in cli and vscode, but I'm testing this plugin to teach somebody with less expertise_
### Switching branches
When I try to change branches I get this message: It seems workspace.json has changed 
<img width="396" alt="image" src="https://github.com/denolehov/obsidian-git/assets/5541794/fec48b86-202f-47c9-9d48-7f19ac30cc63">
which could be potentially avoided by adding the file to the [gitigonre](https://publish.obsidian.md/git-doc/Tips-and-Tricks)
but I argue that if the options are to commit or stash it maight be nice to have a prompt to do one of those.
Talking about it, in the side panel nor the command palette  give the choice for stashing
<img width="221" alt="image" src="https://github.com/denolehov/obsidian-git/assets/5541794/3c0a6e8a-d830-4553-a0be-4c14f218655f">
<img width="398" alt="image" src="https://github.com/denolehov/obsidian-git/assets/5541794/92dfc3ca-3753-4e16-b601-ea2370a84071">

### featuring Branches
Since the plugin support branches, and moreso, let's you create them, it looks like I can't not backup if the branch is not created in the repo. ![Obsidian_GI7ZlhrnPl](https://github.com/denolehov/obsidian-git/assets/5541794/f2d43135-a1f6-403d-a9bd-7ec95182bf77)
It happens both with the sidebar and the command palette. When using backup button in the main branch, which is created, it makes the commits and then push. I think this behaviour can be misleading for users.
Might be possible to create remote branchs instead of local ones? You can switch to those so maybe.

### Steps to reproduce

Not applicable, Should this be a discussion instead?

### Addition context

Sorry I have so many plugins 

SYSTEM INFO:
	Obsidian version: v1.4.16
	Installer version: v1.4.16
	Operating system: Windows 10 Pro 10.0.22621
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 21
	Plugins enabled: 19
		1: Typing Assistant v0.2.1
		2: QuickAdd v1.4.0
		3: Iconize v2.6.1
		4: Excalidraw v1.9.26
		5: Dataview v0.5.61
		6: Advanced Tables v0.19.1
		7: Kanban v1.5.3
		8: Calendar v1.5.10
		9: Tasks v5.0.0
		10: Templater v1.16.4
		11: Advanced Slides v1.20.0
		12: Obsidian Git v2.22.0
		13: Thumbnails v1.3.0
		14: YTranscript v0.9.1
		15: Convert url to preview (iframe) v0.5.0
		16: Buttons v0.4.19
		17: Commander v0.5.1
		18: Code Editor Shortcuts v1.14.0
		19: Better CodeBlock v1.0.8

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

### Operating system

Windows

### Installation Method

None

### Plugin version

2.22.0

**Comment by chrda81** [comment]
+1 for the **stash** and **stash pop** feature

For example: 
- I rename a file on my mobile and push the changes
- I left Obsidian open on my notebook without automatic pull and editing the file, I had renamed above
- backup and push my changes won't work, so I cannot resolve the conflict without using git on command line

Or do I miss something?

**Comment by SrGeneroso** [comment]
cleaning issues, hope this got seen 😘
