### ISSUE TITLE
Feat: Local-only mode that never does any pushes, pulls, ect.

### ISSUE THREAD

**Issue by jboxman** [denolehov/obsidian-git#638]
I have `git-annex` setup to automatically sync my files between local systems whenever a commit happens. It would be great to handle commit messages and look at diffs within Obsidian, rather than using the CLI and VSCode for this, but it seems to want to run a push or a pull when I change files. (My laptop is closed, so an error is returned from `git-annex` via `git`; this is to be expected because the `git-annex` agent runs in the background and syncs whenever other systems are reachable.)

Thanks!

**Comment by kg4zow** [comment]
You might be able to set up a "remote" in another directory on the same machine and *let* it push/pull.

* In the other directory, `git init --bare`
* In the vault's directory, `git remote add origin file::///path/to/bare/repo` and `git push -u origin branchname`
    * careful, the URL has *three* `/` in a row - two are part of the `file://` scheme, and the third one starts an absolute path name ... for me the actual URL was `file:///Users/jms1/git/zdummy`

After this, the `git push`, `git pull`, and other such commands that it insists on doing, will be "pushing" to another directory on the local machine.

Disclaimer: this *should* work, but I haven't tested it. I just started using Obsidian a week ago, *tried* this plugin for the first time earlier today, and still don't have it working yet. It's entirely possible that the plugin assumes a need for authentication which wouldn't exist with a `file://` URL (or in my case, a `keybase://` URL).
