### ISSUE TITLE
Running obsidian git on a different mac I get xcrun error

### ISSUE THREAD

**Issue by drozzy** [denolehov/obsidian-git#64]
Just moved to a different mac and I get this error coming up every time I start obsidian and obsidian-git does a sync:
<img width="304" alt="Screen Shot 2021-04-08 at 8 17 42 PM" src="https://user-images.githubusercontent.com/140710/114111330-cbbc2e80-98a7-11eb-8f9d-83ff652dbbdb.png">

I know it is the plugin because if I disable it and start obsidian without it, the error does not appear.

Appreciate any advice. Thanks guys.

P.S.: Do you take donations?

**Comment by drozzy** [comment]
That fixed it. Cheers! ☕️

**Comment by aaronyih1** [comment]
Is it possible to use this plugin without having to install the entirety of Xcode? My mac is low on space, and I can't spare 25GB just to get this plugin working.

**Comment by Vinzent03** [comment]
@aaronyih1 Sure you can. You may need to specify directory of the git binary in the settings. See [this discussion](https://github.com/denolehov/obsidian-git/discussions/358) for additional context.

**Comment by macrospecter** [comment]
I have the same issue as the poster above: I'm trying to get the plugin working on a laptop with minimal space and don't want to download Xcode. I went to the discussion above, though, and I'm not sure how to "specify the directory of the git binary" in the settings. I see the field to do this. But could someone explain to a newbie what the syntax would be/how I figure out the path to git? Thanks!

**Comment by benf2004** [comment]
@macrospecter this is a bit late, but if you open up terminal and type `which git` it will give the path to git on your machine.

**Comment by macrospecter** [comment]
Thank you! I did manage to figure out how to run git without Xcode and without changing the directory (by just installing the command line tools, without the whole Xcode).
