### ISSUE TITLE
Idea: Option to toggle Git Pull at startup of Obsidian on and off

### ISSUE THREAD

**Issue by frankhommers** [denolehov/obsidian-git#645]
This would be awesome, because I have the interval turned of, but when I am starting to work on another device I sometimes forget and get merge conflicts.. This would prevent it.

**Comment by Siete-F** [comment]
He @frankhommers, can you explain what this differs from the second "highlighted feature" :D

It seems that it is already supported:

> Pull changes from remote repository on Obsidian startup

**Comment by frankhommers** [comment]
Nothing. I read past it I  guess!
