### ISSUE TITLE
[Feature]: Button/Setting for "git commit --amend" 

### ISSUE THREAD

**Issue by RiverOmega** [denolehov/obsidian-git#648]
### Feature

As of now (I think), it's not possible to perform the equivalent of "git commit --amend" via the interface. I would love a button or checkbox close to the "Commit-button" that gives me the option to amend to an existing commit instead of always creating new ones. I share my vault via git with others, and to keep the history clean, amending is a great tool.

**Comment by RiverOmega** [comment]
I realise the formatting is that of a Bug-report, but I couldn't find other templates when using the "New Issue"-button.

**Comment by ParkerRobb** [comment]
I too would love this feature

**Comment by Vinzent03** [comment]
There is now a commit amend command
