### ISSUE TITLE
Under Windows, getting "You need to add your personal github access token in settings"

### ISSUE THREAD

**Issue by mrrcollins** [denolehov/obsidian-git#649]
I already had installed git, set up my ssh keys, and was able to git pull/push on my Windows machine before I started using Obsidian. Once I installed Obsidian I set added Obsidian-git to automate the pulling and the pushing. While it does pull/push in use, everytime it does I get "You need to add your personal github access token in settings". The message is annoying more than anything because Obsidian-git is still working.

Any idea how I can get rid of that message?

**Comment by Vinzent03** [comment]
Are you on the latest version? Are you sure it's coming from the Obsidian Git plugin, because I can nowhere find that text in my code. Please share a screenshot of the console. ( Ctrl + Shift + i)

**Comment by mrrcollins** [comment]
Well, now it's not doing it. I'm closing this and blaming myself for not taking a screen shot in the first place. It must have been something weird on my end.
