### ISSUE TITLE
Question: Is it one vault to one remote repo? 

### ISSUE THREAD

**Issue by CoffeeCodeRpt** [denolehov/obsidian-git#65]
Am I limited to setting up a repo for every vault or can I wrap multiple vaults to a single git repo?

**Comment by denolehov** [comment]
Hey @CoffeeCodeRpt, at the moment, you're limited to one vault per repo.

**Comment by CoffeeCodeRpt** [comment]
Thanks @denolehov I appreciate the quick response:)

**Comment by Vinzent03** [comment]
Well you could create a branch for each vault.
