### ISSUE TITLE
[Feature request]: Use submodule to implement shared knowledge base

### ISSUE THREAD

**Issue by yxs-for** [denolehov/obsidian-git#661]
I hope to create a knowledge base shared by the team through steps similar to the following
1. Create a git repository as obsidian's vault
2. Add other people's git repositories as submodules to view their shared documents
3. Add your own public git repository as a submodule and as a shared notebook
4. Add your own private git repository as a submodule and as a private notebook
5. Configure other people's submodules to be forced to pull . Configure your own submodules to require push

The above steps may not actually be implemented, but I hope you can consider implementing this function. 
Thank you very much.

**Comment by Vinzent03** [comment]
Submodules are already supported on desktop, just enable the option in the settings and refer to the [documentation](https://publish.obsidian.md/git-doc/Features#Submodules+Support)
