### ISSUE TITLE
[Bug]: Obsidian Git commands don't work on iphone due to author information error

### ISSUE THREAD

**Issue by arcticmartian** [denolehov/obsidian-git#663]
**Describe the bug**

Git commands (_Obsidian Git: Pull_, _Obsidian Git: Create back up_) don't work on iphone, and shows the following error message: "**Git author information is not set. Please set it in the settings**". Prior to the error, I synchronized Obsidian with github without any problem (thanks to the command _Obsidian Git: Clone an existing remote repository_), and I wrote in the authentication boxes (username on GitHub and Personal access token) in the plugin settings. 

### Relevant errors (if available) from notifications or console (`CTRL+SHIFT+I`)

```shell
Git author information is not set. Please set it in the settings
```

### Steps to reproduce

1. Create a new vault in Obsidian (without selecting store in iCloud).
2. In Obsidian settings, enable community plugins, instal and enable Obsidian Git.
3. Fill in the username and personal token into the "Authentication/Commit Author" section of the Option for the Obsidian plugin.
4. Create a Token in GitHub.
5. Clone a repo using the command _Obsidian Git: Clone existing remote repo_  (https:// + Token+ the following https path from the repo in GitHub).

The error appears when: 
6. Try to _Obsidian Git: Pull_ or _Obsidian Git: Create back up_

### Expected Behavior

should sync changes after cloning repository successfully

### Operating system

iOS

### Installation Method

None

### Plugin version

Newest

**Comment by JulianGR** [comment]
Same here

**Comment by arcticmartian** [comment]
It works! thanks!!

It was fixed by filling the "Commit author" information (Author name for commit and Author email for commit) :)
