### ISSUE TITLE
[Bug]: Getting file history not working with a custom git name

### ISSUE THREAD

**Issue by riabiy** [denolehov/obsidian-git#664]
### Describe the bug

plugin:obsidian-git:34226 Uncaught (in promise) TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))
    at getData (plugin:obsidian-git:34226:62)
    at async openLineInGitHub (plugin:obsidian-git:34167:16)
    
    
if you have anything but `git@github.com:` it won't work. 

Example

personal-git@github.com:...
git@github.com-personal:...

and so on. 

Error occurs here

https://github.com/denolehov/obsidian-git/blob/1d81577877ccb548b06fb91036a246aa442a41ae/src/openInGitHub.ts#L84

### Steps to reproduce

Have have anything but `git@github.com:` in remote 

### Operating system

macOS

### Installation Method

None

### Plugin version

2.22

**Comment by Vinzent03** [comment]
Why would you use `personal-git@github.com` or anything different from `git@github.com` This shouldn't be about your local configuration, but about what user is used for the ssh connection to github.
