### ISSUE TITLE
[feature] add optional openai  based commit message summarization.

### ISSUE THREAD

**Issue by iamashwin99** [denolehov/obsidian-git#665]
The automatic commit messages are currently quite cryptic as they only offer hostname and date-related information.
It would be a nice introduction to have a {{ai_summary}} as an optional field which then uses, openai or other services to summarise the commit contents.

**Comment by Vinzent03** [comment]
Interesting idea, but I really don't plan to add that anytime soon.

**Comment by Paillat-dev** [comment]
*Maybe* it is possible using [opencommit](https://github.com/di-sukharev/opencommit) and custom git executable path in the obsidian-git settings. But it's  hack solution.

**Comment by GollyTicker** [comment]
An AI summary is not a core feature of a git-backup plugin. Ideally, this should be a secondary plugin based ontop of this one - or where a different obsidian plugin (which implements the AI summary) can be invoked from the obsidian-git plugin to generate the summary. This also makes it possible for the user to decide which AI to use - as not everybody is willing to send their vault files over the internet to Microsoft for summarization :sweat_smile:

**Comment by Vinzent03** [comment]
Yeah I don't plan it for this plugin, so I'm going to close this for now. I'm maybe open to offer an api for extra plugins.
