### ISSUE TITLE
[错误]：我在iOS上使用Working Copy同步iOS和Mac版的黑曜石，但发现黑曜石Git插件无法识别我的Git存储库

### ISSUE THREAD

**Issue by Anber55** [denolehov/obsidian-git#666]
### Describe the bug

I first cloned Working Copy locally, and then linked the repository to Obsidian's local repository. However, the Obsidian Git plug-in showed that it could not recognize Git. I came here to ask for help. I hope you can tell me how to operate Working Copy so that it can be used normally in Obsidian. Git plugin, thanks

### Steps to reproduce

no

### Operating system

macOS

### Installation Method

None

### Plugin version

2.22.0

**Comment by Vinzent03** [comment]
I'm a bit confused. Working Copy is a git client for iPhone and iPad, but not for macos. You need to install [git](https://git-scm.com/download/mac) on macos.
