### ISSUE TITLE
Maybe need a better way detect git

### ISSUE THREAD

**Issue by subframe7536** [denolehov/obsidian-git#668]
see https://github.com/steveukx/git-js/blob/main/examples/git-version.md#check-if-git-is-installed

or use https://github.com/npm/node-which and call

```ts
import which from 'which'

// ...
private isGitInstalled(): boolean {
  return !!which.sync('git')
}
```

context: I am using `git` with `Scoop` on Windows 11, and it fails to detect

**Comment by Vinzent03** [comment]
I don't think this would fix your issue. I guess the installation path of git from scoop is not in the path of Obsidian. Please try setting the git binary path directly in the settings.

**Comment by subframe7536** [comment]
![recording](https://github.com/denolehov/obsidian-git/assets/78338239/1556d678-8d54-457f-8317-1a36b886309b)

**Comment by subframe7536** [comment]
Alright, this took me a lot of time, and I think I need to spend my time on more useful things, and everything just works right now. So I'm going to close this issue for now.
