### ISSUE TITLE
Missing xcrun

### ISSUE THREAD

**Issue by mikaeljagelid** [denolehov/obsidian-git#67]
All running fine för more than a month until three days ago, when I get 
`git failed on initialisation!` in the status line when starting Obsidian. I also get popup alert from Obsidian indicating that xcrun can't be found: 
```
Error: xcrun: error: invalid active developer path
(/Library/Developer/CommandLineTools),
missing xcrun at:
/Library/Developer/CommandLineTools/usr/b...
```
(the popup crops the line unfortunately)

**Comment by Vinzent03** [comment]
Can you try running `xcode-select --install`(https://github.com/denolehov/obsidian-git/issues/52#issuecomment-798322189) in your terminal?

**Comment by afenc** [comment]
I have the same error and running xcode-select --install
solved the issue.

**Comment by Vinzent03** [comment]
Closing because of no response.

**Comment by Alex-Nemet** [comment]
Installing Xcode solved the issue for me as well. Thanks
