### ISSUE TITLE
[Bug]: Not working with custom sign agent

### ISSUE THREAD

**Issue by Paillat-dev** [denolehov/obsidian-git#672]
### Describe the bug

When i have an external agent that handles my ssh commit signing keys, obsidian does not recognize its existence. In my case, git is setup to use `/opt/1Password/op-ssh-sign` to sign commits, witch works perfectly fine outide of obsidian, but when backing up in obsidian it throws `No such file or directory`

### Relevant errors (if available) from notifications or console (`CTRL+SHIFT+I`)

```
Uncaught (in promise) Error: fatal: cannot exec '/opt/1Password/op-ssh-sign': No such file or directory
```

### Steps to reproduce

Open obsidian on linux, use a custom ssh signing agent in your `.gitconfig` file, for example
```
[gpg "ssh"]
  program = "/opt/1Password/op-ssh-sign"
```

### Expected Behavior

Commit my changes.

### Addition context

N/A

### Operating system

Linux

### Installation Method

Flatpak

### Plugin version

2.22.0

**Comment by Paillat-dev** [comment]
Missclick sorry

**Comment by Vinzent03** [comment]
Please try installing Obsidian with different package installer than flatpak. I think it disallows the access to that file.

**Comment by Paillat-dev** [comment]
Thank you for pointing me to the correct direction. I was not familiar with the fact that flatpak had sandboxing. Unfortunately, there is no other install option available for fedora, wich I am running, but I managed to change the permissions thanks to [flatseal](https://www.makeuseof.com/manage-flatpak-permissions-with-flatseal-linux/).
