### ISSUE TITLE
[Feature Request]: Ask password for SSH key in Mac

### ISSUE THREAD

**Issue by puchy22** [denolehov/obsidian-git#678]
I've alredy configure my Arch system to ask for my SSH key with `ksshaskpass` like the docs says. But now there isn't a guide in the doc to do the same in my Mac. I would like to know if anyone has the same problem and find a solution.

**Comment by Ubadub** [comment]
Bump. Anyone know how to do this? The setup instructions for Mac are sparse to non-existtent.

**Comment by MorenoJoshua** [comment]
@puchy22 @Ubadub I just set it up, here's how: (I already had an ssh key configured correctly)

- initialized the repo with `git init`
- added remote (tried to clone, didn't work)
- `git config remote.origin.url` > https://github.com/MorenoJoshua/.obsidian (you need to change the protocol and path)
- `git config remote.origin.url "git@github.com:MorenoJoshua/.obsidian.git"
- it works now

So: swap everything before the first `/` with `git@github.com:` and append `.git`
My private repo is at MorenoJoshua/.obsidian, so replace that with your repo's path

**Comment by puchy22** [comment]
@MorenoJoshua Sorry but I don't understand how this steps can make Obsidian asks for my ssh key password. I have already the repository good configured. I can push my changes from terminal, but the problem is when Obsidian plugin want pull or push doesn't have a method to ask me my password for my ssh key to pull or push the changes.

**Comment by jo-pouradier** [comment]
Try to follow github tutorial, the main part is at the end for you when you need to register your passphrase to the apple-use-keychain: [github tuto](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent)

**Comment by puchy22** [comment]
Thank you, that works for me. I am very new to Mac and I didn't knew about ssh-agent, it is exactly what I was searching.
