### ISSUE TITLE
Feat: keep this plugin running even if obsidian (mac) has no open window

### ISSUE THREAD

**Issue by narutohahahaha** [denolehov/obsidian-git#679]
Hi there,

I notice that this plugin cannot sync notes if Obsidian is running in the background mode---Obsidian has 0 window opened---on mac. Is it possible to address this problem?

**Comment by Vinzent03** [comment]
Do you mean the window is minimized and still running, or is Obsidian not even running? If it's not even running, there's no way for the plugin to run, when Obsidian is just minimized, the plugin should still work.

**Comment by narutohahahaha** [comment]
In mac, the app can run in a sort of background mode with no open window, which is different than the minimized mode. In the minimized mode, the open window is just hidden.

**Comment by narutohahahaha** [comment]
> Do you mean the window is minimized and still running, or is Obsidian not even running? If it's not even running, there's no way for the plugin to run, when Obsidian is just minimized, the plugin should still work.

In mac, the app can run in a sort of background mode with no open window, which is different than the minimized mode. In the minimized mode, the open window is just hidden.

What I notice is that if we click the obsidian icon when it runs in the background mode, obsidian will have to initialize a new window. In the minimized mode, the window can be quickly restored upon the click.

**Comment by Vinzent03** [comment]
I don't own a mac and can't really test this, but I'm pretty sure there's nothing I can do.
