### ISSUE TITLE
Backup interval should outlive sessions

### ISSUE THREAD

**Issue by NomarCub** [denolehov/obsidian-git#68]
I want to make sure to save daily, or a couple of times a week, but I don't have Obsidian open for that long, so the automatic vault backup doesn't kick in in time. To consistently save across sessions, the plugin could save the last backup timestamp into a file, and then auto backup on startup, if the interval has passed, or set a timer until the next scheduled backup time.
This could also help with more consistent saving if saving on exit (https://github.com/denolehov/obsidian-git/issues/13) is not possible.

**Comment by Vinzent03** [comment]
Great idea! So you have set the time to something like 12 hours?

**Comment by NomarCub** [comment]
I've set it to 10000 minutes and for a while forgot that it even existed.
