### ISSUE TITLE
[Bug]: Can not handle files with > in the name

### ISSUE THREAD

**Issue by vhdirk** [denolehov/obsidian-git#682]
### Describe the bug

Files with > in the name are not present in android.
They are pushed to the repo on the desktop

### Steps to reproduce

- Create a file with a > in the name.
- Push changes to git
- Observe, on android, that it does not pull files with > in the name. They are present in the repo.
- Remove the > from filenames and push.
- Now obsidian android can pull/show the files

### Operating system

Android

### Installation Method

None

### Plugin version

2.22.2

**Comment by Vinzent03** [comment]
< or > is not allowed in the filename on android. You can see this when you try to create such note in obsidian.
