### ISSUE TITLE
[Bug]: Not syncing .obsidian directory

### ISSUE THREAD

**Issue by ericbiewener** [denolehov/obsidian-git#685]
### Describe the bug

I expected this to sync the `.obsidian` directory, but it doesn't appear to be doing so. Is this a bug or intended behavior? I don't see this mentioned in the README.md. 

### Relevant errors (if available) from notifications or console (`CTRL+SHIFT+I`)

```shell
None.
```

### Steps to reproduce

1. Install a new plugin. Note that this changes the contents of your `.obsidian` git directory.
2. Push up the changes via this plugin.
3. Look at your repo contents in the GH UI. The changes will not be reflected in the `.obsidian` directory.

### Expected Behavior

I expected this plugin to operate the same as using the command line to push up changes.

### Operating system

macOS

### Installation Method

None

### Plugin version

2.20.6

**Comment by Vinzent03** [comment]
Did you add and commit the changes? Or maybe the directory is ignored via .gignore?

**Comment by DanHugoDanHugo** [comment]
I believe I´m seeing something similar (I do signed commits by default).

My usual (immediately prior to this update) would be to stage change(s), add a conventional comment, commit via the gui (check), password dialog, commit success…

Except in this case, none of this takes place.

The Commit Check does nothing, and so no password to get the gpg key, and no commit.
The staged changes appear still staged in the gui.

Obsidian v1.5.3 , linux, git v2.43.0 , etc.

**Comment by DanHugoDanHugo** [comment]
Normal commit behavior appears to have returned with plugin v2.23.1

**Comment by ericbiewener** [comment]
Agreed, seems to be fixed.
