### ISSUE TITLE
obsidian-git 2.23.0 on Mac OS does not commit from "Open Source Control View"

### ISSUE THREAD

**Issue by gbonazzoli** [denolehov/obsidian-git#686]
obsidian-git 2.23.0 on Mac OS (both Intel and ARM Mx) does not commit from "Open Source Control View". It seems that the button is not associated with the "git commit" command.

obsidian-git 2.22.0 was fine.

The command "Git: Commit staged" on obsidian-git 2.23.0 works fine

**Comment by Vinzent03** [comment]
Thanks for the report, should be fixed now.

**Comment by gbonazzoli** [comment]
TOP !!!!

obsidian-git 2.23.1 fixed the problem !!!
