### ISSUE TITLE
[Bug]: files in gitignore not being ignored

### ISSUE THREAD

**Issue by back-lacking** [denolehov/obsidian-git#688]
### Describe the bug

The error is exactly what it says on the title. I listed one file in my gitignore (`.obsidian/workspace.json`) however that one particular file wont be ignored. that would cause pulls and pushes to fail due to that one file not being ignored and file conflicts. 
(this issue is also present on windows, same behavior)

### Relevant errors (if available) from notifications or console (`CTRL+SHIFT+I`)

```shell
git obsidian error: Pull failed (merge): error: Merging is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.

plugin:obsidian-git:44193 git obsidian message: Everything is up-to-date
plugin:obsidian-git:44203 git obsidian error: You have conflicts in 1 file
plugin:obsidian-git:44203 git obsidian error: Pull failed (merge): fatal: You have not concluded your merge (MERGE_HEAD exists).
Please, commit your changes before you merge.

plugin:obsidian-git:44193 git obsidian message: Everything is up-to-date
plugin:obsidian-git:43742 Pushing....
plugin:obsidian-git:44203 git obsidian error: To https://gitlab.com/back-lacking1/obsidian-notes.git
!	refs/heads/main:refs/heads/main	[rejected] (non-fast-forward)
Done
Pushing to https://gitlab.com/back-lacking1/obsidian-notes.git
error: failed to push some refs to 'https://gitlab.com/back-lacking1/obsidian-notes.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. If you want to integrate the remote changes,
hint: use 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details
```

### Steps to reproduce

setup remote git repo
add `.obsidian/workspace.json` to git ignore
make whatever notes you need/want
press the "backup" button
see git error due to file conflicts
(windows sees the same process)

### Expected Behavior

workspace.json gets ignored when pushing changes and pulling changes. 

### Operating system

Linux

### Installation Method

Flatpak

### Plugin version

2.22.0

**Comment by Vinzent03** [comment]
I assume you already committed the file before adding it to .gitignore. You need to run `git rm --cached <file>` to remove it from the repo.

**Comment by back-lacking** [comment]
> I assume you already committed the file before adding it to .gitignore. You need to run `git rm --cached <file>` to remove it from the repo.

so ive done that, tried it for a few days, made a few changes, and i still see the file being modified. im looking at the commits on gitlab (obsidian notes stored on there), i would see the workspace.json file as a file that is modified. ive tried to remove workspace.json from the gitlab repo, but that didnt succeed.

**Comment by back-lacking** [comment]
Im not sure if i pushed the change. I will look at the commit log on gitlab. I will do it again in a couple minutes in order to confirm. I commited and pushed the gitignore seperately. Ran the git rm command, not sure if i pushed the change. 
The git ignore is just one line, `.obsidian/workspace.json`

**Comment by back-lacking** [comment]
![image](https://github.com/denolehov/obsidian-git/assets/86173810/0e618974-8ac0-468b-8026-0fc96e0c35cd)
here is the commits related to changing the gitignore and removing workspace.json. 
![image](https://github.com/denolehov/obsidian-git/assets/86173810/3e7beca9-e5d4-453a-bb4d-1319c9ff3460)
here is the commit related to the gitignore.

**Comment by Vinzent03** [comment]
But is the file now deleted in the repo on gitlab? You deleted the workspace file before fixing your `.gitignore`. If not try again to delete the workspace file via my provided rm --cached command.

**Comment by back-lacking** [comment]
i may be very dumb
just checked the gitlab repo, and workspace.json isnt there

**Comment by back-lacking** [comment]
as for how i deleted the workspace.json file, i deleted it from the gitlab repo using gitlabs "delete file" option

**Comment by Vinzent03** [comment]
I'm really confused by your new edits. I see you are not familiar with git and this is not a support forum for git. So I will try it last time. Go into terminal and delete the workspace.json file like I told you. The file should be marked as deleted now in git status. Now commit and push the changes. The file should now also be gone from the gitlab repo.

**Comment by back-lacking** [comment]
![image](https://github.com/denolehov/obsidian-git/assets/86173810/2cf61561-4abf-44a8-8afb-1b72a893a683)
shit

**Comment by Vinzent03** [comment]
As this is not an issue with the plugin, please try to find other sources on the internet to fix your issue. Like this one: https://www.atlassian.com/git/tutorials/saving-changes/gitignore I can't explain you every step on how to use git, now that you are even talking about multiple machines.

**Comment by back-lacking** [comment]
fair enough, i will take a look at that article when i can.
