### ISSUE TITLE
Enhancement request: PGP Encrypt files before commit

### ISSUE THREAD

**Issue by cooparo** [denolehov/obsidian-git#690]
Would be cool, if we can **PGP encrypt** (like the obsidian plugins [gpgCrypt](https://github.com/tejado/obsidian-gpgCrypt) does) before committing. We could use Github (or Gitlab, etc.) to store our files with **total privacy**.
How should works imo:
All the **files that are locally stored should be not encrypted,** so everything works as usual, like links, preview, etc. (you can try installing gpgCrypt, encrypting some files and you get broken links to headers and broken file's preview, etc.).
When you want to commit your work, it encrypts every files and eventually you push everything encrypted to Github, totally safe.

Some **cons**: you should still able to checkout to previous version of your notes but would be harder to get the difference between files, since they're encrypted.

**Comment by EricBrunMawuli** [comment]
I was gonna ask for the same feature, it would be great if it was implemented.

**Comment by cooparo** [comment]
I have zero knowledge of typescript but I have some freetime

**Comment by Vinzent03** [comment]
I think what you are searching for is [git-crypt](https://github.com/AGWA/git-crypt). I haven't used it, but according to [this issue](https://github.com/denolehov/obsidian-git/issues/434) it seems to work.

**Comment by cooparo** [comment]
Yep, it's what I was searching about. Tnx u
