### ISSUE TITLE
[Feature]: Add {{author}} to the commit template 

### ISSUE THREAD

**Issue by dhmmasson** [denolehov/obsidian-git#691]
### Description
Obsidian-git facilitates collaboration on a single Obsidian vault by allowing users to synchronize their vault to a remote Git repository. However, in the current implementation, one cannot specify the author in the automatic backup/commit messages. This feature becomes crucial in collaborative environments where multiple users contribute to the same Obsidian vault.

### Proposed Enhancement
Introduce a new variable, {{author}}, to Obsidian-git commit messages template.

### Use Case
In scenarios where multiple users are collaborating on a shared Obsidian vault, the ability to attribute changes to specific authors enhances transparency and accountability.
###  Additional Context
Obsidian-git already supports the use of {{hostname}} in commit messages for situations where a single user manages notes across different devices. Extending this support to include {{author}} would provide a comprehensive solution for both single-user and collaborative environments.
### Example

| Commit message on auto backup/commit |
|-|
| vault backup: {{date}} - {{author}|

```
vault backup: 2024-02-16 - dhmmasson
```

**Comment by Vinzent03** [comment]
What's the benefit of showing the author name in the commit message if the commit already contains the author, which is shown in git log or GitHub commit history as well?

**Comment by dhmmasson** [comment]
The benefits is to see it in the history view in obsidian : 
<img width="354" alt="Screen Shot 2024-02-25 at 17 55 03" src="https://github.com/denolehov/obsidian-git/assets/5263585/846250fd-d68c-40dd-a0eb-e757386c0aa9">
But you are right that it could be directly displayed in the history view from the commit info instead of embed in the message.

**Comment by dhmmasson** [comment]
Thank you for adding that feature!
It would have been a pleasure to contribute directly as I really appreciate your plugin. 
I'll gladly contribute to other issues if you are interested. 

Best,
