### ISSUE TITLE
Mobile. "Type your message and select optional the ve..." popup

### ISSUE THREAD

**Issue by xxxAleksandrxxx** [denolehov/obsidian-git#697]
On iPhone from time to time window with "Type your message and select optional the ve..." popups on the screen.
I believe it's connected to autobeckup somehow. What is that and how to get rid of this popup message?

 ![IMG_6497](https://github.com/denolehov/obsidian-git/assets/103126986/309f053d-ee44-4219-bb4b-7099623575ec)

**Settings:**
Split automatic commit and push: off
Vault backup interval: 5
Auto Backup after stopping file edits: on
Auto pull interval: 30
Specify custom commit message on auto backup: on
Commit message on auto backup/commit: auto backup {{hostname}}: {{date}}

Commit message on manual backup/commit: backup {{hostname}}: {{date}}
{{date}} placeholder format: YYYY-MM-DD
{{hostname}} placeholder replacement: phone
List filenames affected by commit on the commit body: off

Pull updates on startup: on
Push on backup: on
Pull changes before push: on

Automatically refreshed Source Control View on file changes: off
Source Control View refresh interval: 7000
Disable notifications: on
Show status bar: on
Show stage/unstage button in file menu: on
Show branch status bar: off
Show the count of modified files in the status bar: off

**Comment by Vinzent03** [comment]
It asks you for a custom commit message on automatic backup. So the setting `Specify custom commit message on auto backup: on` is the reason. If you don't want that, turn the setting off. Now the commit message for auto backup is used.

**Comment by xxxAleksandrxxx** [comment]
Thank you!
