### ISSUE TITLE
[Bug]: Git pull for Git submodules fail when no upstream remote repo defined

### ISSUE THREAD

**Issue by zombiemaker** [denolehov/obsidian-git#701]
### Describe the bug

For a given Obsidian Vault / Git repository (i.e. main Git repository) where:

- there is no upstream Git remote defined (i.e. the main repository is only a local repository)
- there are one or more Git submodule repositories defined (i.e. the main repository receives updates from other Git repositories as Git submodule repositories)

When using Git pull command:

- the app requests the user to select or create a new remote
- aborts the operation
- does not pull changes from Git submodule repositories

### Steps to reproduce

1. Create an Obsidian Vault as a Git repository (main Git repo)
2. Do not define any Git remote repository
3. Add Git submodule repository (submodule Git repo)
4. Perform, commit, and push changes in the Git repository located at the URL for the submodule Git repo
5. In Obsidian, execute the Git pull command as described above
6. Changes in the submodule Git repo are not fetched into the main Git repo
7. The contents in the Git submodule directory within the main Git repo directory does not change
8. Outside of Obsidian using Git command line program while inside the main Git repo directory, execute the "git submodule update --remote"
9. Updates to the Git submodule directory should be updated 

### Expected Behavior

- Obsidian Git should pull changes from the submodule Git repository even though a Git remote is not defined in the main Git repo

### Operating system

Windows

### Installation Method

None

### Plugin version

2.32.2

**Comment by Vinzent03** [comment]
Should be fixed now :tada:

**Comment by zombiemaker** [comment]
Awesome.   Thanks!
