### ISSUE TITLE
[Bug]: Android: "%%%%%" on left of each line in source mode

### ISSUE THREAD

**Issue by baskgithub** [denolehov/obsidian-git#705]
### Describe the bug

Android 14, obsidian 1.4.16
when switch to Source Mode, there are %%%%% on the left side of each line, which looks like line numbers.

It's normal in reading mode.

I have disabled all other plugins. 
the "%%%%%" appear once Git is enabled.
![Screenshot_2024-03-07-15-26-13-407_md obsidian-edit](https://github.com/denolehov/obsidian-git/assets/24505459/e56fe47f-43c9-43ff-9eef-28413a201216)

I don't kown what is wrong...
please help, thanks.

### Steps to reproduce

once git plugin is enabled

### Operating system

Android

### Installation Method

None

### Plugin version

2.24.0

**Comment by Vinzent03** [comment]
You enabled the line authoring feature on a desktop device and synced the setting to your mobile device. With ac2865676135a22a81f8d1a440825e7583aa73ec this is now fixed.

**Comment by baskgithub** [comment]
> You enabled the line authoring feature on a desktop device and synced the setting to your mobile device. With [ac28656](https://github.com/denolehov/obsidian-git/commit/ac2865676135a22a81f8d1a440825e7583aa73ec) this is now fixed.

Thank you very much! It's resolved in the latest update!
