### ISSUE TITLE
using another git lib on android

### ISSUE THREAD

**Issue by 3DRaven** [denolehov/obsidian-git#706]
Hi! In description of this plugin I read that base git lib is not stable. I think you can use eclipse jgit. It is very tested and stable library. FYI

**Comment by baskgithub** [comment]
by the way, do you have the same issue in the previous one?
%%%%% in source mode.

**Comment by Vinzent03** [comment]
jgit is based on java and I cant use a java library in a javascript plugin ecosystem. For now there are no alternatives.

**Comment by 3DRaven** [comment]
I'm not sure, but it seems to be solvable.

https://stackoverflow.com/questions/440302/how-to-cross-compile-java-source-code-to-javascript

Just for research and information :)
