### ISSUE TITLE
[Feature]: Make Auto Backup commits amendable

### ISSUE THREAD

**Issue by MikeKholomeev** [denolehov/obsidian-git#713]
Hi,

it would be good to have Auto Backup commits Amendable 
and
split AutoCommit and AutoPush.

So I can set Auto Commit interval to 0.1 so it would Amend new changes into the previous commit.

Thanks

**Comment by Vinzent03** [comment]
I don't want the auto backup to be even more complicated and I don't see the great value of always amending. So I don't plan to implement that feature.
