### ISSUE TITLE
[Proposal]: Rename the plugin to "Git Backup"

### ISSUE THREAD

**Issue by tamiroh** [denolehov/obsidian-git#716]
The name of this plugin appears to have changed from Obsidian Git to Git. Certainly I also thought the plugin name would be better without the word "Obsidian", but I think the current name is a bit too ambiguous, though.

So how about "Git Backup" instead?

In my opinion, this name represents the role of the plugin without over- or under-describing it.

**Comment by tamiroh** [comment]
I was thinking of the following others, 

- Backup with Git
- Git Auto Backup
- Auto Backup with Git
- Vault Backup with Git
- Git Vault Backup
- Git Suite

but decided that "Git" should be at the beginning of the name to emphasise that it is a plugin for Git, and that the name does not need to include anything more than doing Backup.

So I think "Git Backup" is the best for now. 👀

**Comment by Riezebos** [comment]
Why do you think Git is too ambiguous? Are plugins like "Pandoc", "Kanban", "Calendar", "Tasks", "Leaflet" also too ambiguous in your opinion?

It's a plugin for Git with lots of functionality, not just Backup. In my opinion, the name Git is quite clear.

**Comment by tamiroh** [comment]
Hmmm, it also seems certain. This plugin may be initially focused on backup feature, but now it has a whole range of Git-related features. So perhaps changing the description in the README would be better.

**Comment by tamiroh** [comment]
README has been updated and I am closing this Issue for now :-)
