### ISSUE TITLE
Wait until `onLayoutReady` before running commands

### ISSUE THREAD

**Issue by liamcain** [denolehov/obsidian-git#72]
https://github.com/denolehov/obsidian-git/blob/5a654bde4e5c0374627250f64ef8f1ccb5c466eb/main.ts#L101

Currently `init` is being called from within onload which slows Obsidian's startup time. Instead you should wrap this in [`onLayoutReady`](https://github.com/obsidianmd/obsidian-api/blob/48bd2b91f66aa7d3768629be48c52e5351ec6696/obsidian.d.ts#L3200) so that it's non-blocking.

**Comment by Vinzent03** [comment]
Oh I though this wouldn't make a difference, because I am not awaiting it.
