### ISSUE TITLE
[Bug]: Freshly installed plugin renders Obsidian unusable!

### ISSUE THREAD

**Issue by danielrosehill** [denolehov/obsidian-git#720]
### Describe the bug

Installed the plugin on Obsidian running on Ubuntu.

Get this on boot now and there's no way to exit out of it, thus making the entire program unusable.

Where does this install to on Ubuntu for manual deletion?

![bug2](https://github.com/denolehov/obsidian-git/assets/40233203/1671c91d-c9f6-4a97-a4df-ef016f46d372)

### Steps to reproduce

-> Obsidian on Ubuntu
-> Install

### Operating system

Linux

### Installation Method

Other

### Plugin version

cant access info

**Comment by Vinzent03** [comment]
What do you mean with unusable? You can delete it by deleting the <vault-root>/.obsidian/plugins/obsidian-git directory.

**Comment by FerallOut** [comment]
When I manually download the "obsidian-git-2.24.1.zip" folder, and extract the files, I found only the "main.js" and "manifest.json" files. After I separately download the "styles.css", it works for me.

**Comment by danielrosehill** [comment]
> What do you mean with unusable? You can delete it by deleting the /.obsidian/plugins/obsidian-git directory.

Hey. Sorry that a poor choice of wording. I figured out where the plugin directory was and got back to where I was by nuking it. 

Maybe there's something that needs to be resolved in the config or something.

**Comment by Vinzent03** [comment]
I've fixed the release script to include the styles.css in the release zip.
Seems like the original issue is fixed.
