### ISSUE TITLE
[Enhancement Suggestion]: Make .git folder outside of value folder by default

### ISSUE THREAD

**Issue by DDDOH** [denolehov/obsidian-git#723]
### Describe the bug

Actually this is not a bug. I found the obsidian starting time on my iPhone is incredibly slow, always stuck at "waiting for iCloud to sync config files", or "loading workspace". I tried to move the .git folder to somewhere else outside of the obsidian value folder. After that obsidian starts really fast on my iPhone. (I am using iCloud to sync obsidian vault folder).

If this is common for other users, I suggest add some description in the README file.

### Steps to reproduce

see the description

### Operating system

macOS

### Installation Method

None

### Plugin version

2.24.1

**Comment by DDDOH** [comment]
@inobrevi That's good for android. But for iCloud I think there is no way to stop syncing .git folder (without change the name of this folder)

**Comment by Vinzent03** [comment]
But did the plugin still work with the .git folder outside the vault? I don't think so, because the plugin shouldn't have file access to files outside the vault.

**Comment by DDDOH** [comment]
it still works. The plugin do not need access to .git folder directly. It only calls git cli command.

**Comment by Vinzent03** [comment]
I thought you were talking about mobile, because you mentioned iPhone in your description. There is no git cli on mobile. On macOS exists no such restriction. So about what device are you talking now?

**Comment by DDDOH** [comment]
I don't need git for my iPhone, i need it only on my mac.

**Comment by Vinzent03** [comment]
Ah now I understand your situation. You are only using git on your Mac, but because iCloud syncs all files, the .git directory is now on your iPhone as well, which slows down Obsidian startup.
I will definitely not change the default location to outside the vault, but I can add a note to the documentation.

**Comment by DDDOH** [comment]
yeah sure. that would be helpful for users like me.

2024年6月23日 下午5:52，Vinzent ***@***.***> 写道：



Ah now I understand your situation. You are only using git on your Mac, but because iCloud syncs all files, the .git directory is now on your iPhone as well, which slows down Obsidian startup.
I will definitely not change the default location to outside the vault, but I can add a note to the documentation.
