### ISSUE TITLE
Merge Conflicts since #68 was fixed.

### ISSUE THREAD

**Issue by despairblue** [denolehov/obsidian-git#74]
Hey, first of, thanks for creating this extension. I don't use a lot of community plugins, but this one turned out to be indispensable. Great work 👏🏾 

Adding the timestamp in the data.json file leads to merge conflicts if obsidian is used on multiple machines and obsidian-git is used to synchronize the vault:

![image](https://user-images.githubusercontent.com/927609/117941084-09c6cb00-b30a-11eb-8eee-addcba39753d.png)

Every obsidian instance will updated the timestamp before pulling and thus create a conflict in that file. It's not that this sometimes happens, it happen consistently every time.

I wonder if 
* that timestamp could be in a different file that could be added to .gitignore or 
* if the timestamp could turned off or
* if the timestamp could only be updated right after a pull

I think all of those would fix this. What do you thing would be the best option?

**Comment by RichSteele** [comment]
I can confirm I've been seeing this behavior as well. Thank you for finding the probable cause of an issue I haven't had a chance to track down yet.

**Comment by Vinzent03** [comment]
I totally see your point. Will decide me for a solution today and patch a fix.

**Comment by Vinzent03** [comment]
Should be fixed now. Let me know if you have further problems.
Fixed another bug too. 😅

**Comment by despairblue** [comment]
Is there a way to try this directly from git as the fix is not released yet?

**Comment by Vinzent03** [comment]
Sorry I just totally forgot that. Will do it now!

**Comment by Vinzent03** [comment]
New [release](https://github.com/denolehov/obsidian-git/releases/tag/1.9.2) is out

**Comment by despairblue** [comment]
Thank you, this fixed it 👏🏾
