### ISSUE TITLE
[Bug]: Uppercase letters in branch names seem to break it

### ISSUE THREAD

**Issue by MicaelJarniac** [denolehov/obsidian-git#741]
### Describe the bug

Uppercase letters in branch names seem to break it

### Steps to reproduce

1. Create branch with uppercase letters
2. It breaks

### Operating system

Linux

### Installation Method

AppImage

### Plugin version

2.24.2

**Comment by Vinzent03** [comment]
Works fine for me. Please elaborate what exactly you are doing and what breaks. Maybe share screenshots and logs.

**Comment by MicaelJarniac** [comment]
I feel like it was easier to do this process with a branch with all lowercase chars, but I managed to make it work with uppercase chars too, so it might be just me doing things wrong. I think I'll close the issue then.

![image](https://github.com/denolehov/obsidian-git/assets/19514231/53c4d3ad-b853-4695-8e9a-d6e53487d98d)
![image](https://github.com/denolehov/obsidian-git/assets/19514231/c8ae1bed-f2e0-4fda-b556-6609926e85cd)
![image](https://github.com/denolehov/obsidian-git/assets/19514231/7fe3cefd-8f46-4452-8836-28c563746e79)
![image](https://github.com/denolehov/obsidian-git/assets/19514231/01781365-b29a-4444-b839-ee627ee6390c)
![image](https://github.com/denolehov/obsidian-git/assets/19514231/e2df9bfe-b2ee-42e2-838e-138fabe23a0c)
![image](https://github.com/denolehov/obsidian-git/assets/19514231/902b1d96-f5bb-4ee4-b467-5921846e4426)
![image](https://github.com/denolehov/obsidian-git/assets/19514231/7e0e7376-e7ac-4203-87dd-9f80639f5ab6)
![image](https://github.com/denolehov/obsidian-git/assets/19514231/ee541eb1-8768-46f7-b851-9c9120c51a6b)
![image](https://github.com/denolehov/obsidian-git/assets/19514231/2e80067a-df59-4dac-9dbf-3d0656390e9f)
![image](https://github.com/denolehov/obsidian-git/assets/19514231/a8fd6f87-1131-423b-b014-ed9d22f8972a)
![image](https://github.com/denolehov/obsidian-git/assets/19514231/d68b500c-c020-4d6f-b49a-21668a4759de)
![image](https://github.com/denolehov/obsidian-git/assets/19514231/43e10590-3294-4736-ba97-d1fa1e6a5162)
![image](https://github.com/denolehov/obsidian-git/assets/19514231/050e1246-16f6-4201-80a3-54047865bafe)
![image](https://github.com/denolehov/obsidian-git/assets/19514231/7d8973ca-2366-4e79-955c-d6d048ffee64)
![image](https://github.com/denolehov/obsidian-git/assets/19514231/feb0efd2-510c-4291-94b9-9456bdc29290)
![image](https://github.com/denolehov/obsidian-git/assets/19514231/68ab629a-9388-470e-a56b-c8c5870f1643)
![image](https://github.com/denolehov/obsidian-git/assets/19514231/1d32a6c1-8031-4858-9498-e04191a8bbfa)
![image](https://github.com/denolehov/obsidian-git/assets/19514231/8ab65625-a879-4e62-9c16-751a300c816b)
![image](https://github.com/denolehov/obsidian-git/assets/19514231/dbffc7ad-a483-4038-b24d-4abe45cdaacb)
