### ISSUE TITLE
[Bug]: Loop of asking to select the remote branch

### ISSUE THREAD

**Issue by DevSerendipity** [denolehov/obsidian-git#743]
### Describe the bug

Constantly asking me to set my remote branch
![image](https://github.com/denolehov/obsidian-git/assets/58050604/37953368-4fed-4afe-aeb6-029f9d6565f6)

### Relevant errors (if available) from notifications or console (`CTRL+SHIFT+I`)

```shell
Dataview: all 268 files have been indexed in 5.399s (0 cached, 0 skipped).
plugin:obsidian-git:45290 git obsidian error: Aborted. No upstream-branch is set!
plugin:obsidian-git:45294 obsidian-git: No changes to push
plugin:obsidian-git:45294 obsidian-git: Committed 5 files
plugin:obsidian-git:45294 obsidian-git: Fetching remote branches
plugin:obsidian-git:45290 git obsidian error: Aborted. No upstream-branch is set!
plugin:obsidian-git:45294 obsidian-git: No changes to push
plugin:obsidian-git:45294 obsidian-git: No changes to commit
plugin:obsidian-git:45294 obsidian-git: Fetching remote branches
plugin:obsidian-git:45290 git obsidian error: Aborted. No upstream-branch is set!
plugin:obsidian-git:45294 obsidian-git: No changes to push
plugin:obsidian-git:45294 obsidian-git: No changes to commit
plugin:obsidian-git:45294 obsidian-git: Fetching remote branches
plugin:obsidian-git:45290 git obsidian error: Aborted. No upstream-branch is set!
plugin:obsidian-git:45294 obsidian-git: No changes to push
plugin:obsidian-git:45294 obsidian-git: No changes to commit
plugin:obsidian-git:45290 git obsidian error: Aborted. No upstream-branch is set!
plugin:obsidian-git:45294 obsidian-git: No changes to push
plugin:obsidian-git:45294 obsidian-git: No changes to commit
plugin:obsidian-git:45290 git obsidian error: Aborted. No upstream-branch is set!
plugin:obsidian-git:45294 obsidian-git: No changes to push
plugin:obsidian-git:45294 obsidian-git: No changes to commit
plugin:obsidian-git:45290 git obsidian error: Aborted. No upstream-branch is set!
plugin:obsidian-git:45294 obsidian-git: No changes to push
```

### Steps to reproduce

I tried to setup this project many times with the UI of Obsidian Git but it keeps making me problems

- installed the plugin
- git init
- added the remote branch like https://github_pat_MYPAT>@github.com/DevSerendipity/MyVault.git (I did it this way because it didn't ask for my PAT so I inserted it straight away which passed)
- made the commits trough the terminal git add . git commit -m "initial commit", pushed it to main, only that way it started registering my changes I was making in my root vault (it initially cloned it inside my vault, but I moved the .git to root after)
- after i did that than i removed the origin and set it up with git remote add origin https://github.com/DevSerendipity/NameOfMyVault.git 
- than I started being bombarded with lots of set origin messages

### Expected Behavior

No loop 

### Operating system

Windows

### Installation Method

Other

### Plugin version

latest

**Comment by DevSerendipity** [comment]
seems like there was some issue with github and it just didn't commit my changes to the upstream, so there wasn't a remote origin branch. That's why it got that error i assume

**Comment by davpaez** [comment]
Hi @DevSerendipity 

I am getting the same (or very similar) error, along with a UI prompt appearing several times, asking me to set up a git remote branch.

The thing is I don't want to have a remote branch. What the prompt appears, I just close it. However, the plugin keeps asking and showing that prompt.

Do you know how I can disable that persistent request to set up a remote branch?

**Comment by Vinzent03** [comment]
@davpaez Why wouldn't you want a remote branch. Does this mean you don't want to push at all? Then you probably need to toggle this off in the settings for the "Commit-and-sync" action.
