### ISSUE TITLE
[Bug]: added jpg files are not displayed in source control

### ISSUE THREAD

**Issue by blumenschwein** [denolehov/obsidian-git#747]
### Describe the bug

In source control, the file names of newly added jpg files are not displayed, although the number of new files are shown (red box in the following screenshot).
![image](https://github.com/denolehov/obsidian-git/assets/39619298/bca9db1b-3cce-42de-831a-dca93f0791d4)

File names of modified md files are displayed correctly.

### Steps to reproduce

1. Add a jpg file to obsidian
2. Refresh source control -> file names are shown for modified md files, but not for jpg files

### Expected Behavior

File names of all modified files are displayed. This was the case in earlier versions of Obsidian-Git.

### Operating system

Linux

### Installation Method

AppImage

### Plugin version

2.24.3

**Comment by Vinzent03** [comment]
Works fine for me. Are you sure they are not ignored from your `.gitignore`? Please share that file.

**Comment by blumenschwein** [comment]
My .gitignore contains only two lines as below:

```bash
> cat .gitignore 
**/.obsidian
**/_debug*
```
Furthermore, the jpg files are **not** ignored by git. They are added to git correctly. The only issue is that their file names are not displayed in source control, and only the number of files is shown.

I also tried it on Windows, and encountered the same issue.

**Comment by Vinzent03** [comment]
Okay, thanks. Are there any errors in the console (`CTRL+SHIFT+I`)? And may you try the default Obsidian theme? As it seems you are using some different theme, changing the icons.

**Comment by blumenschwein** [comment]
Thanks. With your hint, I found the reason. I use custom snippet to hide the `resources` folder like this:

```css
div[data-path^='resources']{
  display: none;
}
```

When I remove this snippet, the names of the jpg files, which are stored in the `resources` folder, appear again.

However, with previous versions of Obsidian and Obsidian-Git, I also used this snippet to hide the `resources` folder, but there the file names in the `resources` folder are all displayed. It seems now that files which are in hidden folders are not displayed anymore, although they are correctly counted (like the "5" in the screenshot above) and added to git.

**Comment by Vinzent03** [comment]
I don't think I've changed something in this regard in the last weeks. You must have been on some much older version. The best way is to make your snippet more specific, by only applying this for the `file-explorer`. There is nothing I can do from my side.

**Comment by blumenschwein** [comment]
Thanks for the suggestion. I found a solution: change the snippet to

```css
.nav-folder-title[data-path^='resources']{
  display: none;
}
```

**Comment by Vinzent03** [comment]
This will only work partially. The plugin provides the option to display your files in a folder view, which will use that css class as well. Which will miss files in that directory again. As long as you don't use that view, this should be fine.
