### ISSUE TITLE
"Cannot run git command" error message on startup.

### ISSUE THREAD

**Issue by Alekssavin** [denolehov/obsidian-git#75]
I have just installed the plugin.
I have successfully authenticated into my GitHub via https.
I have successfully made the first commit on the master branch and pushed it into Github upstream.
When I open Obsidian I get the message "Cannot run git command" on the top right corner.
Please help.

**Comment by Vinzent03** [comment]
On which OS are you? Did you install git on your device? If you are on Windows did you follow this [instruction](https://github.com/denolehov/obsidian-git#windows-installation)?

**Comment by Alekssavin** [comment]
Sorry for providing you all insufficient data.
I use OpenSuse Leap 15.2
Of course I have git installed. I was able to push my vault on github.

**Comment by Vinzent03** [comment]
How did you install Git? Have you read the [Linux instructions](https://github.com/denolehov/obsidian-git#linux-installation)? Snap version does not work, because of sandbox.

**Comment by Alekssavin** [comment]
Now I see there is a problem with snap. I have snap version installed. So there is no hope, I suppose? Should I switch to flatpak instead?

**Comment by Vinzent03** [comment]
Yeah either Flatpak or AppImage ([instructions for AppImage](https://forum.obsidian.md/t/meta-post-linux-tips-tricks-solutions-to-common-problems/6291/3))

**Comment by Alekssavin** [comment]
Too bad. Thank you for your time anyway.
