### ISSUE TITLE
Says no upstream branch is set, but I think there is

### ISSUE THREAD

**Issue by mrdanimal** [denolehov/obsidian-git#76]
I have a repo set up and `git push` works from the command line, but when the plugin tries to push, it throws an error, "Did not push. No upstream branch is set!" In the plugin settings, "master" is set as the current branch, which is correct. Is there anything else need to set up? I've read the README and think I covered everything. Thanks!

**Comment by Vinzent03** [comment]
Are you really only running `git push` or rather `git push origin master`? Do you mind sharing your `config` file in `.git`?

**Comment by mrdanimal** [comment]
Yep, I'm only running `git push`. Here's my `config`:
```
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
	precomposeunicode = true
[remote "origin"]
	url = git@github.com:<redacted>.git
	fetch = +refs/heads/*:refs/remotes/origin/*
```

My global config has `push.default=current`. Would that affect anything?

**Comment by prakar** [comment]
I have the same error, but I am using "git push origin master". 

My git config is:


[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
	precomposeunicode = true
	longpaths = true
[gui]
	wmstate = normal
	geometry = 1353x451+5+28 365 203
[remote "origin"]
	url = https://github.com/xxxxxxxxxxxxxx.git
	fetch = +refs/heads/*:refs/remotes/origin/*

**Comment by Vinzent03** [comment]
@prakar Can you try running `git push`(without the `origin master` part)?

**Comment by prakar** [comment]
This is what i see

```
fatal: The current branch master has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin master
```

![Screen Shot 2021-07-23 at 5 38 17 PM](https://user-images.githubusercontent.com/811452/126779690-f1d289c0-491c-4b85-b942-d19807203259.png)

**Comment by Vinzent03** [comment]
That's exactly what I wanted. Run this and then commit and try again to push in Obsidian.

**Comment by prakar** [comment]
I ran ``` git push --set-upstream origin master``` and ```git commit```, and the commit errors have gone. 

BUT now my UI is freezing, i am unable to interact with Obsidian while the plugin is working. I have to disable it after waiting for the screen to refresh, then i am able to use the UI. 

So now, i have changed to Bug #69  (UI freezes, cannot interact with it)
