### ISSUE TITLE
".obsidian-git-data" causing conflict issue

### ISSUE THREAD

**Issue by linfz94** [denolehov/obsidian-git#78]
I don't why obsidian-git generate a file called ".obsidian-git-data" in the root directory recently, and It always cause conflict isscue, It is really annoying. Is there any way to solve this problem?
![图片](https://user-images.githubusercontent.com/53118840/119422206-1ea45500-bd33-11eb-80f3-b1ff32d81ced.png)

**Comment by Vinzent03** [comment]
It's there to save the date of the last auto backup/pull. It was there to fix merge conflicts. Please add it to the `.gitignore`

**Comment by ljantzen2** [comment]
I have the same issue, probably because I use git to sync between two computers using different locales: 

```
Wed May 26 2021 07:35:14 GMT+0200 (sentraleuropeisk sommertid)
Tue May 25 2021 10:46:15 GMT+0200 (Central European Summer Time)
=======
Tue May 25 2021 10:35:14 GMT+0200 (sentraleuropeisk sommertid)
>>>>>>> a1c958e2c319cd25a6574d21fba0eeb8809855f9
Mon May 24 2021 13:35:13 GMT+0200 (sentraleuropeisk sommertid)
=======
Mon May 24 2021 12:34:52 GMT+0200 (Central European Summer Time)
>>>>>>> e582808127705b79d69f2de8a1a538728d2231ad
~                                                            
```

**Comment by Vinzent03** [comment]
Please take a lookt at my previous comment.

**Comment by laughedelic** [comment]
Maybe it's better to persist this information in the git config? I think this would avoid some confusion and the need to add it to gitignore.
