### ISSUE TITLE
Feature request: trigger vault backup manually

### ISSUE THREAD

**Issue by SaysKez** [denolehov/obsidian-git#8]
First up, loving the plugin so far! Exactly what I needed for my workflow. 

Personally, I would to be able to manually trigger the vault backup within Obsidian. My vault is hooked up to my website so rather than constantly backing up (and triggering new builds each time) every x minutes, it would be nice to be able to write a post and then push the changes within Obsidian when I am ready to publish.

You could do this from the terminal/git client but for me that circumnavigates the biggest convenience of this plugin which is managing everything within Obsidian.

**Comment by vkrol** [comment]
Hello.

It's availiable in Command palette (Ctrl + P):
![image](https://user-images.githubusercontent.com/153412/98267740-c5debc00-1f9c-11eb-856e-3a902414c809.png)

**Comment by SaysKez** [comment]
Silly me, did not catch that all. That's brilliant, thanks!
