### ISSUE TITLE
2FA authentication

### ISSUE THREAD

**Issue by danraymond** [denolehov/obsidian-git#80]
Github requires me to use 2 factor Authentication. Can this be added to the plugin?

**Comment by Vinzent03** [comment]
I don't really know how git handles 2FA. What happens if you try to push/pull via git in the terminal?

**Comment by danraymond** [comment]
Github is moving to require 2FA for all transactions soon. In the console
it asks you to enter the data from your authenticator app (e.g. the Google
app) you then enter that into the console.

So you enter: username then password when asked  and then the 2FA code when
asked.

Regards

**Comment by Vinzent03** [comment]
Are you using personal access tokens as stated in the [docs](https://docs.github.com/en/github/authenticating-to-github/securing-your-account-with-two-factor-authentication-2fa/accessing-github-using-two-factor-authentication)? I have 2FAenabled and have no problems with https authentication.

**Comment by Vinzent03** [comment]
Closing because of no response. Just comment if you have still problems, and I'm open to reopen the issue.
