### ISSUE TITLE
Add support for proxy

### ISSUE THREAD

**Issue by drodil** [denolehov/obsidian-git#83]
Pull and push do not work if you are behind proxy and use git over HTTPS. For some reason global git config does not affect here (simple-git?). It would be nice to allow set http proxy from the Settings of this add-on.

**Comment by drodil** [comment]
Sorry, it seems like I missed the global git config for the proxy. After setting it the obsidian-git started working. Not sure anymore if it's necessary to have the configuration in the Obsidian, maybe, maybe not.

**Comment by Vinzent03** [comment]
The most of configuring, especially such advanced things, have to be done by editing the config with any other text editor. Can I close this now?

**Comment by drodil** [comment]
Sure, let's close it!
