### ISSUE TITLE
Obsidian Gİt Plugin stopped working (files in one drive)

### ISSUE THREAD

**Issue by gandalf34** [denolehov/obsidian-git#84]
I am a newbie obsidianer. I setup the Obsidian Github plugin. I also setup the Git and Github desktop. My files are sitting in one drive. Everything was working fine. Suddenly it stopped. The plugin doesnt give any error. I can see the notifications like 3commits etc. But onedrive sync started to post a notification which states file FETCH Head file couldnt be merged and a new file was formed (see attached image). There’s a another file named FETCH Head with a longer file name.

How can I correct this? Any help much appreciated.
![2021-06-25](https://user-images.githubusercontent.com/86377241/123481178-09f5fe00-d60c-11eb-9c70-b310de8e439b.png)

**Comment by Vinzent03** [comment]
I wouldn't synchronize it with both services. I think the fetch file depends on the device and shouldn't be synced with another PC. That has nothing to do with the plugin. Maybe try to disable onedrive for that particular directory.

**Comment by phibr0** [comment]
The `.git/` Directory to be more specific. It is not visible by default in the Explorer.

**Comment by RichSteele** [comment]
You might want to consider moving your Obsidian folder outside OneDrive, as
the syncing can cause issues with some applications. I've found git
especially to not enjoy having its directory OneDriven.

If you want to keep your vault in your OneDrive folder, a couple of things
to try:

1. Right-click the Obsidian vault folder and select "Always keep on this
device" to prevent OneDrive from evicting Obsidian's files.
2. Use the git --separate-git-dir option to move the .git directory
someplace outside of OneDrive's reach

**Comment by gandalf34** [comment]
I moved the files from one drive to C: drive .
