### ISSUE TITLE
Plugin producing no error but not working

### ISSUE THREAD

**Issue by gandalf34** [denolehov/obsidian-git#85]
I am on windows . When I sync with Github desktop everything works fine and syncs. At the bottom of the screen it shows git:pulling changes. I uninstalled the plugin and reinstalled and played a
round with settings but to no avail.  The console doesn't show any error. I don't know where else  to look or change. I am not very tech savy. What information can I provide to start solving this? Thanks in advance for the help . 🙏  
![2021-06-26](https://user-images.githubusercontent.com/86377241/123525538-26606c00-d6da-11eb-85d0-19d58eb82763.png)

**Comment by gandalf34** [comment]
An update...I uninstalled and installed both Obsidian and the plugin. To no avail. The difference is it does commit now. But pull and push not working. The bottom panel lists pulling changes or pushing changes...But nothing is happening.

**Comment by HatshibaInu** [comment]
I can confirm that this issue has occurred for me too. 
![image](https://user-images.githubusercontent.com/63698999/124344764-b9882d00-dc17-11eb-8bbb-5ce6cca8a25b.png)

It will be stuck on "pulling files..." or "pushing files...". I used the Windows set up instructions exactly as they were.

**Comment by Vinzent03** [comment]
Sorry to hear of your problems. Does push /pull work from the command line via `git push`?

**Comment by HatshibaInu** [comment]
Push works via the github desktop app, not too familiar with the command
line on Windows

**Comment by HatshibaInu** [comment]
Thank you so much for asking btw

**Comment by gandalf34** [comment]
Yes pull and push work from the Github desktop app no problems.

**Comment by Vinzent03** [comment]
@gandalf34 Sorry, but that's not what I asked for. I meant using git via the command line, because that's more like the way the plugin works. 
@HatshibaInu You have to go into your vault directory, commit before via github desktop and run then `git push`.

**Comment by gandalf34** [comment]
Checking now... will let you know

**Comment by gandalf34** [comment]
I made a change on a journal locally and pushed via the cmd line. It
worked. Here's a screenshot.

Should I try a pull as well or is this enough for now?

**Comment by gandalf34** [comment]
Hi... İs there something that I can provide further with this ? Your
help and assistance is greatly appreciated. 🙏

**Comment by Vinzent03** [comment]
Hmm, sorry, but I don't know how I can help you/fix the problem. It's strange that there is no error in the console. You say it commits, so it finds the git executable... So the problem must be something with firewall?? or your connection to github. How did you authenticate using the cmd?

**Comment by gandalf34** [comment]
Yes. it worked. The Other when I was using the command line it asked me to
login to git. Although it had worked on the command line and didnt work on
obsidian I checked on git cmd if I was logged in and then I tried and boom
it worked.

I really dont know what happened and what solved it but I think its related
to being logged in somehow. Thanks for the time and effort. 🙏

**Comment by HatshibaInu** [comment]
Yep, pretty sure authentication was the trick. Thanks a ton for the help,
but you might wanna update the guide in future to include it.

**Comment by Vinzent03** [comment]
It's kinda mentioned already.
https://github.com/denolehov/obsidian-git#requirements
That's why I asked you to not use GitHub desktop. I expect a user using git for a note-taking app already has some experience with raw git in the terminal. I might have to change that mindset haha.

**Comment by gandalf34** [comment]
😊 haha ...well yes I had never used Git in my life not tech person at
all...I learned git (well just enough to get by) just for your plugin...
Thanks again for the plugin by the way...🙏
