### ISSUE TITLE
Cannot pull changes from remote repo

### ISSUE THREAD

**Issue by RoonilWazzlib** [denolehov/obsidian-git#86]
When I make changes to the remote repo these are not pulled into my local files. 

If I try to execute the `Commit *all* changes and push to remote repository` command it tells me there are no changes to commit or push and doesn't do anything. If I restart the app then it will execute `Pull updates on startup` correctly and changes are pulled in.

I have the `Pull changes before push` setting turned on, but it seems that only works when there are some changes to the local files to push in the first place. When the only changes are on the remote repo it just does nothing.

I'm running obsidian version 0.12.5 on Windows 10 version 20H2, with the remote repo stored in a private GitHub repo.

**Comment by Vinzent03** [comment]
There is another `pull changes` command to only pull changes. The other command does not pull changes, because it doesn't push changes when there are no changes. Please reopen if it still doesn't answer your question.

**Comment by RoonilWazzlib** [comment]
I guess I expected there to be a single option to "sync". Meaning if the remote repo is ahead then pull those changes in and if the local repo is ahead commit and push them. 

I don't really see the use case for splitting these into distinct commands.

I'm not sure how other people use it, but my ideal functionality would be a single hotkey which does everything. Pulls if needed, and commits/pushes if needed.

**Comment by Vinzent03** [comment]
It's still supposed to be a git client. That's why it sticks to the default git pull/push behavior.

**Comment by RoonilWazzlib** [comment]
That is very fair. Thank you for the clarification!
