### ISSUE TITLE
git pull on startup error, failing, hanging

### ISSUE THREAD

**Issue by prakar** [denolehov/obsidian-git#88]
- The error message on re-starting Obsidian after installing the plugin is "URL not set", but the plugin doesn't allow a place to set repository URL. 
- The assumption is that the plugin would use the existing github repository information from the vault directory. However, that does not happen for me.
- The message "git pull" in the status bar remains, and Obsidian is locked so I cannot use the UI to disable the plugin.
- I ended up deleting the plugin folder from .obsidian/plugins to regain control of Obsidian.

**Comment by Vinzent03** [comment]
Sorry, I don't know what's causing this error. Your Obsidian freezes, because of this error? Sounds a bit like #69 . Are there any other errors in the console? (`CTRL + SHIFT + I`) Hopefully with a bit more text than just "URL not set".

**Comment by prakar** [comment]
![Screen Shot 2021-07-23 at 11 24 17 AM](https://user-images.githubusercontent.com/811452/126742350-d6aaa26f-76fd-43ed-8766-12c7816ba7ed.png)
I reset my repository, did a couple of commits and re-installed the plugin. 

Improvements:
- Obsidian is no longer hanging or blocking work
- error message has changed to: "Did not push. No upstream branch is set! See README for instructions"

**Comment by prakar** [comment]
At this point, it is the same as #76 

closing, since redundant
