### ISSUE TITLE
Error "Cannot run git command" during initialization

### ISSUE THREAD

**Issue by anchern** [denolehov/obsidian-git#89]
- Install Obsidian with snap
- Clone git repo by ssh
- Configure ssh key
- Enable the plugin and got an error: 'Cannot run git command"
- Status bar message: "git: failed on initialization!" 
- When the `spawnSync ` function is executing it returns such error: "spawnsync git ENOENT"

Ubuntu 20.04.2 LTS
obsidian version 0.12.5
git version 2.25.1

**Comment by Vinzent03** [comment]
Please read the [README](https://github.com/denolehov/obsidian-git#linux-installation). Obsidian installation via snap does not work.
