### ISSUE TITLE
Stuck on "pushing changes"

### ISSUE THREAD

**Issue by macedotavares** [denolehov/obsidian-git#9]
First of all: AWESOME plugin. It was the first one I installed and it's extremely useful as-is.

I installed it with no apparent errors. It pulls changes at startup and creates the commits, but it's stuck on "pushing changes". 
<img width="267" alt="Screenshot 2020-11-05 at 14 22 26" src="https://user-images.githubusercontent.com/687343/98261591-84d6af80-1f7c-11eb-99ad-e97d2dcf1325.png">

This shows up in the console:
<img width="907" alt="Screenshot 2020-11-05 at 14 21 01" src="https://user-images.githubusercontent.com/687343/98262063-12b29a80-1f7d-11eb-97c1-80260603f698.png">

If I push them manually, in the command line, all goes well.

Any clue about what's causing this? Am I missing something?

**Comment by denolehov** [comment]
Hey! This is weird, especially provided that you're able to push changes manually.

Does this happen when plugin automatically pushes changes? Or are you trying to push changes manually via shortcut?

Also, did you checkout to a new branch manually while Obsidian was open?

**Comment by macedotavares** [comment]
> especially provided that you're able to push changes manually.

Yeah, that's how I saw that the plugin was actually committing; when I pushed changes in the terminal, there were a lot of commits waiting to be pushed.

> Does this happen when plugin automatically pushes changes?

I don't think the plugin pushes changes at all. It just gets stuck there, I guess, and nothing shows up on Github. Currently, it says `last update 7 hours ago.`, despite being set to backup every 30 min.

> Or are you trying to push changes manually via shortcut?

I'm pushing changes manually using the macOS terminal.

**Comment by denolehov** [comment]
When plugin is stuck on pushing, does your repo have some uncommited changes? What is the output of `git status`?

**Comment by macedotavares** [comment]
I've just restarted Obsidian again, and noticed that the plugin has been updated. Let me see if the problem persists. If it does, I'l post `git status`here.

Cheers!

**Comment by macedotavares** [comment]
It's all good now. Thanks!

**Comment by denolehov** [comment]
Oh, nice! Did you do anything else besides updating plugin to the latest available version?

**Comment by macedotavares** [comment]
Nothing at all. After the plugin update, it just started to work normally. My repository has been getting all the changes.

BTW, the new commit message placeholders are very useful.

Again, awesome plugin. Thanks.

**Comment by denolehov** [comment]
Nice! I am happy that you find it useful! :)
