### ISSUE TITLE
Empty Commits

### ISSUE THREAD

**Issue by dotkiddo** [denolehov/obsidian-git#90]
# Please remove "empty" commits.

## Expected Behaviour:
If there are no user-generated changes to commit, no commit should be made.

### Result:
A clean git tree only showing user-generated content updates.

## Current Behaviour:
A commit is made every vault backup interval minutes whether there are any user-generated changes to commit or not.

### Result: 
A quickly growing git tree bloated with only lastAutoBackUp changed changes 
(by now > 3k commits in my git history and counting, many of these don't have any user-generated changes):

![image](https://user-images.githubusercontent.com/14318808/125300607-7c641f00-e32a-11eb-846b-002971449deb.png)

**Comment by Vinzent03** [comment]
Related to #78 . Will fix it this evening by storing this information in localStorage.

**Comment by dotkiddo** [comment]
Currently on version 1.9.1
Updating to 1.9.2 now, will update on the behaviour
