### ISSUE TITLE
Need a bot to commit

### ISSUE THREAD

**Issue by SettingDust** [denolehov/obsidian-git#94]
A github app is a bot that can sign commit. https://github.community/t/github-actions-bot-email-address/17204/5
Or a user like @GitJournalApp. Or not tons of commits will display in dashboard.

**Comment by Vinzent03** [comment]
I have no clue what you want.

**Comment by XDIJK** [comment]
If I understand @SettingDust correctly, they want their  commits from the plugin to be pushed to their repo by a bot user so that their commit graph in user dashboard stays free of those commits the plugin would otherwise make.

**Comment by Vinzent03** [comment]
Ah okay. That's not part of the plugin. All configuration needs to be done by the user itself. The email and username in `.git/config` needs to be edited.
