### ISSUE TITLE
Feature Request: Adding a button to the ribbon to manually push

### ISSUE THREAD

**Issue by L-mNguyen** [denolehov/obsidian-git#97]
Hi there, I've had a look but can't see this in the settings. Would it be possible to add a button to the highlighted area to manually push my changes?

![image](https://user-images.githubusercontent.com/52264769/128172827-4cfb4ac6-2257-4e71-b32c-cb03e583f911.png)

**Comment by Vinzent03** [comment]
There are commands in the command palette `CTRL + P`. Do you still want the ribbon?

**Comment by L-mNguyen** [comment]
Yes, it would be nice but it's not a big deal if this wasn't added.

**Comment by Vinzent03** [comment]
Because I don't want to put more and more settings to the plugin and the selection of icon would be hard, I am happy to recommend you this [plugin](https://github.com/phibr0/obsidian-customizable-sidebar) from my friend @phibr0

**Comment by L-mNguyen** [comment]
Perfect! Thanks @Vinzent03 & @phibr0
