### ISSUE TITLE
Feature request: integrate git rename with obsidian rename

### ISSUE THREAD

**Issue by datachampion** [denolehov/obsidian-git#98]
Thanks for developing this plugin!

I use git to sync my obsidian vault but have realised if I rename a file within obsidian, git sees this as a file deletion and subsequent creation of a new file. For a single note with no links to it from other notes, it's not too hard to just to a `git rename` from the command line. However this becomes a problem if I want to make the most of obsidian's function to update all links to a file when you rename it.

Would it be possible to somehow add a function to your plugin to integrate `git rename` with obsidian's rename (or just the update links) feature? This would make it possible to rename a file so that git sees it as a rename (not a deletion / creation) but also get the benefit of automatically updating internal links to the file from other notes.

Unfortunately I don't have the skills to do this!

Thanks so much for your time :-)

**Comment by Vinzent03** [comment]
Duplicate of #62 ? The command `git rename` doesn't even exist. I think you created yourself an alias.
Please run `git add .` and take again a look at `git status`

**Comment by datachampion** [comment]
Yes, you're absolutely right - it's a duplicate. Sorry for missing that, I was obviously having a bad day - I meant to write `git mv` too!
Thanks ever so much for the explanation.

**Comment by Vinzent03** [comment]
No problem!
